-- Run this in the Supabase SQL editor (Database > SQL Editor).
-- Safe to re-run: every insert is `on conflict ... do nothing`, so it only
-- ever adds what's missing — it never edits or deletes existing rows.
--
-- Landmarks batch 4: 584 more landmarks across 86 countries
-- (Asia, Oceania and the Americas), plus any missing cities. Run after scripts/add_landmarks.sql
-- (1–98, add_landmarks_2.sql: 100–515, and add_landmarks_3.sql: 600–1274); none of the places repeat what those files already added.
-- Like add_landmarks_2.sql this file does NOT create `catalog_highlights`
-- ("Yeni eklenenler") rows — the home rail only shows the newest 20, so a
-- bulk import would push every curated highlight off it. Highlight
-- individual landmarks later from the admin panel or with the snippet at the
-- bottom. Photos are left empty on purpose — upload them from the admin panel.
--
-- To add more, append rows to the `_new_landmarks` values list (keep `ord`
-- increasing and above the current max) and re-run the whole file.
-- `country_id` is the `id` from data/worldCountries.json, not a name lookup.

begin;

create temp table _new_landmarks (
  ord int not null,
  country_id text not null,
  city text not null,
  city_tr text,
  name text not null,
  name_tr text,
  description text,
  description_tr text
) on commit drop;

insert into _new_landmarks
  (ord, country_id, city, city_tr, name, name_tr, description, description_tr)
values
  (1374, '392', 'Tokyo', 'Tokyo', 'Meiji Shrine', 'Meiji Tapınağı', 'A forest shrine in the heart of Tokyo.', 'Tokyo''nun kalbinde ormanlık tapınak.'),
  (1375, '392', 'Tokyo', 'Tokyo', 'Shinjuku Gyoen', 'Shinjuku Gyoen', 'A large garden famed for cherry blossoms.', 'Kiraz çiçekleriyle ünlü geniş bahçe.'),
  (1376, '392', 'Tokyo', 'Tokyo', 'Akihabara', 'Akihabara', 'The electric town of anime and gaming.', 'Anime ve oyun dünyasının elektrik kasabası.'),
  (1377, '392', 'Tokyo', 'Tokyo', 'Tsukiji Outer Market', 'Tsukiji Dış Pazarı', 'Street food and fresh seafood stalls.', 'Sokak yemekleri ve taze deniz ürünü tezgâhları.'),
  (1378, '392', 'Tokyo', 'Tokyo', 'Tokyo Tower', 'Tokyo Kulesi', 'The red-and-white Eiffel-inspired tower.', 'Eyfel''den esinlenen kırmızı-beyaz kule.'),
  (1379, '392', 'Tokyo', 'Tokyo', 'teamLab Planets', 'teamLab Planets', 'A walk-through digital art museum.', 'İçinde yürünen dijital sanat müzesi.'),
  (1380, '392', 'Tokyo', 'Tokyo', 'Imperial Palace East Gardens', 'İmparatorluk Sarayı Doğu Bahçeleri', 'Gardens on the former Edo Castle grounds.', 'Eski Edo Kalesi arazisinde bahçeler.'),
  (1381, '392', 'Tokyo', 'Tokyo', 'Harajuku Takeshita Street', 'Harajuku Takeshita Caddesi', 'The heart of Japan''s youth fashion.', 'Japon gençlik modasının kalbi.'),
  (1382, '392', 'Tokyo', 'Tokyo', 'Ghibli Museum', 'Ghibli Müzesi', 'A whimsical museum of Studio Ghibli.', 'Studio Ghibli''nin hayal dolu müzesi.'),
  (1383, '392', 'Kyoto', 'Kyoto', 'Kiyomizu-dera', 'Kiyomizu-dera', 'A wooden temple stage over the hillside.', 'Yamaç üzerinde ahşap tapınak terası.'),
  (1384, '392', 'Kyoto', 'Kyoto', 'Gion District', 'Gion Bölgesi', 'Geisha quarter of wooden teahouses.', 'Ahşap çay evleriyle geyşa mahallesi.'),
  (1385, '392', 'Kyoto', 'Kyoto', 'Nijo Castle', 'Nijo Kalesi', 'A shogun''s castle with nightingale floors.', 'Ötücü kuş döşemeli şogun kalesi.'),
  (1386, '392', 'Kyoto', 'Kyoto', 'Ginkaku-ji (Silver Pavilion)', 'Ginkaku-ji (Gümüş Köşk)', 'A serene temple and moss garden.', 'Sakin tapınak ve yosun bahçesi.'),
  (1387, '392', 'Kyoto', 'Kyoto', 'Philosopher''s Path', 'Filozof Yolu', 'A canal-side stroll lined with cherry trees.', 'Kiraz ağaçlı kanal kenarı yürüyüş yolu.'),
  (1388, '392', 'Osaka', 'Osaka', 'Dotonbori', 'Dotonbori', 'Neon lights and street food by the canal.', 'Kanal kenarında neon ışıklar ve sokak yemekleri.'),
  (1389, '392', 'Osaka', 'Osaka', 'Universal Studios Japan', 'Universal Studios Japonya', 'Home of Super Nintendo World.', 'Super Nintendo World''ün yurdu.'),
  (1390, '392', 'Hiroshima', 'Hiroşima', 'Hiroshima Peace Memorial', 'Hiroşima Barış Anıtı', 'The Atomic Bomb Dome and peace park.', 'Atom Bombası Kubbesi ve barış parkı.'),
  (1391, '392', 'Himeji', 'Himeji', 'Himeji Castle', 'Himeji Kalesi', 'Japan''s most beautiful original castle.', 'Japonya''nın en güzel özgün kalesi.'),
  (1392, '392', 'Nikko', 'Nikko', 'Nikko Toshogu Shrine', 'Nikko Toshogu Tapınağı', 'An ornate shrine amid cedar forest.', 'Sedir ormanında süslü tapınak.'),
  (1393, '392', 'Kanazawa', 'Kanazawa', 'Kenroku-en', 'Kenroku-en', 'One of Japan''s three great gardens.', 'Japonya''nın üç büyük bahçesinden biri.'),
  (1394, '392', 'Shirakawa-go', 'Shirakawa-go', 'Shirakawa-go', 'Shirakawa-go', 'Thatched gassho-zukuri farmhouses in the mountains.', 'Dağlarda çatılı gassho-zukuri çiftlik evleri.'),
  (1395, '392', 'Hakone', 'Hakone', 'Hakone', 'Hakone', 'Hot springs and Mount Fuji views.', 'Kaplıcalar ve Fuji manzarası.'),
  (1396, '392', 'Koyasan', 'Koyasan', 'Koyasan Okunoin', 'Koyasan Okunoin', 'A cemetery and temple retreat in a cedar forest.', 'Sedir ormanında mezarlık ve tapınak inzivası.'),
  (1397, '392', 'Kamakura', 'Kamakura', 'Great Buddha of Kamakura', 'Kamakura Büyük Buda', 'A bronze Buddha statue under open sky.', 'Açık gökyüzü altında bronz Buda heykeli.'),
  (1398, '392', 'Nagasaki', 'Nagazaki', 'Nagasaki Peace Park', 'Nagazaki Barış Parkı', 'A memorial of the 1945 bombing.', '1945 bombardımanının anıtı.'),
  (1399, '392', 'Sapporo', 'Sapporo', 'Sapporo Snow Festival', 'Sapporo Kar Festivali', 'Giant ice and snow sculptures.', 'Dev buz ve kar heykelleri.'),
  (1400, '392', 'Okinawa', 'Okinawa', 'Churaumi Aquarium', 'Churaumi Akvaryumu', 'A giant tank with whale sharks.', 'Balina köpekbalıklı dev tank.'),
  (1401, '392', 'Yakushima', 'Yakushima', 'Yakushima Ancient Cedars', 'Yakushima Antik Sedirleri', 'A moss forest that inspired Princess Mononoke.', 'Prenses Mononoke''ye ilham veren yosun ormanı.'),
  (1402, '392', 'Takayama', 'Takayama', 'Takayama Old Town', 'Takayama Eski Şehir', 'Edo-era streets and sake breweries.', 'Edo dönemi sokaklar ve sake imalathaneleri.'),
  (1403, '392', 'Kawaguchiko', 'Kawaguchiko', 'Lake Kawaguchi', 'Kawaguchi Gölü', 'The classic Mount Fuji reflection.', 'Klasik Fuji Dağı yansıması.'),
  (1404, '392', 'Matsumoto', 'Matsumoto', 'Matsumoto Castle', 'Matsumoto Kalesi', 'A black ''Crow Castle'' from the 16th century.', '16. yüzyıldan kara ''Karga Kalesi''.'),
  (1405, '392', 'Naoshima', 'Naoshima', 'Naoshima Art Island', 'Naoshima Sanat Adası', 'Yayoi Kusama''s pumpkin and modern art.', 'Yayoi Kusama''nın balkabağı ve modern sanat.'),
  (1406, '392', 'Nara', 'Nara', 'Todai-ji', 'Todai-ji', 'A giant Buddha inside a huge wooden hall.', 'Dev ahşap salonda dev Buda.'),
  (1407, '156', 'Beijing', 'Pekin', 'Summer Palace', 'Yaz Sarayı', 'A lakeside imperial garden.', 'Göl kıyısında imparatorluk bahçesi.'),
  (1408, '156', 'Beijing', 'Pekin', 'Tiananmen Square', 'Tiananmen Meydanı', 'One of the world''s largest public squares.', 'Dünyanın en büyük meydanlarından biri.'),
  (1409, '156', 'Beijing', 'Pekin', 'Mutianyu Great Wall', 'Mutianyu Çin Seddi', 'A restored, scenic section of the Great Wall.', 'Çin Seddi''nin restore edilmiş manzaralı bölümü.'),
  (1410, '156', 'Beijing', 'Pekin', 'Lama Temple', 'Lama Tapınağı', 'A Tibetan Buddhist temple in the city.', 'Şehir içinde Tibet Budist tapınağı.'),
  (1411, '156', 'Hong Kong', 'Hong Kong', 'Victoria Peak', 'Victoria Tepesi', 'The best view of Hong Kong''s skyline.', 'Hong Kong silüetinin en iyi manzarası.'),
  (1412, '156', 'Hong Kong', 'Hong Kong', 'Tian Tan Buddha', 'Tian Tan Buddha', 'A 34-metre bronze Buddha on Lantau.', 'Lantau''da 34 metrelik bronz Buda.'),
  (1413, '156', 'Hong Kong', 'Hong Kong', 'Star Ferry', 'Star Ferry', 'A century-old ferry across Victoria Harbour.', 'Victoria Limanı''nda yüzyıllık feribot.'),
  (1414, '156', 'Macau', 'Makao', 'Ruins of St. Paul''s', 'Aziz Pavlus Kalıntıları', 'A baroque church facade on a hill.', 'Tepede barok kilise cephesi.'),
  (1415, '156', 'Shanghai', 'Şanghay', 'Yu Garden', 'Yu Bahçesi', 'A classical garden in the old city.', 'Eski şehirde klasik bahçe.'),
  (1416, '156', 'Shanghai', 'Şanghay', 'Oriental Pearl Tower', 'Doğu İncisi Kulesi', 'A futuristic TV tower with pink spheres.', 'Pembe kürelerle fütüristik televizyon kulesi.'),
  (1417, '156', 'Hangzhou', 'Hangzhou', 'West Lake', 'Batı Gölü', 'A poetic lake of pagodas and willows.', 'Pagodalar ve söğütlerle şiirsel göl.'),
  (1418, '156', 'Suzhou', 'Suzhou', 'Classical Gardens of Suzhou', 'Suzhou Klasik Bahçeleri', 'Scholar gardens of pavilions and ponds.', 'Köşkler ve göletlerle bilgin bahçeleri.'),
  (1419, '156', 'Lhasa', 'Lhasa', 'Potala Palace', 'Potala Sarayı', 'The Dalai Lamas'' palace on a hill.', 'Dalay Lamaların tepedeki sarayı.'),
  (1420, '156', 'Lhasa', 'Lhasa', 'Jokhang Temple', 'Jokhang Tapınağı', 'Tibet''s holiest temple.', 'Tibet''in en kutsal tapınağı.'),
  (1421, '156', 'Huangshan', 'Huangshan', 'Huangshan (Yellow Mountains)', 'Huangshan (Sarı Dağlar)', 'Granite peaks above a sea of clouds.', 'Bulut denizi üzerinde granit zirveler.'),
  (1422, '156', 'Jiuzhaigou', 'Jiuzhaigou', 'Jiuzhaigou Valley', 'Jiuzhaigou Vadisi', 'Multi-colored lakes and waterfalls.', 'Çok renkli göller ve şelaleler.'),
  (1423, '156', 'Dunhuang', 'Dunhuang', 'Mogao Caves', 'Mogao Mağaraları', 'Buddhist cave temples with ancient murals.', 'Antik duvar resimli Budist mağara tapınakları.'),
  (1424, '156', 'Harbin', 'Harbin', 'Harbin Ice and Snow Festival', 'Harbin Buz ve Kar Festivali', 'Glowing ice castles in winter.', 'Kışın parlayan buz kaleleri.'),
  (1425, '156', 'Leshan', 'Leshan', 'Leshan Giant Buddha', 'Leshan Dev Buda', 'A 71-metre Buddha carved in a cliff.', 'Kayalığa oyulmuş 71 metrelik Buda.'),
  (1426, '156', 'Chongqing', 'Chongqing', 'Hongya Cave', 'Hongya Mağarası', 'A stilted riverfront complex lit at night.', 'Geceleri aydınlanan kazıklı nehir kıyısı kompleksi.'),
  (1427, '156', 'Zhangye', 'Zhangye', 'Zhangye Danxia Landform', 'Zhangye Danxia Oluşumu', 'Rainbow-colored sandstone hills.', 'Gökkuşağı renkli kumtaşı tepeler.'),
  (1428, '156', 'Lijiang', 'Lijiang', 'Lijiang Old Town', 'Lijiang Eski Şehir', 'A canal-woven Naxi town.', 'Kanallarla örülü Naxi kasabası.'),
  (1429, '156', 'Lijiang', 'Lijiang', 'Tiger Leaping Gorge', 'Kaplan Sıçrayışı Vadisi', 'One of the deepest gorges on Earth.', 'Dünyanın en derin vadilerinden biri.'),
  (1430, '156', 'Guangzhou', 'Guangzhou', 'Canton Tower', 'Canton Kulesi', 'A twisting hourglass-shaped tower.', 'Bükülen kum saati biçimli kule.'),
  (1431, '156', 'Xi''an', 'Xi''an', 'Xi''an City Wall', 'Xi''an Şehir Surları', 'A cyclable Ming-era wall.', 'Bisikletle gezilebilen Ming dönemi sur.'),
  (1432, '156', 'Kashgar', 'Kaşgar', 'Kashgar Old City', 'Kaşgar Eski Şehir', 'A Silk Road oasis with a Sunday market.', 'Pazar pazarıyla İpek Yolu vahası.'),
  (1433, '156', 'Pingyao', 'Pingyao', 'Pingyao Ancient City', 'Pingyao Antik Şehri', 'A perfectly walled Ming-Qing city.', 'Mükemmel surlu Ming-Qing şehri.'),
  (1434, '156', 'Longsheng', 'Longsheng', 'Longji Rice Terraces', 'Longji Pirinç Terasları', 'Dragon''s-backbone terraces.', 'Ejderha omurgası terasları.'),
  (1435, '156', 'Shenzhen', 'Şenzen', 'Window of the World', 'Dünyanın Penceresi', 'Miniature world landmarks in a park.', 'Parkta minyatür dünya simgeleri.'),
  (1436, '158', 'Taichung', 'Taichung', 'Sun Moon Lake', 'Sun Moon Gölü', 'Taiwan''s largest and most scenic lake.', 'Tayvan''ın en büyük ve güzel gölü.'),
  (1437, '158', 'Chiayi', 'Chiayi', 'Alishan', 'Alishan', 'Forest railway, sunrise and tea.', 'Orman treni, gün doğumu ve çay.'),
  (1438, '158', 'Kenting', 'Kenting', 'Kenting National Park', 'Kenting Milli Parkı', 'A tropical southern tip with beaches.', 'Plajlı tropikal güney ucu.'),
  (1439, '158', 'Pingxi', 'Pingxi', 'Shifen Sky Lanterns', 'Shifen Gökyüzü Fenerleri', 'Release lanterns along the railway.', 'Demiryolu boyunca fener uçurma.'),
  (1440, '158', 'Taipei', 'Taipei', 'National Palace Museum', 'Ulusal Saray Müzesi', 'Chinese imperial treasures.', 'Çin imparatorluk hazineleri.'),
  (1441, '158', 'Taipei', 'Taipei', 'Chiang Kai-shek Memorial Hall', 'Chiang Kai-shek Anıt Salonu', 'A white-and-blue hall with a large plaza.', 'Geniş meydanlı beyaz-mavi salon.'),
  (1442, '158', 'Yehliu', 'Yehliu', 'Yehliu Geopark', 'Yehliu Jeoparkı', 'Wind-carved rocks, including the Queen''s Head.', 'Kraliçe''nin Başı dahil rüzgârın oyduğu kayalar.'),
  (1443, '158', 'Tainan', 'Tainan', 'Fort Zeelandia (Anping)', 'Zeelandia Kalesi (Anping)', 'A Dutch colonial fort.', 'Hollanda sömürge kalesi.'),
  (1444, '410', 'Seoul', 'Seul', 'Changdeokgung Palace', 'Changdeokgung Sarayı', 'A UNESCO palace with a secret garden.', 'Gizli bahçeli UNESCO sarayı.'),
  (1445, '410', 'Seoul', 'Seul', 'Dongdaemun Design Plaza', 'Dongdaemun Tasarım Plazası', 'A curvy silver building by Zaha Hadid.', 'Zaha Hadid''in kıvrımlı gümüş yapısı.'),
  (1446, '410', 'Seoul', 'Seul', 'Myeongdong', 'Myeongdong', 'A shopping and street food district.', 'Alışveriş ve sokak yemeği bölgesi.'),
  (1447, '410', 'Seoul', 'Seul', 'Lotte World Tower', 'Lotte World Tower', 'A 555-metre skyscraper with a sky deck.', 'Seyir terasıyla 555 metrelik gökdelen.'),
  (1448, '410', 'Gyeongju', 'Gyeongju', 'Bulguksa Temple', 'Bulguksa Tapınağı', 'A Silla-era temple of stone terraces.', 'Silla dönemi taş teraslı tapınak.'),
  (1449, '410', 'Gangwon', 'Gangwon', 'Seoraksan National Park', 'Seoraksan Milli Parkı', 'Jagged peaks and autumn foliage.', 'Sivri zirveler ve sonbahar yaprakları.'),
  (1450, '410', 'Paju', 'Paju', 'DMZ and Joint Security Area', 'DMZ ve Ortak Güvenlik Bölgesi', 'The border between North and South Korea.', 'Kuzey ve Güney Kore sınırı.'),
  (1451, '410', 'Jeonju', 'Jeonju', 'Jeonju Hanok Village', 'Jeonju Hanok Köyü', 'Home to bibimbap and 700 hanoks.', 'Bibimbap''ın ve 700 hanok''un yurdu.'),
  (1452, '410', 'Busan', 'Busan', 'Haeundae Beach', 'Haeundae Plajı', 'Korea''s most famous beach.', 'Kore''nin en ünlü plajı.'),
  (1453, '410', 'Jeju', 'Jeju', 'Hallasan', 'Hallasan', 'South Korea''s highest peak and volcano.', 'Güney Kore''nin en yüksek zirvesi ve yanardağı.'),
  (1454, '410', 'Suwon', 'Suwon', 'Hwaseong Fortress', 'Hwaseong Kalesi', 'An 18th-century fortress wall.', '18. yüzyıldan kale duvarı.'),
  (1455, '410', 'Chuncheon', 'Chuncheon', 'Nami Island', 'Nami Adası', 'A tree-lined island from a K-drama.', 'Dizi setiyle ünlü ağaçlı ada.'),
  (1456, '356', 'Mumbai', 'Mumbai', 'Gateway of India', 'Hindistan Kapısı', 'A harbour arch from the British Raj.', 'İngiliz Raj döneminden liman kemeri.'),
  (1457, '356', 'Mumbai', 'Mumbai', 'Marine Drive', 'Marine Drive', 'A curved promenade called the Queen''s Necklace.', 'Kraliçe''nin Gerdanlığı denen kavisli yürüyüş yolu.'),
  (1458, '356', 'Mumbai', 'Mumbai', 'Elephanta Caves', 'Elephanta Mağaraları', 'Rock-cut Shiva temples on an island.', 'Adada kayaya oyma Şiva tapınakları.'),
  (1459, '356', 'Goa', 'Goa', 'Basilica of Bom Jesus', 'Bom Jesus Bazilikası', 'A baroque church housing a saint''s relics.', 'Bir azizin kalıntılarını barındıran barok kilise.'),
  (1460, '356', 'Hyderabad', 'Haydarabad', 'Charminar', 'Charminar', 'A 16th-century mosque with four minarets.', 'Dört minareli 16. yüzyıl yapısı.'),
  (1461, '356', 'Mysore', 'Mysore', 'Mysore Palace', 'Mysore Sarayı', 'An Indo-Saracenic palace lit by thousands of bulbs.', 'Binlerce ampulle aydınlanan Hint-Sarasen sarayı.'),
  (1462, '356', 'Hampi', 'Hampi', 'Hampi', 'Hampi', 'Boulder-strewn ruins of Vijayanagara.', 'Kayalarla dolu Vijayanagara kalıntıları.'),
  (1463, '356', 'Aurangabad', 'Aurangabad', 'Ajanta and Ellora Caves', 'Ajanta ve Ellora Mağaraları', 'Ancient rock-cut cave temples.', 'Antik kayaya oyma mağara tapınakları.'),
  (1464, '356', 'Khajuraho', 'Khajuraho', 'Khajuraho Temples', 'Khajuraho Tapınakları', 'Sculpted temples of medieval India.', 'Ortaçağ Hindistan''ının heykel işlemeli tapınakları.'),
  (1465, '356', 'Jaisalmer', 'Jaisalmer', 'Jaisalmer Fort', 'Jaisalmer Kalesi', 'A living golden fort in the Thar Desert.', 'Thar Çölü''nde yaşayan altın kale.'),
  (1466, '356', 'Jodhpur', 'Jodhpur', 'Mehrangarh Fort', 'Mehrangarh Kalesi', 'A fort towering above the blue city.', 'Mavi şehrin üzerinde yükselen kale.'),
  (1467, '356', 'Pushkar', 'Pushkar', 'Pushkar Lake', 'Pushkar Gölü', 'A sacred lake and camel fair town.', 'Kutsal göl ve deve fuarı kasabası.'),
  (1468, '356', 'Darjeeling', 'Darjeeling', 'Darjeeling Himalayan Railway', 'Darjeeling Himalaya Demiryolu', 'A toy train through tea hills.', 'Çay tepelerinden geçen oyuncak tren.'),
  (1469, '356', 'Rishikesh', 'Rishikesh', 'Rishikesh Laxman Jhula', 'Rishikesh Laxman Jhula', 'The yoga capital on the Ganges.', 'Ganj kıyısında yoga başkenti.'),
  (1470, '356', 'Ladakh', 'Ladakh', 'Pangong Lake', 'Pangong Gölü', 'A high-altitude lake changing blues.', 'Mavinin tonlarını değiştiren yüksek rakımlı göl.'),
  (1471, '356', 'Kolkata', 'Kalküta', 'Victoria Memorial', 'Victoria Anıtı', 'A white marble memorial and museum.', 'Beyaz mermer anıt ve müze.'),
  (1472, '356', 'Madurai', 'Madurai', 'Meenakshi Amman Temple', 'Meenakshi Amman Tapınağı', 'A towering, brightly painted Hindu temple.', 'Yüksek ve canlı boyalı Hindu tapınağı.'),
  (1473, '356', 'Konark', 'Konark', 'Konark Sun Temple', 'Konark Güneş Tapınağı', 'A chariot-shaped temple of the sun god.', 'Güneş tanrısının araba biçimli tapınağı.'),
  (1474, '356', 'Munnar', 'Munnar', 'Munnar Tea Gardens', 'Munnar Çay Bahçeleri', 'Rolling hills of tea plantations.', 'Çay tarlalarıyla kaplı tepeler.'),
  (1475, '356', 'Delhi', 'Delhi', 'Qutub Minar', 'Kutub Minar', 'A 73-metre brick minaret from 1200.', '1200''den 73 metrelik tuğla minare.'),
  (1476, '356', 'Delhi', 'Delhi', 'Humayun''s Tomb', 'Hümayun Türbesi', 'A garden tomb that inspired the Taj Mahal.', 'Tac Mahal''e ilham veren bahçe türbesi.'),
  (1477, '356', 'Delhi', 'Delhi', 'Lotus Temple', 'Lotus Tapınağı', 'A lotus-shaped Bahai house of worship.', 'Lotus biçimli Bahai ibadethanesi.'),
  (1478, '356', 'Agra', 'Agra', 'Agra Fort', 'Agra Kalesi', 'A red sandstone Mughal fortress.', 'Kırmızı kumtaşı Babür kalesi.'),
  (1479, '356', 'Fatehpur Sikri', 'Fatehpur Sikri', 'Fatehpur Sikri', 'Fatehpur Sikri', 'A deserted Mughal imperial city.', 'Terk edilmiş Babür imparatorluk şehri.'),
  (1480, '356', 'Jaipur', 'Jaipur', 'Hawa Mahal', 'Hawa Mahal', 'The pink ''Palace of Winds'' facade.', 'Pembe ''Rüzgârlar Sarayı'' cephesi.'),
  (1481, '356', 'Uttarakhand', 'Uttarakhand', 'Valley of Flowers', 'Çiçekler Vadisi', 'An alpine meadow bursting with blooms.', 'Çiçeklerle dolu alpin çayır.'),
  (1482, '524', 'Kathmandu', 'Kathmandu', 'Pashupatinath Temple', 'Pashupatinath Tapınağı', 'A sacred Hindu temple on the Bagmati River.', 'Bagmati Nehri''nde kutsal Hindu tapınağı.'),
  (1483, '524', 'Kathmandu', 'Kathmandu', 'Durbar Square', 'Durbar Meydanı', 'Medieval palaces and pagodas.', 'Ortaçağ sarayları ve pagodalar.'),
  (1484, '524', 'Annapurna', 'Annapurna', 'Annapurna Circuit', 'Annapurna Parkuru', 'A classic Himalayan trek.', 'Klasik Himalaya trekking rotası.'),
  (1485, '524', 'Chitwan', 'Chitwan', 'Chitwan National Park', 'Chitwan Milli Parkı', 'Rhinos and tigers in the jungle.', 'Ormanda gergedan ve kaplanlar.'),
  (1486, '524', 'Lumbini', 'Lumbini', 'Lumbini', 'Lumbini', 'The birthplace of the Buddha.', 'Buda''nın doğum yeri.'),
  (1487, '524', 'Nagarkot', 'Nagarkot', 'Nagarkot Sunrise', 'Nagarkot Gün Doğumu', 'A hill viewpoint over the Himalayas.', 'Himalayalar''a bakan tepe seyir noktası.'),
  (1488, '064', 'Punakha', 'Punakha', 'Punakha Dzong', 'Punakha Dzong', 'A fortress at the meeting of two rivers.', 'İki nehrin birleştiği yerde kale.'),
  (1489, '064', 'Dochula', 'Dochula', 'Dochula Pass', 'Dochula Geçidi', '108 stupas and Himalayan views.', '108 stupa ve Himalaya manzarası.'),
  (1490, '064', 'Phobjikha', 'Phobjikha', 'Phobjikha Valley', 'Phobjikha Vadisi', 'A glacial valley of black-necked cranes.', 'Kara boyunlu turnalarla buzul vadisi.'),
  (1491, '144', 'Yala', 'Yala', 'Yala National Park', 'Yala Milli Parkı', 'Leopards and elephants on safari.', 'Safaride leoparlar ve filler.'),
  (1492, '144', 'Dambulla', 'Dambulla', 'Dambulla Cave Temple', 'Dambulla Mağara Tapınağı', 'Painted Buddhist caves.', 'Boyalı Budist mağaralar.'),
  (1493, '144', 'Anuradhapura', 'Anuradhapura', 'Anuradhapura', 'Anuradhapura', 'An ancient Sinhalese capital.', 'Antik Sinhala başkenti.'),
  (1494, '144', 'Polonnaruwa', 'Polonnaruwa', 'Polonnaruwa', 'Polonnaruwa', 'Ruins of a medieval royal city.', 'Ortaçağ kraliyet şehrinin kalıntıları.'),
  (1495, '144', 'Nuwara Eliya', 'Nuwara Eliya', 'Nuwara Eliya Tea Country', 'Nuwara Eliya Çay Bölgesi', 'Cool hills of tea estates.', 'Çay bahçeleriyle serin tepeler.'),
  (1496, '144', 'Mirissa', 'Mirissa', 'Mirissa Whale Watching', 'Mirissa Balina Gözlemi', 'Blue whales off the south coast.', 'Güney kıyısında mavi balinalar.'),
  (1497, '144', 'Adam''s Peak', 'Adam''s Peak', 'Adam''s Peak', 'Adem Tepesi', 'A sacred mountain climbed at night.', 'Geceleri tırmanılan kutsal dağ.'),
  (1498, '462', 'Male', 'Malé', 'Malé Grand Friday Mosque', 'Malé Büyük Cuma Camii', 'The capital''s oldest mosque with golden dome.', 'Başkentin altın kubbeli en eski camisi.'),
  (1499, '462', 'Raa Atoll', 'Raa Atolü', 'Vaadhoo Sea of Stars', 'Vaadhoo Yıldızlar Denizi', 'Bioluminescent waves glowing blue at night.', 'Geceleri mavi parlayan biyolüminesan dalgalar.'),
  (1500, '462', 'Maafushi', 'Maafushi', 'Maafushi Local Island', 'Maafushi Yerel Ada', 'An affordable local island experience.', 'Uygun fiyatlı yerel ada deneyimi.'),
  (1501, '586', 'Lahore', 'Lahor', 'Lahore Fort', 'Lahor Kalesi', 'A Mughal citadel with mirrored palaces.', 'Aynalı saraylarıyla Babür kalesi.'),
  (1502, '586', 'Islamabad', 'İslamabad', 'Faisal Mosque', 'Faysal Camii', 'A tent-shaped mosque below the Margalla Hills.', 'Margalla Tepeleri altında çadır biçimli cami.'),
  (1503, '586', 'Moenjodaro', 'Mohenjo-daro', 'Mohenjo-daro', 'Mohenjo-daro', 'A 4,500-year-old Indus Valley city.', '4500 yıllık İndus Vadisi şehri.'),
  (1504, '586', 'Gilgit', 'Gilgit', 'Fairy Meadows', 'Peri Çayırları', 'A meadow facing Nanga Parbat.', 'Nanga Parbat''a bakan çayır.'),
  (1505, '586', 'Karakoram', 'Karakoram', 'K2 Base Camp', 'K2 Base Kampı', 'A trek to the world''s second-highest peak.', 'Dünyanın ikinci yüksek zirvesine trek.'),
  (1506, '586', 'Thatta', 'Thatta', 'Shah Jahan Mosque, Thatta', 'Şah Cihan Camii, Thatta', 'A mosque with mosaic tilework.', 'Mozaik çinili cami.'),
  (1507, '586', 'Karachi', 'Karaçi', 'Mazar-e-Quaid', 'Kaid-i Azam Türbesi', 'The mausoleum of Pakistan''s founder.', 'Pakistan''ın kurucusunun türbesi.'),
  (1508, '050', 'Cox''s Bazar', 'Cox''s Bazar', 'Cox''s Bazar Beach', 'Cox''s Bazar Plajı', 'One of the world''s longest natural beaches.', 'Dünyanın en uzun doğal plajlarından biri.'),
  (1509, '050', 'Bagerhat', 'Bagerhat', 'Sixty Dome Mosque', 'Altmış Kubbe Camii', 'A 15th-century brick mosque.', '15. yüzyıl tuğla camisi.'),
  (1510, '050', 'Dhaka', 'Dakka', 'Ahsan Manzil', 'Ahsan Manzil', 'The pink palace on the Buriganga.', 'Buriganga kıyısında pembe saray.'),
  (1511, '050', 'Sylhet', 'Sylhet', 'Srimangal Tea Gardens', 'Srimangal Çay Bahçeleri', 'The tea capital of Bangladesh.', 'Bangladeş''in çay başkenti.'),
  (1512, '104', 'Mandalay', 'Mandalay', 'U Bein Bridge', 'U Bein Köprüsü', 'The world''s longest teak bridge.', 'Dünyanın en uzun tik köprüsü.'),
  (1513, '104', 'Mandalay', 'Mandalay', 'Mandalay Hill', 'Mandalay Tepesi', 'A pagoda-topped hill over the city.', 'Şehre bakan pagodalı tepe.'),
  (1514, '104', 'Kyaiktiyo', 'Kyaiktiyo', 'Golden Rock Pagoda', 'Altın Kaya Pagodası', 'A gilded boulder balanced on a cliff.', 'Uçurumda dengede duran yaldızlı kaya.'),
  (1515, '104', 'Ngapali', 'Ngapali', 'Ngapali Beach', 'Ngapali Plajı', 'A quiet Bay of Bengal beach.', 'Bengal Körfezi''nde sakin plaj.'),
  (1516, '104', 'Mrauk U', 'Mrauk U', 'Mrauk U Temples', 'Mrauk U Tapınakları', 'Temples of a lost Arakan kingdom.', 'Kayıp Arakan krallığının tapınakları.'),
  (1517, '418', 'Vientiane', 'Vientiane', 'Pha That Luang', 'Pha That Luang', 'A golden stupa, symbol of Laos.', 'Laos''un sembolü altın stupa.'),
  (1518, '418', 'Vang Vieng', 'Vang Vieng', 'Vang Vieng', 'Vang Vieng', 'Karst peaks, blue lagoons and tubing.', 'Karst zirveleri, mavi lagünler ve tüp ile akıntı.'),
  (1519, '418', 'Xieng Khouang', 'Xieng Khouang', 'Plain of Jars', 'Küpler Ovası', 'Mysterious ancient stone jars.', 'Gizemli antik taş küpler.'),
  (1520, '418', 'Si Phan Don', 'Si Phan Don', 'Four Thousand Islands', 'Dört Bin Ada', 'Mekong islands and river dolphins.', 'Mekong adaları ve nehir yunusları.'),
  (1521, '418', 'Champasak', 'Champasak', 'Wat Phou', 'Wat Phou', 'A Khmer temple on a hillside.', 'Yamaçta Khmer tapınağı.'),
  (1522, '764', 'Bangkok', 'Bangkok', 'Wat Pho', 'Wat Pho', 'The giant Reclining Buddha temple.', 'Dev Uzanmış Buda tapınağı.'),
  (1523, '764', 'Bangkok', 'Bangkok', 'Chatuchak Weekend Market', 'Chatuchak Hafta Sonu Pazarı', 'A vast market of 15,000 stalls.', '15.000 tezgâhlı dev pazar.'),
  (1524, '764', 'Bangkok', 'Bangkok', 'Damnoen Saduak Floating Market', 'Damnoen Saduak Yüzen Pazarı', 'Boats of fruit and food on canals.', 'Kanallarda meyve ve yemek dolu tekneler.'),
  (1525, '764', 'Bangkok', 'Bangkok', 'Khao San Road', 'Khao San Caddesi', 'The backpacker hub of Bangkok.', 'Bangkok''un sırt çantalı gezgin merkezi.'),
  (1526, '764', 'Chiang Rai', 'Chiang Rai', 'White Temple (Wat Rong Khun)', 'Beyaz Tapınak (Wat Rong Khun)', 'A dazzling white contemporary temple.', 'Göz alıcı beyaz çağdaş tapınak.'),
  (1527, '764', 'Sukhothai', 'Sukhothai', 'Sukhothai Historical Park', 'Sukhothai Tarihi Parkı', 'The first capital of Siam.', 'Siyam''ın ilk başkenti.'),
  (1528, '764', 'Kanchanaburi', 'Kanchanaburi', 'Bridge over the River Kwai', 'Kwai Nehri Köprüsü', 'The WWII railway bridge.', 'İkinci Dünya Savaşı demiryolu köprüsü.'),
  (1529, '764', 'Kanchanaburi', 'Kanchanaburi', 'Erawan Falls', 'Erawan Şelaleleri', 'Seven tiers of emerald pools.', 'Yedi kademeli zümrüt havuzlar.'),
  (1530, '764', 'Koh Samui', 'Koh Samui', 'Koh Samui Big Buddha', 'Koh Samui Büyük Buda', 'A 12-metre golden Buddha by the sea.', 'Deniz kıyısında 12 metrelik altın Buda.'),
  (1531, '764', 'Koh Tao', 'Koh Tao', 'Koh Tao', 'Koh Tao', 'A diving island of clear water.', 'Berrak sulu dalış adası.'),
  (1532, '764', 'Pai', 'Pai', 'Pai', 'Pai', 'A laid-back mountain town.', 'Rahat dağ kasabası.'),
  (1533, '764', 'Khao Sok', 'Khao Sok', 'Khao Sok National Park', 'Khao Sok Milli Parkı', 'Rainforest and limestone-ringed lake.', 'Yağmur ormanı ve kireçtaşıyla çevrili göl.'),
  (1534, '764', 'Phang Nga', 'Phang Nga', 'James Bond Island', 'James Bond Adası', 'A limestone needle in Phang Nga Bay.', 'Phang Nga Körfezi''nde kireçtaşı iğne.'),
  (1535, '764', 'Similan', 'Similan', 'Similan Islands', 'Similan Adaları', 'White-sand islands with top diving.', 'Birinci sınıf dalışlı beyaz kumlu adalar.'),
  (1536, '764', 'Satun', 'Satun', 'Koh Lipe', 'Koh Lipe', 'Thailand''s southernmost island paradise.', 'Tayland''ın en güneydeki ada cenneti.'),
  (1537, '704', 'Ho Chi Minh City', 'Ho Chi Minh Şehri', 'War Remnants Museum', 'Savaş Kalıntıları Müzesi', 'A museum on the Vietnam War.', 'Vietnam Savaşı müzesi.'),
  (1538, '704', 'Ho Chi Minh City', 'Ho Chi Minh Şehri', 'Cu Chi Tunnels', 'Cu Chi Tünelleri', 'A network of wartime tunnels.', 'Savaş dönemi tünel ağı.'),
  (1539, '704', 'Ho Chi Minh City', 'Ho Chi Minh Şehri', 'Saigon Notre-Dame Basilica', 'Saygon Notre-Dame Bazilikası', 'A red-brick French colonial cathedral.', 'Kırmızı tuğlalı Fransız sömürge katedrali.'),
  (1540, '704', 'Hue', 'Hue', 'Hue Imperial City', 'Hue İmparatorluk Şehri', 'The Nguyen dynasty''s citadel.', 'Nguyen hanedanının kalesi.'),
  (1541, '704', 'Phong Nha', 'Phong Nha', 'Phong Nha Caves', 'Phong Nha Mağaraları', 'Vast caves including Son Doong.', 'Son Doong dahil devasa mağaralar.'),
  (1542, '704', 'Mekong Delta', 'Mekong Deltası', 'Mekong Delta', 'Mekong Deltası', 'Floating markets and canals.', 'Yüzen pazarlar ve kanallar.'),
  (1543, '704', 'Mui Ne', 'Mui Ne', 'Mui Ne Sand Dunes', 'Mui Ne Kum Tepeleri', 'Red and white desert-like dunes.', 'Kırmızı ve beyaz çöl benzeri kumullar.'),
  (1544, '704', 'Da Lat', 'Da Lat', 'Da Lat', 'Da Lat', 'A cool highland city of lakes and pine.', 'Göller ve çamlarla serin yayla şehri.'),
  (1545, '704', 'Nha Trang', 'Nha Trang', 'Nha Trang Beach', 'Nha Trang Plajı', 'A beach city with island boat trips.', 'Ada tekne turlu plaj şehri.'),
  (1546, '704', 'Phu Quoc', 'Phu Quoc', 'Phu Quoc Island', 'Phu Quoc Adası', 'Beaches and sunset pearl farms.', 'Plajlar ve gün batımı inci çiftlikleri.'),
  (1547, '704', 'Cat Ba', 'Cat Ba', 'Cat Ba Island', 'Cat Ba Adası', 'Karst islands near Ha Long Bay.', 'Ha Long Körfezi yakınında karst adaları.'),
  (1548, '704', 'Hanoi', 'Hanoi', 'Temple of Literature', 'Edebiyat Tapınağı', 'Vietnam''s first university.', 'Vietnam''ın ilk üniversitesi.'),
  (1549, '704', 'Hanoi', 'Hanoi', 'Hanoi Train Street', 'Hanoi Tren Sokağı', 'A railway through narrow houses.', 'Dar evler arasından geçen demiryolu.'),
  (1550, '704', 'Ha Giang', 'Ha Giang', 'Ha Giang Loop', 'Ha Giang Döngüsü', 'A mountain motorbike loop.', 'Dağlarda motosiklet rotası.'),
  (1551, '704', 'Da Nang', 'Da Nang', 'Marble Mountains', 'Mermer Dağlar', 'Cave temples in marble hills.', 'Mermer tepelerde mağara tapınakları.'),
  (1552, '116', 'Siem Reap', 'Siem Reap', 'Angkor Thom', 'Angkor Thom', 'A walled city of giant gates.', 'Dev kapılı surlu şehir.'),
  (1553, '116', 'Siem Reap', 'Siem Reap', 'Banteay Srei', 'Banteay Srei', 'A pink sandstone temple of fine carving.', 'İnce oymalı pembe kumtaşı tapınak.'),
  (1554, '116', 'Siem Reap', 'Siem Reap', 'Tonle Sap Floating Villages', 'Tonle Sap Yüzen Köyleri', 'Villages on stilts and boats.', 'Kazık ve teknelerde köyler.'),
  (1555, '116', 'Kampot', 'Kampot', 'Bokor Hill Station', 'Bokor Dağ İstasyonu', 'A ghostly colonial hill station.', 'Hayalet gibi sömürge dağ istasyonu.'),
  (1556, '116', 'Koh Rong', 'Koh Rong', 'Koh Rong Island', 'Koh Rong Adası', 'White-sand beaches and glowing plankton.', 'Beyaz kumsallar ve parlayan planktonlar.'),
  (1557, '116', 'Preah Vihear', 'Preah Vihear', 'Preah Vihear Temple', 'Preah Vihear Tapınağı', 'A cliff-edge Khmer temple.', 'Uçurum kenarında Khmer tapınağı.'),
  (1558, '116', 'Phnom Penh', 'Phnom Penh', 'Tuol Sleng Genocide Museum', 'Tuol Sleng Soykırım Müzesi', 'A memorial of the Khmer Rouge era.', 'Kızıl Kmerler dönemi anıtı.'),
  (1559, '116', 'Phnom Penh', 'Phnom Penh', 'Central Market, Phnom Penh', 'Merkez Pazarı, Phnom Penh', 'A domed Art Deco market.', 'Kubbeli Art Deco pazar.'),
  (1560, '360', 'Jakarta', 'Cakarta', 'National Monument (Monas)', 'Ulusal Anıt (Monas)', 'A tall obelisk with a golden flame.', 'Altın alevli yüksek dikilitaş.'),
  (1561, '360', 'Bali', 'Bali', 'Tanah Lot', 'Tanah Lot', 'A sea temple on a rock.', 'Kayanın üzerinde deniz tapınağı.'),
  (1562, '360', 'Bali', 'Bali', 'Besakih Temple', 'Besakih Tapınağı', 'Bali''s largest ''Mother Temple''.', 'Bali''nin en büyük ''Ana Tapınağı''.'),
  (1563, '360', 'Ubud', 'Ubud', 'Sacred Monkey Forest', 'Kutsal Maymun Ormanı', 'A forest sanctuary with temples and monkeys.', 'Tapınaklar ve maymunlarla orman sığınağı.'),
  (1564, '360', 'Nusa Penida', 'Nusa Penida', 'Kelingking Beach', 'Kelingking Plajı', 'A T-rex-shaped cliff above blue sea.', 'Mavi denizin üzerinde T-rex biçimli kayalık.'),
  (1565, '360', 'Bali', 'Bali', 'Mount Batur Sunrise', 'Batur Yanardağı Gün Doğumu', 'A volcano trek at dawn.', 'Şafakta yanardağ yürüyüşü.'),
  (1566, '360', 'Gili Islands', 'Gili Adaları', 'Gili Islands', 'Gili Adaları', 'Car-free islands and turtles.', 'Araçsız adalar ve kaplumbağalar.'),
  (1567, '360', 'Lombok', 'Lombok', 'Mount Rinjani', 'Rinjani Dağı', 'A volcano with a crater lake.', 'Krater gölü olan yanardağ.'),
  (1568, '360', 'Raja Ampat', 'Raja Ampat', 'Raja Ampat', 'Raja Ampat', 'The world''s richest marine biodiversity.', 'Dünyanın en zengin deniz biyoçeşitliliği.'),
  (1569, '360', 'Toraja', 'Toraja', 'Tana Toraja', 'Tana Toraja', 'Boat-shaped houses and cliff graves.', 'Tekne biçimli evler ve uçurum mezarları.'),
  (1570, '360', 'Lake Toba', 'Toba Gölü', 'Lake Toba', 'Toba Gölü', 'The world''s largest volcanic lake.', 'Dünyanın en büyük volkanik gölü.'),
  (1571, '360', 'East Java', 'Doğu Java', 'Ijen Blue Fire', 'Ijen Mavi Ateşi', 'Electric-blue sulfur flames at night.', 'Geceleri elektrik mavisi kükürt alevleri.'),
  (1572, '360', 'Malang', 'Malang', 'Tumpak Sewu Waterfall', 'Tumpak Sewu Şelalesi', 'A thousand-stream curtain waterfall.', 'Bin akıntılı perde şelale.'),
  (1573, '360', 'Flores', 'Flores', 'Kelimutu Crater Lakes', 'Kelimutu Krater Gölleri', 'Three lakes that change color.', 'Renk değiştiren üç göl.'),
  (1574, '360', 'Komodo', 'Komodo', 'Padar Island', 'Padar Adası', 'A viewpoint over three-colored beaches.', 'Üç renkli plaj manzaralı seyir noktası.'),
  (1575, '360', 'Yogyakarta', 'Yogyakarta', 'Taman Sari Water Castle', 'Taman Sari Su Sarayı', 'A royal bathing complex.', 'Kraliyet banyo kompleksi.'),
  (1576, '458', 'Kuala Lumpur', 'Kuala Lumpur', 'KL Tower', 'KL Kulesi', 'A telecommunications tower with a sky deck.', 'Seyir terasıyla telekomünikasyon kulesi.'),
  (1577, '458', 'Kuala Lumpur', 'Kuala Lumpur', 'Merdeka Square', 'Merdeka Meydanı', 'Where independence was declared.', 'Bağımsızlığın ilan edildiği yer.'),
  (1578, '458', 'Malacca', 'Malaka', 'A Famosa', 'A Famosa', 'A Portuguese fort gate in Malacca.', 'Malaka''da Portekiz kale kapısı.'),
  (1579, '458', 'Cameron Highlands', 'Cameron Highlands', 'Cameron Highlands Tea Plantations', 'Cameron Highlands Çay Plantasyonları', 'Cool hills of tea and strawberries.', 'Çay ve çilekle serin tepeler.'),
  (1580, '458', 'Sabah', 'Sabah', 'Mount Kinabalu', 'Kinabalu Dağı', 'Southeast Asia''s highest peak.', 'Güneydoğu Asya''nın en yüksek zirvesi.'),
  (1581, '458', 'Sabah', 'Sabah', 'Sipadan Island', 'Sipadan Adası', 'One of the world''s best dive sites.', 'Dünyanın en iyi dalış noktalarından biri.'),
  (1582, '458', 'Sarawak', 'Sarawak', 'Gunung Mulu Caves', 'Gunung Mulu Mağaraları', 'Giant caves and bat flights.', 'Dev mağaralar ve yarasa uçuşları.'),
  (1583, '458', 'Taman Negara', 'Taman Negara', 'Taman Negara', 'Taman Negara', 'One of the world''s oldest rainforests.', 'Dünyanın en eski yağmur ormanlarından biri.'),
  (1584, '458', 'Putrajaya', 'Putrajaya', 'Putra Mosque', 'Putra Camii', 'A pink-domed mosque on a lake.', 'Gölde pembe kubbeli cami.'),
  (1585, '458', 'Penang', 'Penang', 'Kek Lok Si Temple', 'Kek Lok Si Tapınağı', 'A giant hillside Buddhist temple.', 'Yamaçta dev Budist tapınağı.'),
  (1586, '458', 'Sabah', 'Sabah', 'Sepilok Orangutan Sanctuary', 'Sepilok Orangutan Sığınağı', 'A rehabilitation centre for orangutans.', 'Orangutanlar için rehabilitasyon merkezi.'),
  (1587, '702', 'Singapore', 'Singapur', 'Raffles Hotel', 'Raffles Hotel', 'The colonial hotel of the Singapore Sling.', 'Singapore Sling''in sömürge oteli.'),
  (1588, '702', 'Singapore', 'Singapur', 'Chinatown Singapore', 'Singapur Çin Mahallesi', 'Temples, hawker food and shophouses.', 'Tapınaklar, sokak yemekleri ve dükkân evleri.'),
  (1589, '702', 'Singapore', 'Singapur', 'Night Safari', 'Gece Safarisi', 'The world''s first nocturnal zoo.', 'Dünyanın ilk gece hayvanat bahçesi.'),
  (1590, '702', 'Singapore', 'Singapur', 'Jewel Changi Airport', 'Jewel Changi Havalimanı', 'An indoor waterfall in an airport.', 'Havalimanında kapalı şelale.'),
  (1591, '702', 'Singapore', 'Singapur', 'Clarke Quay', 'Clarke Quay', 'A riverside nightlife district.', 'Nehir kıyısında gece hayatı bölgesi.'),
  (1592, '702', 'Singapore', 'Singapur', 'Singapore Botanic Gardens', 'Singapur Botanik Bahçesi', 'A UNESCO tropical garden.', 'UNESCO tropikal bahçe.'),
  (1593, '702', 'Singapore', 'Singapur', 'Universal Studios Singapore', 'Universal Studios Singapur', 'A theme park on Sentosa.', 'Sentosa''da tema parkı.'),
  (1594, '608', 'Manila', 'Manila', 'Intramuros', 'Intramuros', 'The Spanish colonial walled city.', 'İspanyol sömürge surlu şehri.'),
  (1595, '608', 'Banaue', 'Banaue', 'Banaue Rice Terraces', 'Banaue Pirinç Terasları', '2,000-year-old terraces.', '2000 yıllık teraslar.'),
  (1596, '608', 'Albay', 'Albay', 'Mayon Volcano', 'Mayon Yanardağı', 'A near-perfect cone volcano.', 'Neredeyse kusursuz konik yanardağ.'),
  (1597, '608', 'Palawan', 'Palawan', 'Puerto Princesa Underground River', 'Puerto Princesa Yeraltı Nehri', 'A navigable river inside a cave.', 'Mağara içinde seyredilebilir nehir.'),
  (1598, '608', 'Coron', 'Coron', 'Coron', 'Coron', 'Lagoons, lakes and shipwreck diving.', 'Lagünler, göller ve gemi enkazı dalışı.'),
  (1599, '608', 'Siargao', 'Siargao', 'Siargao Cloud 9', 'Siargao Cloud 9', 'A surfing paradise island.', 'Sörf cenneti ada.'),
  (1600, '608', 'Vigan', 'Vigan', 'Vigan Heritage Village', 'Vigan Miras Köyü', 'A Spanish colonial town of cobblestones.', 'Arnavut kaldırımlı İspanyol sömürge kasabası.'),
  (1601, '608', 'Donsol', 'Donsol', 'Donsol Whale Sharks', 'Donsol Balina Köpekbalıkları', 'Swim with whale sharks.', 'Balina köpekbalıklarıyla yüzün.'),
  (1602, '608', 'Camiguin', 'Camiguin', 'Camiguin Island', 'Camiguin Adası', 'Volcanoes, springs and a sunken cemetery.', 'Yanardağlar, kaynaklar ve batık mezarlık.'),
  (1603, '096', 'Bandar Seri Begawan', 'Bandar Seri Begawan', 'Sultan Omar Ali Saifuddien Mosque', 'Sultan Ömer Ali Seyfeddin Camii', 'A golden-domed mosque on a lagoon.', 'Lagün üzerinde altın kubbeli cami.'),
  (1604, '096', 'Bandar Seri Begawan', 'Bandar Seri Begawan', 'Kampong Ayer', 'Kampong Ayer', 'The world''s largest water village.', 'Dünyanın en büyük su köyü.'),
  (1605, '626', 'Dili', 'Dili', 'Cristo Rei of Dili', 'Dili Cristo Rei', 'A giant Christ statue over the bay.', 'Körfeze bakan dev İsa heykeli.'),
  (1606, '626', 'Atauro', 'Atauro', 'Atauro Island', 'Atauro Adası', 'A diving island of reefs.', 'Resifleriyle dalış adası.'),
  (1607, '408', 'Pyongyang', 'Pyongyang', 'Arch of Triumph, Pyongyang', 'Zafer Takı, Pyongyang', 'A giant triumphal arch.', 'Dev zafer takı.'),
  (1608, '408', 'Pyongyang', 'Pyongyang', 'Juche Tower', 'Juche Kulesi', 'A granite tower on the Taedong River.', 'Taedong Nehri''nde granit kule.'),
  (1609, '344', 'Hong Kong', 'Hong Kong', 'Hong Kong Disneyland', 'Hong Kong Disneyland', 'A Disney park on Lantau.', 'Lantau''da Disney parkı.'),
  (1610, '344', 'Hong Kong', 'Hong Kong', 'Symphony of Lights', 'Işıkların Senfonisi', 'A nightly light show over the harbour.', 'Limanda her gece ışık gösterisi.'),
  (1611, '446', 'Macau', 'Makao', 'The Venetian Macao', 'The Venetian Macao', 'A Venice-themed mega resort.', 'Venedik temalı dev resort.'),
  (1612, '446', 'Macau', 'Makao', 'Macau Tower', 'Makao Kulesi', 'A tower with the world''s highest bungee jump.', 'Dünyanın en yüksek bungee atlayışı kulesi.'),
  (1613, '398', 'Astana', 'Astana', 'Bayterek Tower', 'Baiterek Kulesi', 'A monument tower with a golden orb.', 'Altın küreli anıt kule.'),
  (1614, '398', 'Astana', 'Astana', 'Khan Shatyr', 'Han Şatır', 'A giant translucent tent mall.', 'Dev şeffaf çadır alışveriş merkezi.'),
  (1615, '398', 'Kolsai', 'Kolsai', 'Kolsai Lakes', 'Kolsay Gölleri', 'Three alpine lakes.', 'Üç dağ gölü.'),
  (1616, '398', 'Turkistan', 'Türkistan', 'Mausoleum of Khoja Ahmed Yasawi', 'Hoca Ahmed Yesevi Türbesi', 'A grand Timurid mausoleum.', 'Görkemli Timurlu türbesi.'),
  (1617, '398', 'Almaty', 'Almatı', 'Altyn-Emel Singing Dune', 'Altın Emel Şarkı Söyleyen Kumul', 'A dune that hums in the wind.', 'Rüzgârda uğuldayan kumul.'),
  (1618, '860', 'Samarkand', 'Semerkant', 'Shah-i-Zinda', 'Şahi Zinde', 'An avenue of blue-tiled mausoleums.', 'Mavi çinili türbeler caddesi.'),
  (1619, '860', 'Samarkand', 'Semerkant', 'Gur-e-Amir', 'Gur-ı Emir', 'Timur''s tomb under a ribbed dome.', 'Nervürlü kubbe altında Timur''un türbesi.'),
  (1620, '860', 'Bukhara', 'Buhara', 'Kalyan Minaret', 'Kalyan Minaresi', 'The tower of death in Bukhara.', 'Buhara''nın ölüm kulesi.'),
  (1621, '860', 'Bukhara', 'Buhara', 'Ark of Bukhara', 'Buhara Ark Kalesi', 'A massive fortress citadel.', 'Devasa kale.'),
  (1622, '860', 'Tashkent', 'Taşkent', 'Tashkent Metro', 'Taşkent Metrosu', 'Palace-like Soviet stations.', 'Saray gibi Sovyet istasyonları.'),
  (1623, '860', 'Samarkand', 'Semerkant', 'Bibi-Khanym Mosque', 'Bibi Hanım Camii', 'A vast Timurid mosque.', 'Geniş Timurlu camii.'),
  (1624, '417', 'Naryn', 'Naryn', 'Song-Kol Lake', 'Song-Köl Gölü', 'A high alpine lake with yurt camps.', 'Yurt kamplarıyla yüksek dağ gölü.'),
  (1625, '417', 'Bishkek', 'Bişkek', 'Ala Archa National Park', 'Ala Archa Milli Parkı', 'Glaciers near the capital.', 'Başkente yakın buzullar.'),
  (1626, '417', 'Chuy', 'Çuy', 'Burana Tower', 'Burana Kulesi', 'An ancient minaret on the Silk Road.', 'İpek Yolu''nda antik minare.'),
  (1627, '417', 'Osh', 'Oş', 'Sulaiman-Too', 'Süleyman Dağı', 'A sacred mountain in the city.', 'Şehirde kutsal dağ.'),
  (1628, '795', 'Ashgabat', 'Aşkabat', 'Ashgabat White Marble City', 'Aşkabat Beyaz Mermer Şehri', 'The world''s most marble-clad capital.', 'Dünyanın en çok mermer kaplı başkenti.'),
  (1629, '795', 'Mary', 'Mary', 'Merv Ancient City', 'Merv Antik Şehri', 'A great Silk Road city.', 'Büyük İpek Yolu şehri.'),
  (1630, '795', 'Ashgabat', 'Aşkabat', 'Nisa Fortress', 'Nisa Kalesi', 'A Parthian royal citadel.', 'Part kraliyet kalesi.'),
  (1631, '762', 'Fann Mountains', 'Fan Dağları', 'Iskanderkul Lake', 'İskenderkul Gölü', 'A mountain lake linked to Alexander.', 'İskender''le anılan dağ gölü.'),
  (1632, '762', 'Dushanbe', 'Duşanbe', 'Navruz Palace', 'Navruz Sarayı', 'A grand teahouse-palace.', 'Görkemli çayhane-saray.'),
  (1633, '496', 'Terelj', 'Terelj', 'Gorkhi-Terelj National Park', 'Gorkhi-Terelj Milli Parkı', 'Granite rocks and ger camps.', 'Granit kayalar ve ger kampları.'),
  (1634, '496', 'Kharkhorin', 'Karakurum', 'Erdene Zuu Monastery', 'Erdene Zuu Manastırı', 'Mongolia''s oldest Buddhist monastery.', 'Moğolistan''ın en eski Budist manastırı.'),
  (1635, '496', 'Khuvsgul', 'Hövsgöl', 'Lake Khuvsgul', 'Hövsgöl Gölü', 'The ''Blue Pearl'' of Mongolia.', 'Moğolistan''ın ''Mavi İncisi''.'),
  (1636, '496', 'Ulaanbaatar', 'Ulan Batur', 'Naadam Festival', 'Naadam Festivali', 'Wrestling, archery and horse racing.', 'Güreş, okçuluk ve at yarışı.'),
  (1637, '004', 'Bamyan', 'Bamiyan', 'Bamiyan Buddha Niches', 'Bamiyan Buda Nişleri', 'The giant niches of the destroyed Buddhas.', 'Yıkılan Buda heykellerinin dev nişleri.'),
  (1638, '004', 'Ghor', 'Gur', 'Minaret of Jam', 'Cam Minaresi', 'A 12th-century brick minaret in a gorge.', 'Vadide 12. yüzyıl tuğla minare.'),
  (1639, '004', 'Mazar-i-Sharif', 'Mezar-ı Şerif', 'Blue Mosque of Mazar-i-Sharif', 'Mezar-ı Şerif Mavi Camii', 'A tiled shrine of blue mosaics.', 'Mavi mozaikli çinili türbe.'),
  (1640, '036', 'Sydney', 'Sidney', 'Sydney Harbour Bridge', 'Sidney Liman Köprüsü', 'The iconic steel arch bridge.', 'İkonik çelik kemer köprü.'),
  (1641, '036', 'Blue Mountains', 'Blue Mountains', 'Three Sisters', 'Üç Kız Kardeş', 'Sandstone peaks in the Blue Mountains.', 'Mavi Dağlar''da kumtaşı zirveler.'),
  (1642, '036', 'Sydney', 'Sidney', 'The Rocks', 'The Rocks', 'Sydney''s oldest district.', 'Sidney''in en eski bölgesi.'),
  (1643, '036', 'Sydney', 'Sidney', 'Taronga Zoo', 'Taronga Hayvanat Bahçesi', 'A zoo with harbour views.', 'Liman manzaralı hayvanat bahçesi.'),
  (1644, '036', 'Sydney', 'Sidney', 'Manly Beach', 'Manly Plajı', 'A ferry ride to a surf beach.', 'Feribotla gidilen sörf plajı.'),
  (1645, '036', 'Melbourne', 'Melbourne', 'Federation Square', 'Federation Square', 'Melbourne''s cultural heart.', 'Melbourne''un kültürel kalbi.'),
  (1646, '036', 'Melbourne', 'Melbourne', 'Queen Victoria Market', 'Queen Victoria Pazarı', 'A historic open-air market.', 'Tarihi açık hava pazarı.'),
  (1647, '036', 'Phillip Island', 'Phillip Island', 'Phillip Island Penguin Parade', 'Phillip Island Penguen Geçidi', 'Little penguins waddle ashore at dusk.', 'Alacakaranlıkta küçük penguenler kıyıya yürür.'),
  (1648, '036', 'Gold Coast', 'Gold Coast', 'Gold Coast Surfers Paradise', 'Gold Coast Surfers Paradise', 'Surf beaches and skyscrapers.', 'Sörf plajları ve gökdelenler.'),
  (1649, '036', 'Cairns', 'Cairns', 'Daintree Rainforest', 'Daintree Yağmur Ormanı', 'The world''s oldest tropical rainforest.', 'Dünyanın en eski tropikal yağmur ormanı.'),
  (1650, '036', 'Whitsundays', 'Whitsundays', 'Whitehaven Beach', 'Whitehaven Plajı', 'Silica-white sand and swirling tides.', 'Silika beyazı kum ve girdaplı gelgitler.'),
  (1651, '036', 'Kakadu', 'Kakadu', 'Kakadu National Park', 'Kakadu Milli Parkı', 'Wetlands and Aboriginal rock art.', 'Sulak alanlar ve Aborijin kaya sanatı.'),
  (1652, '036', 'Perth', 'Perth', 'Kings Park', 'Kings Park', 'A huge park with city views.', 'Şehir manzaralı dev park.'),
  (1653, '036', 'Rottnest Island', 'Rottnest Adası', 'Rottnest Island Quokkas', 'Rottnest Adası Quokkaları', 'Meet the smiling quokkas.', 'Gülümseyen quokkalarla tanışın.'),
  (1654, '036', 'Exmouth', 'Exmouth', 'Ningaloo Reef', 'Ningaloo Resifi', 'Swim with whale sharks.', 'Balina köpekbalıklarıyla yüzün.'),
  (1655, '036', 'Kangaroo Island', 'Kangaroo Island', 'Kangaroo Island', 'Kangaroo Island', 'Wildlife, sea lions and rugged coast.', 'Vahşi yaşam, deniz aslanları ve sarp kıyı.'),
  (1656, '036', 'Kimberley', 'Kimberley', 'Bungle Bungle Range', 'Bungle Bungle Dağları', 'Orange-striped beehive domes.', 'Turuncu çizgili arı kovanı kubbeler.'),
  (1657, '036', 'Hyden', 'Hyden', 'Wave Rock', 'Dalga Kayası', 'A granite cliff shaped like a wave.', 'Dalga biçimli granit kayalık.'),
  (1658, '036', 'Fraser Island', 'Fraser Adası', 'K''gari (Fraser Island)', 'K''gari (Fraser Adası)', 'The world''s largest sand island.', 'Dünyanın en büyük kum adası.'),
  (1659, '036', 'Canberra', 'Canberra', 'Parliament House Canberra', 'Canberra Parlamento Binası', 'A grass-roofed parliament.', 'Çim çatılı parlamento.'),
  (1660, '036', 'Hobart', 'Hobart', 'MONA Museum', 'MONA Müzesi', 'An edgy underground art museum.', 'Cesur yeraltı sanat müzesi.'),
  (1661, '036', 'Tasmania', 'Tazmanya', 'Wineglass Bay', 'Wineglass Koyu', 'A perfect crescent bay.', 'Kusursuz hilal koy.'),
  (1662, '036', 'Broome', 'Broome', 'Cable Beach', 'Cable Beach', 'Camel rides at sunset.', 'Gün batımında deve gezisi.'),
  (1663, '036', 'Uluru', 'Uluru', 'Kata Tjuta', 'Kata Tjuta', 'Domed rocks near Uluru.', 'Uluru yakınında kubbeli kayalar.'),
  (1664, '036', 'Karijini', 'Karijini', 'Karijini National Park', 'Karijini Milli Parkı', 'Red gorges and swimming holes.', 'Kırmızı vadiler ve yüzme havuzları.'),
  (1665, '554', 'Auckland', 'Auckland', 'Sky Tower', 'Sky Tower', 'The Southern Hemisphere''s tallest tower.', 'Güney Yarımküre''nin en yüksek kulesi.'),
  (1666, '554', 'Waitomo', 'Waitomo', 'Waitomo Glowworm Caves', 'Waitomo Parıldayan Böcek Mağaraları', 'A cave ceiling of glowing worms.', 'Parlayan solucanlarla dolu mağara tavanı.'),
  (1667, '554', 'Franz Josef', 'Franz Josef', 'Franz Josef Glacier', 'Franz Josef Buzulu', 'A glacier near the rainforest.', 'Yağmur ormanı yakınında buzul.'),
  (1668, '554', 'Aoraki', 'Aoraki', 'Aoraki / Mount Cook', 'Aoraki / Cook Dağı', 'New Zealand''s highest peak.', 'Yeni Zelanda''nın en yüksek zirvesi.'),
  (1669, '554', 'Abel Tasman', 'Abel Tasman', 'Abel Tasman National Park', 'Abel Tasman Milli Parkı', 'Golden beaches and kayaking.', 'Altın plajlar ve kano.'),
  (1670, '554', 'Bay of Islands', 'Bay of Islands', 'Bay of Islands', 'Bay of Islands', 'A subtropical bay of 144 islands.', '144 adalı subtropikal körfez.'),
  (1671, '554', 'Wellington', 'Wellington', 'Te Papa Museum', 'Te Papa Müzesi', 'New Zealand''s national museum.', 'Yeni Zelanda''nın ulusal müzesi.'),
  (1672, '554', 'Kaikoura', 'Kaikoura', 'Kaikoura Whale Watching', 'Kaikoura Balina Gözlemi', 'Sperm whales close to shore.', 'Kıyıya yakın ispermeçet balinaları.'),
  (1673, '554', 'Tekapo', 'Tekapo', 'Lake Tekapo', 'Tekapo Gölü', 'A milky-blue lake under starry skies.', 'Yıldızlı gökyüzü altında sütlü mavi göl.'),
  (1674, '554', 'Rotorua', 'Rotorua', 'Te Puia Geothermal Park', 'Te Puia Jeotermal Parkı', 'Geysers and Maori culture.', 'Gayzerler ve Maori kültürü.'),
  (1675, '554', 'Coromandel', 'Coromandel', 'Cathedral Cove', 'Cathedral Cove', 'A natural arch beach.', 'Doğal kemerli plaj.'),
  (1676, '554', 'Coromandel', 'Coromandel', 'Hot Water Beach', 'Hot Water Beach', 'Dig your own hot pool in the sand.', 'Kumda kendi sıcak havuzunu kaz.'),
  (1677, '554', 'Fiordland', 'Fiordland', 'Doubtful Sound', 'Doubtful Sound', 'A remote, quiet fjord.', 'Uzak ve sessiz fiyort.'),
  (1678, '554', 'Taranaki', 'Taranaki', 'Mount Taranaki', 'Taranaki Dağı', 'A symmetrical volcano.', 'Simetrik yanardağ.'),
  (1679, '242', 'Nadi', 'Nadi', 'Garden of the Sleeping Giant', 'Uyuyan Dev Bahçesi', 'A garden of orchids.', 'Orkide bahçesi.'),
  (1680, '242', 'Yasawa', 'Yasawa', 'Yasawa Islands', 'Yasawa Adaları', 'Remote islands of blue lagoons.', 'Mavi lagünlü uzak adalar.'),
  (1681, '242', 'Taveuni', 'Taveuni', 'Bouma Falls', 'Bouma Şelaleleri', 'Waterfalls in a tropical forest.', 'Tropikal ormanda şelaleler.'),
  (1682, '242', 'Nadi', 'Nadi', 'Sabeto Mud Pool', 'Sabeto Çamur Havuzu', 'Hot mud and thermal pools.', 'Sıcak çamur ve termal havuzlar.'),
  (1683, '882', 'Upolu', 'Upolu', 'To Sua Ocean Trench', 'To Sua Okyanus Çukuru', 'A swimming hole reached by ladder.', 'Merdivenle inilen yüzme çukuru.'),
  (1684, '776', 'Vava''u', 'Vava''u', 'Swimming with Humpback Whales', 'Kambur Balinalarla Yüzme', 'Meet whales in the Tongan sea.', 'Tonga denizinde balinalarla buluşma.'),
  (1685, '548', 'Tanna', 'Tanna', 'Mount Yasur', 'Yasur Yanardağı', 'An accessible active volcano.', 'Yaklaşılabilen aktif yanardağ.'),
  (1686, '090', 'Marovo', 'Marovo', 'Marovo Lagoon', 'Marovo Lagünü', 'The world''s largest double-barrier lagoon.', 'Dünyanın en büyük çift bariyerli lagünü.'),
  (1687, '585', 'Koror', 'Koror', 'Jellyfish Lake', 'Denizanası Gölü', 'Swim with harmless jellyfish.', 'Zararsız denizanalarıyla yüzün.'),
  (1688, '585', 'Koror', 'Koror', 'Rock Islands of Palau', 'Palau Kaya Adaları', 'Mushroom-shaped limestone islets.', 'Mantar biçimli kireçtaşı adacıklar.'),
  (1689, '184', 'Aitutaki', 'Aitutaki', 'Aitutaki Lagoon', 'Aitutaki Lagünü', 'A turquoise lagoon with sand islets.', 'Kum adacıklı turkuaz lagün.'),
  (1690, '540', 'Isle of Pines', 'Isle of Pines', 'Isle of Pines', 'Isle of Pines', 'White beaches and natural pools.', 'Beyaz plajlar ve doğal havuzlar.'),
  (1691, '583', 'Pohnpei', 'Pohnpei', 'Nan Madol', 'Nan Madol', 'A ruined city built on reef islets.', 'Resif adacıklarında kurulmuş yıkık şehir.'),
  (1692, '584', 'Bikini Atoll', 'Bikini Atolü', 'Bikini Atoll', 'Bikini Atolü', 'A nuclear-test atoll turned dive site.', 'Nükleer test atolünden dalış alanına.'),
  (1693, '570', 'Niue', 'Niue', 'Limu Pools', 'Limu Havuzları', 'Snorkel in clear rock pools.', 'Berrak kaya havuzlarında şnorkel.'),
  (1694, '840', 'New York', 'New York', 'Brooklyn Bridge', 'Brooklyn Köprüsü', 'A gothic-arched suspension bridge you can walk across.', 'Yürünebilen Gotik kemerli asma köprü.'),
  (1695, '840', 'New York', 'New York', 'High Line', 'High Line', 'A park built on an old elevated railway.', 'Eski yüksek demiryolu üzerinde park.'),
  (1696, '840', 'New York', 'New York', '9/11 Memorial', '11 Eylül Anıtı', 'Reflecting pools on the Twin Towers'' footprints.', 'İkiz Kuleler''in izlerinde yansıma havuzları.'),
  (1697, '840', 'New York', 'New York', 'Rockefeller Center', 'Rockefeller Center', 'Art Deco plaza with Top of the Rock views.', 'Top of the Rock manzaralı Art Deco plaza.'),
  (1698, '840', 'New York', 'New York', 'Metropolitan Museum of Art', 'Metropolitan Sanat Müzesi', 'One of the world''s greatest art museums.', 'Dünyanın en büyük sanat müzelerinden biri.'),
  (1699, '840', 'New York', 'New York', 'Grand Central Terminal', 'Grand Central Terminal', 'A Beaux-Arts station with a celestial ceiling.', 'Göksel tavanlı Beaux-Arts istasyon.'),
  (1700, '840', 'New York', 'New York', 'Coney Island', 'Coney Island', 'A boardwalk with a historic amusement park.', 'Tarihi lunaparklı sahil yürüyüşü.'),
  (1701, '840', 'Washington, D.C.', 'Washington, D.C.', 'White House', 'Beyaz Saray', 'The home of the US President.', 'ABD Başkanı''nın konutu.'),
  (1702, '840', 'Washington, D.C.', 'Washington, D.C.', 'US Capitol', 'ABD Kongre Binası', 'The domed seat of Congress.', 'Kongre''nin kubbeli merkezi.'),
  (1703, '840', 'Washington, D.C.', 'Washington, D.C.', 'Washington Monument', 'Washington Anıtı', 'An obelisk at the National Mall.', 'National Mall''da dikilitaş.'),
  (1704, '840', 'Washington, D.C.', 'Washington, D.C.', 'Smithsonian Museums', 'Smithsonian Müzeleri', 'Free museums of air, space and history.', 'Havacılık, uzay ve tarih için ücretsiz müzeler.'),
  (1705, '840', 'Boston', 'Boston', 'Freedom Trail', 'Özgürlük Yolu', 'A red-brick path past Revolution sites.', 'Devrim alanlarından geçen kırmızı tuğla yol.'),
  (1706, '840', 'Chicago', 'Şikago', 'Cloud Gate (The Bean)', 'Cloud Gate (Fasulye)', 'A mirrored sculpture in Millennium Park.', 'Millennium Park''ta aynalı heykel.'),
  (1707, '840', 'Chicago', 'Şikago', 'Willis Tower Skydeck', 'Willis Tower Skydeck', 'A glass ledge 412 metres up.', '412 metrede cam balkon.'),
  (1708, '840', 'San Francisco', 'San Francisco', 'Alcatraz Island', 'Alcatraz Adası', 'The notorious former island prison.', 'Ünlü eski ada hapishanesi.'),
  (1709, '840', 'San Francisco', 'San Francisco', 'Lombard Street', 'Lombard Caddesi', 'The crookedest street in America.', 'Amerika''nın en kıvrımlı sokağı.'),
  (1710, '840', 'Los Angeles', 'Los Angeles', 'Hollywood Sign', 'Hollywood Tabelası', 'The iconic sign on Mount Lee.', 'Lee Dağı''ndaki ikonik tabela.'),
  (1711, '840', 'Los Angeles', 'Los Angeles', 'Griffith Observatory', 'Griffith Gözlemevi', 'An observatory with city and sign views.', 'Şehir ve tabela manzaralı gözlemevi.'),
  (1712, '840', 'Los Angeles', 'Los Angeles', 'Santa Monica Pier', 'Santa Monica İskelesi', 'A pier and Ferris wheel by the Pacific.', 'Pasifik''te iskele ve dönme dolap.'),
  (1713, '840', 'Los Angeles', 'Los Angeles', 'Universal Studios Hollywood', 'Universal Studios Hollywood', 'A film-studio theme park.', 'Film stüdyosu tema parkı.'),
  (1714, '840', 'Seattle', 'Seattle', 'Space Needle', 'Space Needle', 'The 1962 observation tower.', '1962''den kalma gözlem kulesi.'),
  (1715, '840', 'Arizona', 'Arizona', 'Horseshoe Bend', 'Horseshoe Bend', 'A horseshoe-shaped meander of the Colorado River.', 'Colorado Nehri''nin at nalı biçimli kıvrımı.'),
  (1716, '840', 'Arizona', 'Arizona', 'Monument Valley', 'Monument Valley', 'Red sandstone buttes of the Old West.', 'Vahşi Batı''nın kırmızı kumtaşı tepeleri.'),
  (1717, '840', 'Arizona', 'Arizona', 'Sedona Red Rocks', 'Sedona Kırmızı Kayalıkları', 'Red rock formations and vortex sites.', 'Kırmızı kaya oluşumları ve enerji noktaları.'),
  (1718, '840', 'Utah', 'Utah', 'Zion National Park', 'Zion Milli Parkı', 'Canyon hikes like Angels Landing.', 'Angels Landing gibi kanyon yürüyüşleri.'),
  (1719, '840', 'Utah', 'Utah', 'Arches National Park', 'Arches Milli Parkı', 'Natural sandstone arches.', 'Doğal kumtaşı kemerler.'),
  (1720, '840', 'Utah', 'Utah', 'Bryce Canyon', 'Bryce Kanyonu', 'Amphitheatres of orange hoodoos.', 'Turuncu peri bacası amfileri.'),
  (1721, '840', 'Colorado', 'Colorado', 'Rocky Mountain National Park', 'Rocky Mountain Milli Parkı', 'Alpine lakes and elk.', 'Dağ gölleri ve geyikler.'),
  (1722, '840', 'South Dakota', 'Güney Dakota', 'Mount Rushmore', 'Rushmore Dağı', 'Four presidents carved in granite.', 'Granite oyulmuş dört başkan.'),
  (1723, '840', 'Florida', 'Florida', 'Walt Disney World', 'Walt Disney World', 'The world''s most visited theme park resort.', 'Dünyanın en çok ziyaret edilen tema parkı.'),
  (1724, '840', 'Florida', 'Florida', 'Everglades National Park', 'Everglades Milli Parkı', 'A subtropical wetland of alligators.', 'Timsahlı subtropikal sulak alan.'),
  (1725, '840', 'Key West', 'Key West', 'Key West Southernmost Point', 'Key West En Güney Noktası', 'The southernmost point of the contiguous US.', 'ABD anakarasının en güney noktası.'),
  (1726, '840', 'Miami', 'Miami', 'South Beach', 'South Beach', 'Art Deco buildings and white sand.', 'Art Deco binalar ve beyaz kum.'),
  (1727, '840', 'New Orleans', 'New Orleans', 'French Quarter', 'Fransız Mahallesi', 'Jazz, balconies and Creole food.', 'Caz, balkonlar ve Kreol yemekleri.'),
  (1728, '840', 'Nashville', 'Nashville', 'Broadway Honky Tonks', 'Broadway Honky Tonks', 'Live country music every night.', 'Her gece canlı country müzik.'),
  (1729, '840', 'Memphis', 'Memphis', 'Graceland', 'Graceland', 'The home of Elvis Presley.', 'Elvis Presley''in evi.'),
  (1730, '840', 'San Antonio', 'San Antonio', 'The Alamo', 'Alamo', 'A historic Texas mission.', 'Tarihi Teksas misyonu.'),
  (1731, '840', 'Hawaii', 'Hawaii', 'Haleakala Crater', 'Haleakalā Krateri', 'A volcano summit sunrise.', 'Yanardağ zirvesinde gün doğumu.'),
  (1732, '840', 'Hawaii', 'Hawaii', 'Pearl Harbor', 'Pearl Harbor', 'The WWII memorial and USS Arizona.', 'İkinci Dünya Savaşı anıtı ve USS Arizona.'),
  (1733, '840', 'Hawaii', 'Hawaii', 'Hawaii Volcanoes National Park', 'Hawaii Volkanları Milli Parkı', 'A glowing Kilauea crater.', 'Parlayan Kilauea krateri.'),
  (1734, '840', 'Kauai', 'Kauai', 'Na Pali Coast', 'Na Pali Kıyısı', 'Jagged green sea cliffs.', 'Sivri yeşil deniz kayalıkları.'),
  (1735, '840', 'Alaska', 'Alaska', 'Denali National Park', 'Denali Milli Parkı', 'North America''s tallest peak.', 'Kuzey Amerika''nın en yüksek zirvesi.'),
  (1736, '840', 'Montana', 'Montana', 'Glacier National Park', 'Glacier Milli Parkı', 'Alpine lakes and Going-to-the-Sun Road.', 'Dağ gölleri ve Going-to-the-Sun Yolu.'),
  (1737, '840', 'Maine', 'Maine', 'Acadia National Park', 'Acadia Milli Parkı', 'Rocky coast and fall foliage.', 'Kayalık sahil ve sonbahar yaprakları.'),
  (1738, '840', 'Wyoming', 'Wyoming', 'Grand Teton National Park', 'Grand Teton Milli Parkı', 'Jagged peaks over mirror lakes.', 'Ayna göller üzerinde sivri zirveler.'),
  (1739, '840', 'Philadelphia', 'Philadelphia', 'Liberty Bell', 'Özgürlük Çanı', 'A symbol of American independence.', 'Amerikan bağımsızlığının sembolü.'),
  (1740, '840', 'Florida', 'Florida', 'Kennedy Space Center', 'Kennedy Uzay Merkezi', 'NASA''s launch site.', 'NASA''nın fırlatma üssü.'),
  (1741, '840', 'California', 'Kaliforniya', 'Redwood National Park', 'Redwood Milli Parkı', 'The world''s tallest trees.', 'Dünyanın en uzun ağaçları.'),
  (1742, '840', 'California', 'Kaliforniya', 'Death Valley', 'Ölüm Vadisi', 'The hottest, lowest place in North America.', 'Kuzey Amerika''nın en sıcak ve en alçak yeri.'),
  (1743, '840', 'California', 'Kaliforniya', 'Lake Tahoe', 'Tahoe Gölü', 'A crystal-clear alpine lake.', 'Berrak dağ gölü.'),
  (1744, '840', 'California', 'Kaliforniya', 'Big Sur', 'Big Sur', 'Cliffside Highway 1 and Bixby Bridge.', 'Uçurum kenarında Highway 1 ve Bixby Köprüsü.'),
  (1745, '840', 'California', 'Kaliforniya', 'Napa Valley', 'Napa Vadisi', 'California wine country.', 'Kaliforniya şarap bölgesi.'),
  (1746, '840', 'California', 'Kaliforniya', 'Joshua Tree National Park', 'Joshua Tree Milli Parkı', 'Desert boulders and spiky trees.', 'Çöl kayaları ve dikenli ağaçlar.'),
  (1747, '840', 'Oregon', 'Oregon', 'Crater Lake', 'Crater Gölü', 'The deepest lake in the US.', 'ABD''nin en derin gölü.'),
  (1748, '840', 'Nevada', 'Nevada', 'Hoover Dam', 'Hoover Barajı', 'A 1930s art-deco dam on the Colorado.', 'Colorado''da 1930''lardan Art Deco baraj.'),
  (1749, '840', 'Washington', 'Washington', 'Mount Rainier', 'Rainier Dağı', 'A glaciated volcano near Seattle.', 'Seattle yakınında buzullu yanardağ.'),
  (1750, '840', 'Utah', 'Utah', 'Salt Lake Temple', 'Salt Lake Tapınağı', 'The centre of the Latter-day Saints.', 'Mormonların merkez tapınağı.'),
  (1751, '840', 'Tennessee', 'Tennessee', 'Great Smoky Mountains', 'Great Smoky Dağları', 'Misty ridges and black bears.', 'Sisli sırtlar ve kara ayılar.'),
  (1752, '840', 'South Dakota', 'Güney Dakota', 'Badlands National Park', 'Badlands Milli Parkı', 'Eroded buttes and fossils.', 'Aşınmış tepeler ve fosiller.'),
  (1753, '124', 'Vancouver', 'Vancouver', 'Stanley Park', 'Stanley Park', 'A seawall park by downtown.', 'Şehir merkezinde deniz duvarı parkı.'),
  (1754, '124', 'Whistler', 'Whistler', 'Whistler Blackcomb', 'Whistler Blackcomb', 'A top North American ski resort.', 'Kuzey Amerika''nın önde gelen kayak merkezi.'),
  (1755, '124', 'Victoria', 'Victoria', 'Butchart Gardens', 'Butchart Bahçeleri', 'A show garden in a former quarry.', 'Eski taş ocağında gösteri bahçesi.'),
  (1756, '124', 'Jasper', 'Jasper', 'Athabasca Glacier', 'Athabasca Buzulu', 'A glacier you can walk on.', 'Üzerinde yürünebilen buzul.'),
  (1757, '124', 'Banff', 'Banff', 'Moraine Lake', 'Moraine Gölü', 'A turquoise lake under ten peaks.', 'On zirvenin altında turkuaz göl.'),
  (1758, '124', 'Montreal', 'Montreal', 'Notre-Dame Basilica of Montreal', 'Montreal Notre-Dame Bazilikası', 'A starry blue Gothic Revival interior.', 'Yıldızlı mavi Gotik Canlanma iç mekânı.'),
  (1759, '124', 'Montreal', 'Montreal', 'Old Montreal', 'Eski Montreal', 'Cobbled streets and old stone buildings.', 'Arnavut kaldırımlı sokaklar ve eski taş binalar.'),
  (1760, '124', 'Ottawa', 'Ottawa', 'Parliament Hill', 'Parliament Hill', 'Gothic Revival parliament buildings.', 'Gotik Canlanma parlamento binaları.'),
  (1761, '124', 'Ottawa', 'Ottawa', 'Rideau Canal', 'Rideau Kanalı', 'A canal that becomes a skating rink.', 'Buz pistine dönüşen kanal.'),
  (1762, '124', 'Nova Scotia', 'Nova Scotia', 'Peggy''s Cove', 'Peggy''s Cove', 'A lighthouse on granite rocks.', 'Granit kayalıkta deniz feneri.'),
  (1763, '124', 'Nova Scotia', 'Nova Scotia', 'Cabot Trail', 'Cabot Trail', 'A scenic coastal highway.', 'Manzaralı sahil yolu.'),
  (1764, '124', 'Newfoundland', 'Newfoundland', 'Gros Morne National Park', 'Gros Morne Milli Parkı', 'Fjords and exposed earth''s mantle.', 'Fiyortlar ve açığa çıkmış manto.'),
  (1765, '124', 'Prince Edward Island', 'Prince Edward Adası', 'Green Gables Heritage Place', 'Green Gables Miras Alanı', 'The home of Anne of Green Gables.', 'Yeşil Çatılı Anne''nin evi.'),
  (1766, '124', 'Yukon', 'Yukon', 'Dawson City', 'Dawson City', 'A Klondike Gold Rush town.', 'Klondike Altın Hücumu kasabası.'),
  (1767, '124', 'Yellowknife', 'Yellowknife', 'Yellowknife Aurora Viewing', 'Yellowknife Aurora Gözlemi', 'Dark skies for the Northern Lights.', 'Kuzey Işıkları için karanlık gökyüzü.'),
  (1768, '124', 'Calgary', 'Calgary', 'Calgary Stampede', 'Calgary Stampede', 'A rodeo festival every July.', 'Her Temmuz rodeo festivali.'),
  (1769, '124', 'New Brunswick', 'New Brunswick', 'Hopewell Rocks', 'Hopewell Kayaları', 'Flowerpot rocks at the Bay of Fundy.', 'Fundy Körfezi''nde çiçeklik biçimli kayalar.'),
  (1770, '124', 'Ontario', 'Ontario', 'Thousand Islands', 'Binlerce Ada', 'A river of islands and castles.', 'Adalar ve şatolar nehri.'),
  (1771, '124', 'Tofino', 'Tofino', 'Pacific Rim National Park', 'Pacific Rim Milli Parkı', 'Surf beaches and storm watching.', 'Sörf plajları ve fırtına izleme.'),
  (1772, '124', 'Haida Gwaii', 'Haida Gwaii', 'Haida Gwaii', 'Haida Gwaii', 'Misty islands of totem poles.', 'Totem direkli sisli adalar.'),
  (1773, '124', 'Ontario', 'Ontario', 'Algonquin Provincial Park', 'Algonquin Eyalet Parkı', 'Canoe lakes and moose.', 'Kano gölleri ve geyikler.'),
  (1774, '484', 'Mexico City', 'Meksiko', 'Zocalo', 'Zócalo', 'The vast main square of Mexico City.', 'Meksiko''nun geniş ana meydanı.'),
  (1775, '484', 'Mexico City', 'Meksiko', 'Frida Kahlo Museum', 'Frida Kahlo Müzesi', 'The Blue House of Frida Kahlo.', 'Frida Kahlo''nun Mavi Evi.'),
  (1776, '484', 'Mexico City', 'Meksiko', 'Xochimilco', 'Xochimilco', 'Colorful trajinera boats on canals.', 'Kanallarda renkli trajinera tekneleri.'),
  (1777, '484', 'Mexico City', 'Meksiko', 'Chapultepec Castle', 'Chapultepec Şatosu', 'A hilltop castle in a big park.', 'Büyük parkta tepe şatosu.'),
  (1778, '484', 'Oaxaca', 'Oaxaca', 'Monte Alban', 'Monte Albán', 'A hilltop Zapotec capital.', 'Tepede Zapotek başkenti.'),
  (1779, '484', 'Oaxaca', 'Oaxaca', 'Hierve el Agua', 'Hierve el Agua', 'Petrified waterfalls and infinity pools.', 'Taşlaşmış şelaleler ve sonsuzluk havuzları.'),
  (1780, '484', 'Chiapas', 'Chiapas', 'Palenque', 'Palenque', 'A Maya city in the jungle.', 'Ormanda Maya şehri.'),
  (1781, '484', 'Merida', 'Mérida', 'Uxmal', 'Uxmal', 'A Puuc-style Maya city.', 'Puuc tarzı Maya şehri.'),
  (1782, '484', 'Quintana Roo', 'Quintana Roo', 'Coba', 'Cobá', 'A Maya pyramid you can sometimes climb.', 'Bazen tırmanılabilen Maya piramidi.'),
  (1783, '484', 'Tulum', 'Tulum', 'Cenote Dos Ojos', 'Cenote Dos Ojos', 'A cave-cenote for snorkelling.', 'Şnorkel için mağara cenote.'),
  (1784, '484', 'Playa del Carmen', 'Playa del Carmen', 'Playa del Carmen', 'Playa del Carmen', 'A Caribbean beach town.', 'Karayip plaj kasabası.'),
  (1785, '484', 'Cozumel', 'Cozumel', 'Cozumel Reefs', 'Cozumel Resifleri', 'Famous Caribbean diving.', 'Ünlü Karayip dalışı.'),
  (1786, '484', 'Holbox', 'Holbox', 'Holbox Island', 'Holbox Adası', 'A car-free island with whale sharks.', 'Balina köpekbalıklı araçsız ada.'),
  (1787, '484', 'Chihuahua', 'Chihuahua', 'Copper Canyon', 'Copper Kanyonu', 'Canyons larger than the Grand Canyon.', 'Büyük Kanyon''dan büyük kanyonlar.'),
  (1788, '484', 'Puerto Vallarta', 'Puerto Vallarta', 'Puerto Vallarta Malecon', 'Puerto Vallarta Malecón', 'A seafront promenade of sculptures.', 'Heykellerle dolu sahil yürüyüşü.'),
  (1789, '484', 'Los Cabos', 'Los Cabos', 'El Arco de Cabo San Lucas', 'Cabo San Lucas Kemeri', 'A rock arch at land''s end.', 'Karanın sonunda kaya kemer.'),
  (1790, '484', 'San Miguel de Allende', 'San Miguel de Allende', 'San Miguel de Allende', 'San Miguel de Allende', 'A pink-stone colonial town.', 'Pembe taşlı sömürge kasabası.'),
  (1791, '484', 'Puebla', 'Puebla', 'Cholula Great Pyramid', 'Cholula Büyük Piramidi', 'The largest pyramid by volume.', 'Hacim olarak en büyük piramit.'),
  (1792, '484', 'Chiapas', 'Chiapas', 'Sumidero Canyon', 'Sumidero Kanyonu', 'A deep river canyon with crocodiles.', 'Timsahlı derin nehir kanyonu.'),
  (1793, '484', 'Bacalar', 'Bacalar', 'Bacalar Lagoon', 'Bacalar Lagünü', 'The ''Lagoon of Seven Colors''.', '''Yedi Renkli Lagün''.'),
  (1794, '484', 'Jalisco', 'Jalisco', 'Tequila Town', 'Tequila Kasabası', 'Agave fields and distilleries.', 'Agav tarlaları ve damıtımevleri.'),
  (1795, '604', 'Lima', 'Lima', 'Miraflores Malecon', 'Miraflores Malecón', 'Clifftop parks above the Pacific.', 'Pasifik üzerinde uçurum parkları.'),
  (1796, '604', 'Arequipa', 'Arequipa', 'Colca Canyon', 'Colca Kanyonu', 'Condors in one of the deepest canyons.', 'En derin kanyonlardan birinde kondorlar.'),
  (1797, '604', 'Arequipa', 'Arequipa', 'Santa Catalina Monastery', 'Santa Catalina Manastırı', 'A colorful hidden city of nuns.', 'Rahibelerin renkli gizli şehri.'),
  (1798, '604', 'Ica', 'Ica', 'Huacachina Oasis', 'Huacachina Vahası', 'A desert oasis with dune buggies.', 'Kum tepesi arabalı çöl vahası.'),
  (1799, '604', 'Lake Titicaca', 'Titicaca Gölü', 'Taquile Island', 'Taquile Adası', 'A weaving community island.', 'Dokumacı topluluk adası.'),
  (1800, '604', 'Madre de Dios', 'Madre de Dios', 'Manu National Park', 'Manu Milli Parkı', 'Amazon rainforest biodiversity.', 'Amazon yağmur ormanı biyoçeşitliliği.'),
  (1801, '604', 'Cusco', 'Cusco', 'Choquequirao', 'Choquequirao', 'A remote ''sister'' of Machu Picchu.', 'Machu Picchu''nun uzak ''kardeşi''.'),
  (1802, '604', 'Cusco', 'Cusco', 'Ollantaytambo', 'Ollantaytambo', 'A living Inca town and fortress.', 'Yaşayan İnka kasabası ve kalesi.'),
  (1803, '604', 'Chachapoyas', 'Chachapoyas', 'Kuelap Fortress', 'Kuelap Kalesi', 'A cloud-forest fortress.', 'Bulut ormanında kale.'),
  (1804, '604', 'Paracas', 'Paracas', 'Ballestas Islands', 'Ballestas Adaları', 'Sea lions and penguins on rocky islands.', 'Kayalık adalarda deniz aslanları ve penguenler.'),
  (1805, '604', 'Cusco', 'Cusco', 'Inca Trail', 'İnka Yolu', 'A four-day trek to Machu Picchu.', 'Machu Picchu''ya dört günlük trekking.'),
  (1806, '604', 'Cusco', 'Cusco', 'Sacsayhuaman', 'Sacsayhuamán', 'A massive Inca stone fortress.', 'Devasa İnka taş kalesi.'),
  (1807, '604', 'Cusco', 'Cusco', 'Plaza de Armas Cusco', 'Cusco Plaza de Armas', 'The colonial heart of Cusco.', 'Cusco''nun sömürge kalbi.'),
  (1808, '604', 'Cusco', 'Cusco', 'Moray', 'Moray', 'Circular Inca agricultural terraces.', 'Dairesel İnka tarım terasları.'),
  (1809, '604', 'Cusco', 'Cusco', 'Maras Salt Mines', 'Maras Tuz Madenleri', 'Thousands of salt pans on a hillside.', 'Yamaçta binlerce tuz havuzu.'),
  (1810, '604', 'Trujillo', 'Trujillo', 'Chan Chan', 'Chan Chan', 'The largest adobe city in the Americas.', 'Amerika''nın en büyük kerpiç şehri.'),
  (1811, '076', 'Sao Paulo', 'São Paulo', 'Avenida Paulista', 'Avenida Paulista', 'The city''s cultural boulevard.', 'Şehrin kültür bulvarı.'),
  (1812, '076', 'Salvador', 'Salvador', 'Pelourinho', 'Pelourinho', 'A colorful Afro-Brazilian old town.', 'Renkli Afro-Brezilya eski şehri.'),
  (1813, '076', 'Fernando de Noronha', 'Fernando de Noronha', 'Fernando de Noronha', 'Fernando de Noronha', 'Protected beaches and dolphins.', 'Korunan plajlar ve yunuslar.'),
  (1814, '076', 'Manaus', 'Manaus', 'Amazon Rainforest', 'Amazon Yağmur Ormanı', 'Where the black and brown rivers meet.', 'Siyah ve kahverengi nehirlerin buluştuğu yer.'),
  (1815, '076', 'Pantanal', 'Pantanal', 'Pantanal Wetlands', 'Pantanal Sulak Alanları', 'The best place to see jaguars.', 'Jaguarları görmek için en iyi yer.'),
  (1816, '076', 'Florianopolis', 'Florianópolis', 'Florianopolis Beaches', 'Florianópolis Plajları', 'A surf island with over 40 beaches.', '40''tan fazla plajlı sörf adası.'),
  (1817, '076', 'Ouro Preto', 'Ouro Preto', 'Ouro Preto', 'Ouro Preto', 'A baroque gold-rush town.', 'Barok altın hücumu kasabası.'),
  (1818, '076', 'Brasilia', 'Brasília', 'Brasilia Cathedral', 'Brasília Katedrali', 'A hyperboloid by Niemeyer.', 'Niemeyer''in hiperboloid yapısı.'),
  (1819, '076', 'Paraty', 'Paraty', 'Paraty', 'Paraty', 'A colonial port town.', 'Sömürge liman kasabası.'),
  (1820, '076', 'Ilha Grande', 'Ilha Grande', 'Ilha Grande', 'Ilha Grande', 'A car-free jungle island.', 'Araçsız orman adası.'),
  (1821, '076', 'Jericoacoara', 'Jericoacoara', 'Jericoacoara', 'Jericoacoara', 'Dunes, lagoons and sunsets.', 'Kum tepeleri, lagünler ve gün batımı.'),
  (1822, '076', 'Bonito', 'Bonito', 'Bonito', 'Bonito', 'Crystal-clear rivers and caves.', 'Berrak nehirler ve mağaralar.'),
  (1823, '076', 'Chapada Diamantina', 'Chapada Diamantina', 'Chapada Diamantina', 'Chapada Diamantina', 'Waterfalls and table mountains.', 'Şelaleler ve masa dağlar.'),
  (1824, '076', 'Rio de Janeiro', 'Rio de Janeiro', 'Ipanema Beach', 'Ipanema Plajı', 'The beach of the Girl from Ipanema.', 'Ipanemalı Kız''ın plajı.'),
  (1825, '076', 'Rio de Janeiro', 'Rio de Janeiro', 'Selaron Steps', 'Selarón Merdivenleri', 'A mosaic-tiled staircase.', 'Mozaik çinili merdiven.'),
  (1826, '076', 'Rio de Janeiro', 'Rio de Janeiro', 'Tijuca National Park', 'Tijuca Milli Parkı', 'The world''s largest urban rainforest.', 'Dünyanın en büyük kentsel yağmur ormanı.'),
  (1827, '032', 'Buenos Aires', 'Buenos Aires', 'Casa Rosada', 'Casa Rosada', 'The pink presidential palace.', 'Pembe başkanlık sarayı.'),
  (1828, '032', 'Buenos Aires', 'Buenos Aires', 'Teatro Colon', 'Teatro Colón', 'One of the world''s best opera houses.', 'Dünyanın en iyi opera binalarından biri.'),
  (1829, '032', 'Buenos Aires', 'Buenos Aires', 'El Ateneo Grand Splendid', 'El Ateneo Grand Splendid', 'A theatre turned bookshop.', 'Kitapçıya dönüşmüş tiyatro.'),
  (1830, '032', 'Buenos Aires', 'Buenos Aires', 'Obelisco', 'Obelisco', 'The city''s iconic 67-metre obelisk.', 'Şehrin ikonik 67 metrelik dikilitaşı.'),
  (1831, '032', 'Bariloche', 'Bariloche', 'Bariloche Lake District', 'Bariloche Göller Bölgesi', 'Alpine lakes and chocolate.', 'Alp gölleri ve çikolata.'),
  (1832, '032', 'Salta', 'Salta', 'Quebrada de las Conchas', 'Quebrada de las Conchas', 'Red rock canyon near Salta.', 'Salta yakınında kırmızı kaya kanyonu.'),
  (1833, '032', 'Jujuy', 'Jujuy', 'Serrania de Hornocal', 'Hornocal Dağları', 'The Mountain of Fourteen Colors.', 'On Dört Renkli Dağ.'),
  (1834, '032', 'Puerto Iguazu', 'Puerto Iguazú', 'Iguazu Falls Argentina', 'Iguazu Şelaleleri Arjantin', 'Devil''s Throat from the Argentine side.', 'Arjantin tarafından Şeytan''ın Boğazı.'),
  (1835, '032', 'El Chalten', 'El Chaltén', 'Mount Fitz Roy', 'Fitz Roy Dağı', 'Patagonia''s iconic granite spire.', 'Patagonya''nın ikonik granit sivri zirvesi.'),
  (1836, '032', 'Puerto Madryn', 'Puerto Madryn', 'Peninsula Valdes', 'Valdés Yarımadası', 'Whales, sea lions and orcas.', 'Balinalar, deniz aslanları ve katil balinalar.'),
  (1837, '032', 'Mendoza', 'Mendoza', 'Aconcagua', 'Aconcagua', 'The highest peak outside Asia.', 'Asya dışındaki en yüksek zirve.'),
  (1838, '032', 'San Juan', 'San Juan', 'Ischigualasto Provincial Park', 'Ischigualasto Eyalet Parkı', 'A moon-like valley of fossils.', 'Fosillerle dolu ay yüzeyi gibi vadi.'),
  (1839, '032', 'Santa Cruz', 'Santa Cruz', 'Cueva de las Manos', 'Cueva de las Manos', 'Ancient hand stencils on cave walls.', 'Mağara duvarlarında antik el izleri.'),
  (1840, '032', 'Buenos Aires', 'Buenos Aires', 'Puerto Madero', 'Puerto Madero', 'A modern waterfront district.', 'Modern rıhtım bölgesi.'),
  (1841, '152', 'Santiago', 'Santiago', 'Cerro San Cristobal', 'San Cristóbal Tepesi', 'A hill with a Virgin Mary statue.', 'Meryem Ana heykelli tepe.'),
  (1842, '152', 'Aysen', 'Aysén', 'Marble Caves', 'Mermer Mağaralar', 'Swirling blue marble caverns.', 'Girdaplı mavi mermer mağaralar.'),
  (1843, '152', 'Pucon', 'Pucón', 'Villarrica Volcano', 'Villarrica Yanardağı', 'A smoking volcano you can climb.', 'Tırmanılabilen tüten yanardağ.'),
  (1844, '152', 'Atacama', 'Atacama', 'Valle de la Luna', 'Ay Vadisi', 'Dunes and salt caves at sunset.', 'Gün batımında kum tepeleri ve tuz mağaraları.'),
  (1845, '152', 'Atacama', 'Atacama', 'El Tatio Geysers', 'El Tatio Gayzerleri', 'Steaming geysers at dawn.', 'Şafakta buharlı gayzerler.'),
  (1846, '152', 'Chiloe', 'Chiloé', 'Chiloe Palafitos', 'Chiloé Palafitoları', 'Stilt houses and wooden churches.', 'Kazıklı evler ve ahşap kiliseler.'),
  (1847, '152', 'Atacama', 'Atacama', 'Miscanti Lagoon', 'Miscanti Lagünü', 'A high-altitude blue lagoon.', 'Yüksek rakımlı mavi lagün.'),
  (1848, '152', 'Santiago', 'Santiago', 'Cajon del Maipo', 'Cajón del Maipo', 'Andean valley near Santiago.', 'Santiago yakınında And vadisi.'),
  (1849, '152', 'Punta Arenas', 'Punta Arenas', 'Strait of Magellan', 'Macellan Boğazı', 'The historic passage at the tip of South America.', 'Güney Amerika''nın ucunda tarihi geçit.'),
  (1850, '170', 'Bogota', 'Bogotá', 'Monserrate', 'Monserrate', 'A hilltop church above Bogotá.', 'Bogotá''nın üzerinde tepe kilisesi.'),
  (1851, '170', 'Bogota', 'Bogotá', 'Gold Museum', 'Altın Müzesi', 'Thousands of pre-Columbian gold pieces.', 'Binlerce Kolomb öncesi altın eser.'),
  (1852, '170', 'Medellin', 'Medellín', 'Comuna 13', 'Comuna 13', 'A transformed neighbourhood of street art.', 'Sokak sanatıyla dönüşen mahalle.'),
  (1853, '170', 'Santa Marta', 'Santa Marta', 'Tayrona National Park', 'Tayrona Milli Parkı', 'Jungle beaches on the Caribbean.', 'Karayipler''de orman plajları.'),
  (1854, '170', 'Meta', 'Meta', 'Cano Cristales', 'Caño Cristales', 'The ''river of five colors''.', '''Beş renkli nehir''.'),
  (1855, '170', 'San Andres', 'San Andrés', 'San Andres Island', 'San Andrés Adası', 'The sea of seven colors.', 'Yedi renkli deniz.'),
  (1856, '170', 'Zipaquira', 'Zipaquirá', 'Salt Cathedral of Zipaquira', 'Zipaquirá Tuz Katedrali', 'A cathedral inside a salt mine.', 'Tuz madeni içinde katedral.'),
  (1857, '170', 'Santa Marta', 'Santa Marta', 'Lost City (Ciudad Perdida)', 'Kayıp Şehir (Ciudad Perdida)', 'A multi-day jungle trek to ruins.', 'Kalıntılara günlerce süren orman yürüyüşü.'),
  (1858, '170', 'Villa de Leyva', 'Villa de Leyva', 'Villa de Leyva', 'Villa de Leyva', 'A whitewashed colonial town.', 'Beyaz badanalı sömürge kasabası.'),
  (1859, '170', 'Huila', 'Huila', 'Tatacoa Desert', 'Tatacoa Çölü', 'A red and grey desert for stargazing.', 'Yıldız izlemek için kırmızı ve gri çöl.'),
  (1860, '170', 'Cartagena', 'Cartagena', 'Castillo San Felipe de Barajas', 'San Felipe de Barajas Kalesi', 'A huge Spanish hilltop fortress.', 'Büyük İspanyol tepe kalesi.'),
  (1861, '170', 'Barichara', 'Barichara', 'Barichara', 'Barichara', 'Colombia''s prettiest town.', 'Kolombiya''nın en güzel kasabası.'),
  (1862, '218', 'Cotopaxi', 'Cotopaxi', 'Cotopaxi Volcano', 'Cotopaxi Yanardağı', 'A snowy active volcano.', 'Karlı aktif yanardağ.'),
  (1863, '218', 'Banos', 'Baños', 'Casa del Arbol Swing', 'Casa del Árbol Salıncağı', 'The swing at the end of the world.', 'Dünyanın ucundaki salıncak.'),
  (1864, '218', 'Quito', 'Quito', 'Middle of the World Monument', 'Dünyanın Ortası Anıtı', 'The equator monument.', 'Ekvator anıtı.'),
  (1865, '218', 'Quilotoa', 'Quilotoa', 'Quilotoa Crater Lake', 'Quilotoa Krater Gölü', 'A green crater lake.', 'Yeşil krater gölü.'),
  (1866, '218', 'Cuenca', 'Cuenca', 'Cuenca Old Town', 'Cuenca Eski Şehir', 'A colonial UNESCO city.', 'UNESCO sömürge şehri.'),
  (1867, '218', 'Otavalo', 'Otavalo', 'Otavalo Market', 'Otavalo Pazarı', 'A famous indigenous textile market.', 'Ünlü yerli tekstil pazarı.'),
  (1868, '218', 'Yasuni', 'Yasuní', 'Yasuni National Park', 'Yasuní Milli Parkı', 'Amazon biodiversity hotspot.', 'Amazon biyoçeşitlilik noktası.'),
  (1869, '068', 'Lake Titicaca', 'Titicaca Gölü', 'Isla del Sol', 'Isla del Sol', 'The Inca birthplace of the sun.', 'İnka''ların güneşin doğum yeri.'),
  (1870, '068', 'La Paz', 'La Paz', 'Death Road', 'Ölüm Yolu', 'A famous mountain biking road.', 'Ünlü dağ bisikleti yolu.'),
  (1871, '068', 'Potosi', 'Potosí', 'Cerro Rico, Potosi', 'Cerro Rico, Potosí', 'The silver mountain.', 'Gümüş dağı.'),
  (1872, '068', 'Sucre', 'Sucre', 'Sucre White City', 'Sucre Beyaz Şehir', 'A whitewashed colonial capital.', 'Beyaz badanalı sömürge başkenti.'),
  (1873, '068', 'Tiwanaku', 'Tiwanaku', 'Tiwanaku', 'Tiwanaku', 'A pre-Inca ceremonial site.', 'İnka öncesi tören alanı.'),
  (1874, '068', 'La Paz', 'La Paz', 'Mi Teleferico', 'Mi Teleférico', 'The world''s highest urban cable car.', 'Dünyanın en yüksek kentsel teleferiği.'),
  (1875, '858', 'Montevideo', 'Montevideo', 'Ciudad Vieja Montevideo', 'Montevideo Ciudad Vieja', 'Colonial streets and a Rambla.', 'Sömürge sokakları ve Rambla.'),
  (1876, '858', 'Rocha', 'Rocha', 'Cabo Polonio', 'Cabo Polonio', 'A car-free dune village.', 'Araçsız kum tepesi köyü.'),
  (1877, '858', 'Punta del Este', 'Punta del Este', 'Casapueblo', 'Casapueblo', 'A white Mediterranean-style house.', 'Beyaz Akdeniz tarzı ev.'),
  (1878, '858', 'Rocha', 'Rocha', 'Punta del Diablo', 'Punta del Diablo', 'A laid-back surf village.', 'Rahat sörf köyü.'),
  (1879, '600', 'Asuncion', 'Asunción', 'Palacio de los Lopez', 'Palacio de los López', 'The presidential palace on the river.', 'Nehir kıyısında başkanlık sarayı.'),
  (1880, '600', 'Itapua', 'Itapúa', 'Salto Cristal', 'Salto Cristal', 'A waterfall in a green setting.', 'Yeşilliklerle çevrili şelale.'),
  (1881, '862', 'Merida', 'Mérida', 'Merida Cable Car', 'Mérida Teleferiği', 'One of the world''s highest cable cars.', 'Dünyanın en yüksek teleferiklerinden biri.'),
  (1882, '862', 'Bolivar', 'Bolívar', 'Mount Roraima', 'Roraima Dağı', 'A table mountain in the Gran Sabana.', 'Gran Sabana''da masa dağ.'),
  (1883, '862', 'Margarita', 'Margarita', 'Margarita Island', 'Margarita Adası', 'A Caribbean island of beaches.', 'Plajlı Karayip adası.'),
  (1884, '328', 'Kaieteur', 'Kaieteur', 'Kaieteur Falls', 'Kaieteur Şelalesi', 'One of the world''s most powerful single-drop falls.', 'Dünyanın en güçlü tek düşüşlü şelalelerinden biri.'),
  (1885, '188', 'Manuel Antonio', 'Manuel Antonio', 'Manuel Antonio National Park', 'Manuel Antonio Milli Parkı', 'Monkeys and beaches in the jungle.', 'Ormanda maymunlar ve plajlar.'),
  (1886, '188', 'Tortuguero', 'Tortuguero', 'Tortuguero National Park', 'Tortuguero Milli Parkı', 'Sea turtle nesting canals.', 'Deniz kaplumbağası yuvalama kanalları.'),
  (1887, '188', 'Alajuela', 'Alajuela', 'Poas Volcano', 'Poás Yanardağı', 'A volcano with a steaming crater.', 'Buharlı kraterli yanardağ.'),
  (1888, '188', 'Osa', 'Osa', 'Corcovado National Park', 'Corcovado Milli Parkı', 'One of the most biodiverse places.', 'Dünyanın en biyoçeşitli yerlerinden biri.'),
  (1889, '188', 'Guanacaste', 'Guanacaste', 'Rio Celeste', 'Río Celeste', 'A blue river waterfall.', 'Mavi nehir şelalesi.'),
  (1890, '188', 'Guanacaste', 'Guanacaste', 'Tamarindo Beach', 'Tamarindo Plajı', 'A surf and sunset beach town.', 'Sörf ve gün batımı plaj kasabası.'),
  (1891, '591', 'Panama City', 'Panama Şehri', 'Casco Viejo', 'Casco Viejo', 'A colonial old town with rooftop bars.', 'Teras barlarıyla sömürge eski şehir.'),
  (1892, '591', 'Boquete', 'Boquete', 'Boquete Coffee Highlands', 'Boquete Kahve Yaylaları', 'Coffee farms in the cloud forest.', 'Bulut ormanında kahve çiftlikleri.'),
  (1893, '591', 'Gamboa', 'Gamboa', 'Soberania National Park', 'Soberanía Milli Parkı', 'Rainforest by the canal.', 'Kanal yanında yağmur ormanı.'),
  (1894, '320', 'Solola', 'Sololá', 'Lake Atitlan', 'Atitlán Gölü', 'A lake ringed by volcanoes.', 'Yanardağlarla çevrili göl.'),
  (1895, '320', 'Coban', 'Cobán', 'Semuc Champey', 'Semuc Champey', 'Turquoise limestone pools.', 'Turkuaz kireçtaşı havuzlar.'),
  (1896, '320', 'Escuintla', 'Escuintla', 'Pacaya Volcano', 'Pacaya Yanardağı', 'Roast marshmallows on lava.', 'Lavda marshmallow kızart.'),
  (1897, '320', 'Chichicastenango', 'Chichicastenango', 'Chichicastenango Market', 'Chichicastenango Pazarı', 'A colorful Maya market.', 'Renkli Maya pazarı.'),
  (1898, '320', 'Antigua Guatemala', 'Antigua Guatemala', 'Acatenango Volcano', 'Acatenango Yanardağı', 'An overnight hike to see Fuego erupt.', 'Fuego''nun patlamasını görmek için gecelik yürüyüş.'),
  (1899, '084', 'San Ignacio', 'San Ignacio', 'Actun Tunichil Muknal Cave', 'Actun Tunichil Muknal Mağarası', 'A Maya ceremonial cave.', 'Maya tören mağarası.'),
  (1900, '084', 'Caye Caulker', 'Caye Caulker', 'Caye Caulker', 'Caye Caulker', 'A ''go slow'' island.', '''Yavaşla'' adası.'),
  (1901, '084', 'Cayo', 'Cayo', 'Xunantunich', 'Xunantunich', 'A Maya pyramid by a river.', 'Nehir kıyısında Maya piramidi.'),
  (1902, '340', 'Copan', 'Copán', 'Copan Ruins', 'Copán Kalıntıları', 'A Maya city of carved stelae.', 'Oyma steller şehir.'),
  (1903, '340', 'Roatan', 'Roatán', 'Roatan Island', 'Roatán Adası', 'Reef diving and beaches.', 'Resif dalışı ve plajlar.'),
  (1904, '340', 'Utila', 'Utila', 'Utila', 'Utila', 'Cheap diving and whale sharks.', 'Ucuz dalış ve balina köpekbalıkları.'),
  (1905, '558', 'Granada', 'Granada', 'Granada Nicaragua', 'Granada Nikaragua', 'A colonial city on a great lake.', 'Büyük gölde sömürge şehri.'),
  (1906, '558', 'Ometepe', 'Ometepe', 'Ometepe Island', 'Ometepe Adası', 'Twin volcanoes in a lake.', 'Gölde ikiz yanardağlar.'),
  (1907, '558', 'Leon', 'León', 'Leon Cathedral', 'León Katedrali', 'A white cathedral with rooftop walk.', 'Çatı yürüyüşlü beyaz katedral.'),
  (1908, '558', 'Masaya', 'Masaya', 'Masaya Volcano', 'Masaya Yanardağı', 'A glowing lava lake.', 'Parlayan lav gölü.'),
  (1909, '222', 'Santa Ana', 'Santa Ana', 'Santa Ana Volcano', 'Santa Ana Yanardağı', 'A volcano with a turquoise crater lake.', 'Turkuaz krater gölü olan yanardağ.'),
  (1910, '222', 'Ahuachapan', 'Ahuachapán', 'Ruta de las Flores', 'Çiçekler Rotası', 'A route of colorful coffee villages.', 'Renkli kahve köyleri rotası.'),
  (1911, '222', 'San Juan Opico', 'San Juan Opico', 'Joya de Ceren', 'Joya de Cerén', 'The ''Pompeii of the Americas''.', '''Amerika''nın Pompeii''si''.'),
  (1912, '192', 'Varadero', 'Varadero', 'Varadero Beach', 'Varadero Plajı', 'A long white-sand beach.', 'Uzun beyaz kumlu plaj.'),
  (1913, '192', 'Cienfuegos', 'Cienfuegos', 'Cienfuegos', 'Cienfuegos', 'The ''Pearl of the South''.', '''Güneyin İncisi''.'),
  (1914, '192', 'Santiago de Cuba', 'Santiago de Cuba', 'Santiago de Cuba', 'Santiago de Cuba', 'Cuba''s music and revolution city.', 'Küba''nın müzik ve devrim şehri.'),
  (1915, '192', 'Santa Clara', 'Santa Clara', 'Che Guevara Mausoleum', 'Che Guevara Anıt Mezarı', 'A memorial in Santa Clara.', 'Santa Clara''da anıt.'),
  (1916, '192', 'Cayo Coco', 'Cayo Coco', 'Cayo Coco', 'Cayo Coco', 'A cay resort of white sand.', 'Beyaz kumlu ada tatil beldesi.'),
  (1917, '192', 'Havana', 'Havana', 'Hemingway''s Floridita', 'Hemingway''in Floridita''sı', 'The daiquiri bar of Hemingway.', 'Hemingway''in daiquiri barı.'),
  (1918, '388', 'Kingston', 'Kingston', 'Blue Mountains', 'Blue Mountains', 'Jamaican coffee highlands.', 'Jamaika kahve yaylaları.'),
  (1919, '388', 'Kingston', 'Kingston', 'Bob Marley Museum', 'Bob Marley Müzesi', 'The reggae star''s home.', 'Reggae yıldızının evi.'),
  (1920, '388', 'Montego Bay', 'Montego Bay', 'Doctor''s Cave Beach', 'Doctor''s Cave Plajı', 'A famous Montego Bay beach.', 'Ünlü Montego Bay plajı.'),
  (1921, '388', 'Ocho Rios', 'Ocho Rios', 'Blue Hole Ocho Rios', 'Ocho Rios Mavi Delik', 'Cliff-jumping and waterfalls.', 'Uçurumdan atlama ve şelaleler.'),
  (1922, '388', 'Negril', 'Negril', 'Rick''s Cafe', 'Rick''s Cafe', 'Cliff jumping at sunset.', 'Gün batımında uçurumdan atlama.'),
  (1923, '044', 'Nassau', 'Nassau', 'Atlantis Paradise Island', 'Atlantis Paradise Island', 'A famous resort with aquarium and water park.', 'Akvaryum ve su parkı olan ünlü resort.'),
  (1924, '044', 'Harbour Island', 'Harbour Island', 'Pink Sands Beach', 'Pembe Kum Plajı', 'A blush-colored beach.', 'Pembemsi renkli plaj.'),
  (1925, '044', 'Exuma', 'Exuma', 'Thunderball Grotto', 'Thunderball Mağarası', 'A snorkelling cave from a Bond film.', 'Bond filminden şnorkel mağarası.'),
  (1926, '044', 'Eleuthera', 'Eleuthera', 'Glass Window Bridge', 'Glass Window Köprüsü', 'Atlantic and Caribbean meet.', 'Atlantik ve Karayip buluşur.'),
  (1927, '214', 'Santo Domingo', 'Santo Domingo', 'Colonial Zone, Santo Domingo', 'Sömürge Bölgesi, Santo Domingo', 'The oldest European city in the Americas.', 'Amerika''nın en eski Avrupa şehri.'),
  (1928, '214', 'La Romana', 'La Romana', 'Saona Island', 'Saona Adası', 'A tropical island of palm beaches.', 'Palmiyeli plajlarıyla tropikal ada.'),
  (1929, '214', 'Punta Cana', 'Punta Cana', 'Bavaro Beach', 'Bavaro Plajı', 'A long white-sand resort beach.', 'Uzun beyaz kumlu tatil plajı.'),
  (1930, '214', 'Puerto Plata', 'Puerto Plata', '27 Waterfalls of Damajagua', 'Damajagua 27 Şelalesi', 'Jump and slide through waterfalls.', 'Şelalelerde atlama ve kayma.'),
  (1931, '052', 'Bridgetown', 'Bridgetown', 'Harrison''s Cave', 'Harrison''s Cave', 'A crystal limestone cave by tram.', 'Tramvayla gezilen kristal kireçtaşı mağara.'),
  (1932, '052', 'Bathsheba', 'Bathsheba', 'Bathsheba Beach', 'Bathsheba Plajı', 'Rock-strewn surf coast.', 'Kayalarla dolu sörf kıyısı.'),
  (1933, '533', 'Oranjestad', 'Oranjestad', 'Eagle Beach', 'Eagle Plajı', 'One of the world''s best beaches.', 'Dünyanın en iyi plajlarından biri.'),
  (1934, '533', 'Oranjestad', 'Oranjestad', 'Arikok National Park', 'Arikok Milli Parkı', 'Caves, dunes and the Natural Pool.', 'Mağaralar, kum tepeleri ve Doğal Havuz.'),
  (1935, '531', 'Willemstad', 'Willemstad', 'Willemstad Handelskade', 'Willemstad Handelskade', 'Pastel Dutch-style waterfront houses.', 'Pastel Hollanda tarzı rıhtım evleri.'),
  (1936, '531', 'Westpunt', 'Westpunt', 'Grote Knip', 'Grote Knip', 'A turquoise cove with white sand.', 'Beyaz kumlu turkuaz koy.'),
  (1937, '780', 'Maracas', 'Maracas', 'Maracas Bay', 'Maracas Koyu', 'Home of bake-and-shark.', 'Bake-and-shark''ın yurdu.'),
  (1938, '780', 'La Brea', 'La Brea', 'Pitch Lake', 'Zift Gölü', 'The world''s largest natural asphalt lake.', 'Dünyanın en büyük doğal asfalt gölü.'),
  (1939, '662', 'Soufriere', 'Soufrière', 'The Pitons', 'Pitonlar', 'Twin volcanic spires from the sea.', 'Denizden yükselen ikiz volkanik sivrilikler.'),
  (1940, '662', 'Soufriere', 'Soufrière', 'Sulphur Springs', 'Kükürt Kaynakları', 'A drive-in volcano and mud baths.', 'Araçla girilen yanardağ ve çamur banyoları.'),
  (1941, '662', 'Marigot Bay', 'Marigot Bay', 'Marigot Bay', 'Marigot Koyu', 'A sheltered, palm-fringed harbour.', 'Palmiyelerle çevrili korunaklı liman.'),
  (1942, '308', 'St. George''s', 'St. George''s', 'Grand Anse Beach', 'Grand Anse Plajı', 'A two-mile white-sand beach.', 'İki millik beyaz kumlu plaj.'),
  (1943, '308', 'Molinere', 'Molinere', 'Underwater Sculpture Park', 'Su Altı Heykel Parkı', 'Sculptures on the seabed.', 'Deniz tabanında heykeller.'),
  (1944, '136', 'George Town', 'George Town', 'Seven Mile Beach', 'Yedi Mil Plajı', 'The Cayman Islands'' signature beach.', 'Cayman Adaları''nın simge plajı.'),
  (1945, '136', 'George Town', 'George Town', 'Stingray City', 'Stingray City', 'Stand among friendly stingrays.', 'Sevimli vatozların arasında durun.'),
  (1946, '028', 'English Harbour', 'English Harbour', 'Nelson''s Dockyard', 'Nelson''s Dockyard', 'A Georgian naval dockyard.', 'Gürcü dönemi donanma tersanesi.'),
  (1947, '028', 'English Harbour', 'English Harbour', 'Shirley Heights', 'Shirley Heights', 'A sunset lookout with steel-band music.', 'Çelik bando müzikli gün batımı seyir noktası.'),
  (1948, '092', 'Virgin Gorda', 'Virgin Gorda', 'The Baths', 'The Baths', 'Giant granite boulders and grottoes.', 'Dev granit kayalar ve mağaralar.'),
  (1949, '796', 'Providenciales', 'Providenciales', 'Grace Bay Beach', 'Grace Bay Plajı', 'Consistently ranked among the world''s best.', 'Dünyanın en iyileri arasında hep gösterilen plaj.'),
  (1950, '659', 'Basseterre', 'Basseterre', 'Brimstone Hill Fortress', 'Brimstone Hill Kalesi', 'The ''Gibraltar of the West Indies''.', '''Batı Hint Adaları''nın Cebelitarık''ı''.'),
  (1951, '212', 'Roseau', 'Roseau', 'Boiling Lake', 'Kaynayan Göl', 'A flooded fumarole hike.', 'Su basmış fumarol yürüyüşü.'),
  (1952, '630', 'San Juan', 'San Juan', 'El Morro Fortress', 'El Morro Kalesi', 'A 16th-century Spanish fortress.', '16. yüzyıl İspanyol kalesi.'),
  (1953, '630', 'Fajardo', 'Fajardo', 'Bioluminescent Bay (Mosquito Bay)', 'Biyolüminesan Koy (Mosquito Bay)', 'Water that glows when touched.', 'Dokunulunca parlayan su.'),
  (1954, '630', 'Rio Grande', 'Río Grande', 'El Yunque National Forest', 'El Yunque Milli Ormanı', 'The only tropical US rainforest.', 'ABD''nin tek tropikal yağmur ormanı.'),
  (1955, '060', 'Hamilton', 'Hamilton', 'Horseshoe Bay Beach', 'Horseshoe Bay Plajı', 'Pink-sand beach of Bermuda.', 'Bermuda''nın pembe kumlu plajı.'),
  (1956, '132', 'Fogo', 'Fogo', 'Pico do Fogo', 'Pico do Fogo', 'An active volcano with a village in the crater.', 'Kraterinde köy olan aktif yanardağ.'),
  (1957, '304', 'Nuuk', 'Nuuk', 'Nuuk', 'Nuuk', 'The colorful Arctic capital.', 'Renkli Arktik başkent.');

-- Cities (reuses an existing city with the same English name per country).
insert into public.cities (country_id, name, name_tr)
select distinct on (country_id, city) country_id, city, city_tr
from _new_landmarks
order by country_id, city, ord
on conflict (country_id, name) do nothing;

-- Landmarks. sort_order follows list order (above the earlier files' ranges),
-- so a city's older landmarks keep showing first.
insert into public.landmarks
  (country_id, city_id, name, name_tr, description, description_tr, sort_order)
select n.country_id, c.id, n.name, n.name_tr, n.description, n.description_tr, n.ord
from _new_landmarks n
join public.cities c on c.country_id = n.country_id and c.name = n.city
order by n.ord
on conflict (city_id, name) do nothing;

commit;

-- Optional, on its own: make specific landmarks show in "Yeni eklenenler".
-- Replace the names in the list, then run.
--
-- insert into public.catalog_highlights
--   (type, item_id, title, title_tr, subtitle, subtitle_tr, image_url)
-- select 'landmarks', l.id::text, l.name, l.name_tr, null, null, l.image_url
-- from public.landmarks l
-- where l.name in ('Meiji Shrine', 'Zion National Park')
-- on conflict (type, item_id) do nothing;
