-- Run this in the Supabase SQL editor (Database > SQL Editor).
-- Safe to re-run: every insert is `on conflict ... do nothing`, so it only
-- ever adds what's missing — it never edits or deletes existing rows.
--
-- Second batch of landmarks after scripts/add_landmarks.sql: 416 more
-- landmarks across 141 countries (the original countries plus new ones), plus any
-- missing cities. Unlike add_landmarks.sql this file does NOT create
-- `catalog_highlights` ("Yeni eklenenler") rows — the home rail only shows
-- the newest 20, so a bulk import would push every curated highlight off
-- it. Highlight individual landmarks later from the admin panel
-- ("Yeni eklenenler" checkbox) or with the snippet at the bottom.
-- Photos are left empty on purpose — upload them from the admin panel.
--
-- To add more, append rows to the `_new_landmarks` values list (keep `ord`
-- increasing and above the current max) and re-run the whole file.
-- `country_id` is the `id` from data/worldCountries.json, not a name lookup.

begin;

create temp table _new_landmarks (
  ord int not null,
  country_id text not null,
  city text not null,
  city_tr text,
  name text not null,
  name_tr text,
  description text,
  description_tr text
) on commit drop;

insert into _new_landmarks
  (ord, country_id, city, city_tr, name, name_tr, description, description_tr)
values
  (100, '792', 'Istanbul', 'İstanbul', 'Blue Mosque', 'Sultanahmet Camii', 'Six slender minarets and thousands of blue Iznik tiles.', 'Altı minaresi ve binlerce mavi İznik çinisiyle ünlü cami.'),
  (101, '792', 'Istanbul', 'İstanbul', 'Galata Tower', 'Galata Kulesi', 'A medieval tower with a 360-degree view of the Bosphorus.', 'Boğaz''ı 360 derece gören ortaçağ kulesi.'),
  (102, '792', 'Istanbul', 'İstanbul', 'Basilica Cistern', 'Yerebatan Sarnıcı', 'An atmospheric underground Byzantine reservoir held up by 336 columns.', '336 sütunla ayakta duran, atmosferik Bizans yeraltı sarnıcı.'),
  (103, '792', 'Istanbul', 'İstanbul', 'Dolmabahce Palace', 'Dolmabahçe Sarayı', 'A lavish waterfront palace of the late Ottoman era.', 'Geç dönem Osmanlı''nın görkemli deniz kıyısı sarayı.'),
  (104, '792', 'Istanbul', 'İstanbul', 'Grand Bazaar', 'Kapalıçarşı', 'One of the world''s oldest and largest covered markets.', 'Dünyanın en eski ve en büyük kapalı çarşılarından biri.'),
  (105, '792', 'Ankara', 'Ankara', 'Anitkabir', 'Anıtkabir', 'The mausoleum of Mustafa Kemal Atatürk, the founder of the Republic.', 'Cumhuriyet''in kurucusu Mustafa Kemal Atatürk''ün anıt mezarı.'),
  (106, '792', 'Canakkale', 'Çanakkale', 'Troy', 'Truva Antik Kenti', 'The legendary city of Homer''s Iliad and its famous wooden horse.', 'Homeros''un İlyada''sındaki efsanevi şehir ve ünlü tahta at.'),
  (107, '792', 'Canakkale', 'Çanakkale', 'Gallipoli Peninsula', 'Gelibolu Yarımadası', 'Battlefields and memorials of the 1915 Gallipoli campaign.', '1915 Çanakkale Savaşları''nın cepheleri ve şehitlikleri.'),
  (108, '792', 'Antalya', 'Antalya', 'Kaleici Old Town', 'Kaleiçi', 'Ottoman houses and a Roman harbour inside Antalya''s old walls.', 'Antalya''nın tarihi surları içinde Osmanlı evleri ve Roma limanı.'),
  (109, '792', 'Antalya', 'Antalya', 'Aspendos Theatre', 'Aspendos Antik Tiyatrosu', 'The best-preserved Roman theatre in Anatolia, still used for concerts.', 'Anadolu''nun en iyi korunmuş, hâlâ konserlere ev sahipliği yapan Roma tiyatrosu.'),
  (110, '792', 'Adiyaman', 'Adıyaman', 'Mount Nemrut', 'Nemrut Dağı', 'Giant stone heads of ancient gods watching the sunrise.', 'Gün doğumunu izleyen antik tanrıların dev taş başları.'),
  (111, '792', 'Kars', 'Kars', 'Ani Ruins', 'Ani Harabeleri', 'The ruined medieval Armenian capital known as the city of 1001 churches.', '1001 kilise şehri olarak bilinen ortaçağ Ermeni başkentinin kalıntıları.'),
  (112, '792', 'Agri', 'Ağrı', 'Ishak Pasha Palace', 'İshak Paşa Sarayı', 'A fairytale Ottoman palace set against the Ararat mountains.', 'Ağrı Dağı''nın eteğinde masalsı bir Osmanlı sarayı.'),
  (113, '792', 'Trabzon', 'Trabzon', 'Uzungol', 'Uzungöl', 'An alpine-style mountain lake village in the Black Sea highlands.', 'Karadeniz yaylalarında Alp havasında bir göl köyü.'),
  (114, '792', 'Edirne', 'Edirne', 'Selimiye Mosque', 'Selimiye Camii', 'Mimar Sinan''s masterpiece, crowned with a vast central dome.', 'Mimar Sinan''ın devasa kubbeli ustalık eseri.'),
  (115, '792', 'Bursa', 'Bursa', 'Bursa Grand Mosque', 'Bursa Ulu Camii', 'An early Ottoman mosque with 20 domes and masterful calligraphy.', '20 kubbesi ve hat sanatıyla ünlü erken dönem Osmanlı camisi.'),
  (116, '250', 'Paris', 'Paris', 'Notre-Dame Cathedral', 'Notre-Dame Katedrali', 'A Gothic masterpiece on the Île de la Cité.', 'Île de la Cité üzerinde yükselen Gotik başyapıt.'),
  (117, '250', 'Paris', 'Paris', 'Arc de Triomphe', 'Zafer Takı', 'A triumphal arch crowning the Champs-Élysées.', 'Champs-Élysées''nin ucunda yükselen zafer takı.'),
  (118, '250', 'Paris', 'Paris', 'Sacré-Cœur Basilica', 'Sacré-Cœur Bazilikası', 'A white-domed basilica with views over Montmartre and Paris.', 'Montmartre tepesinden Paris''e bakan beyaz kubbeli bazilika.'),
  (119, '250', 'Versailles', 'Versay', 'Palace of Versailles', 'Versay Sarayı', 'The opulent royal palace of Louis XIV and its Hall of Mirrors.', 'XIV. Louis''nin görkemli sarayı ve Aynalı Galeri.'),
  (120, '250', 'Normandy', 'Normandiya', 'Mont Saint-Michel', 'Mont Saint-Michel', 'A medieval abbey on a tidal island.', 'Gelgit adası üzerinde ortaçağ manastırı.'),
  (121, '250', 'Nice', 'Nice', 'Promenade des Anglais', 'Promenade des Anglais', 'A seaside boulevard along the Baie des Anges on the French Riviera.', 'Fransız Rivierası''nda Baie des Anges boyunca uzanan sahil bulvarı.'),
  (122, '250', 'Chamonix', 'Chamonix', 'Mont Blanc', 'Mont Blanc', 'The highest peak in the Alps, reached by a dramatic cable car.', 'Alplerin en yüksek zirvesi ve nefes kesen teleferik.'),
  (123, '380', 'Rome', 'Roma', 'Trevi Fountain', 'Trevi Çeşmesi', 'Toss a coin into Rome''s grandest baroque fountain.', 'Roma''nın en görkemli barok çeşmesine bir bozuk para at.'),
  (124, '380', 'Rome', 'Roma', 'Pantheon', 'Pantheon', 'A 2,000-year-old temple with the world''s largest unreinforced concrete dome.', 'Dünyanın en büyük donatısız beton kubbesine sahip 2000 yıllık tapınak.'),
  (125, '380', 'Pisa', 'Pisa', 'Leaning Tower of Pisa', 'Pisa Kulesi', 'The world-famous bell tower that leans at an impossible angle.', 'Dünyaca ünlü, eğik duran çan kulesi.'),
  (126, '380', 'Naples', 'Napoli', 'Pompeii', 'Pompeii', 'A Roman city frozen in time by the eruption of Mount Vesuvius.', 'Vezüv yanardağının patlamasıyla zamanda donan Roma kenti.'),
  (127, '380', 'Amalfi', 'Amalfi', 'Amalfi Coast', 'Amalfi Sahili', 'Pastel villages stacked on cliffs above the Mediterranean.', 'Akdeniz''e bakan kayalıklarda pastel renkli köyler.'),
  (128, '380', 'Milan', 'Milano', 'Milan Cathedral', 'Milano Katedrali', 'A Gothic cathedral with 3,400 statues and a rooftop walk.', '3400 heykeli ve çatı yürüyüşüyle Gotik katedral.'),
  (129, '380', 'Dolomites', 'Dolomitler', 'Lago di Braies', 'Braies Gölü', 'An emerald alpine lake ringed by the Dolomites.', 'Dolomitler''le çevrili zümrüt rengi dağ gölü.'),
  (130, '724', 'Madrid', 'Madrid', 'Royal Palace of Madrid', 'Madrid Kraliyet Sarayı', 'The largest functioning royal palace in Europe.', 'Avrupa''nın hâlâ kullanılan en büyük kraliyet sarayı.'),
  (131, '724', 'Barcelona', 'Barselona', 'Park Güell', 'Park Güell', 'Gaudí''s mosaic-covered park above Barcelona.', 'Gaudí''nin Barselona''ya bakan mozaik kaplı parkı.'),
  (132, '724', 'Barcelona', 'Barselona', 'La Rambla', 'La Rambla', 'Barcelona''s famous tree-lined pedestrian boulevard.', 'Barselona''nın ağaçlarla çevrili ünlü yaya bulvarı.'),
  (133, '724', 'Cordoba', 'Kordoba', 'Mezquita of Córdoba', 'Kordoba Mezquita Camii', 'A mosque-cathedral with a forest of red-and-white arches.', 'Kırmızı beyaz kemerlerden oluşan ormanıyla cami-katedral.'),
  (134, '724', 'Tenerife', 'Tenerife', 'Teide National Park', 'Teide Milli Parkı', 'Spain''s highest peak, rising from a lunar volcanic landscape.', 'Ay yüzeyini andıran volkanik arazide İspanya''nın en yüksek zirvesi.'),
  (135, '724', 'Toledo', 'Toledo', 'Toledo Old Town', 'Toledo Eski Şehir', 'A walled hilltop city where Christian, Muslim and Jewish heritage meet.', 'Hristiyan, Müslüman ve Yahudi mirasının buluştuğu surlu tepe şehri.'),
  (136, '620', 'Sintra', 'Sintra', 'Pena Palace', 'Pena Sarayı', 'A colorful Romanticist palace on a misty hilltop.', 'Sisli bir tepede renkli Romantik saray.'),
  (137, '620', 'Lisbon', 'Lizbon', 'Alfama District', 'Alfama Mahallesi', 'Lisbon''s oldest quarter of winding alleys and fado music.', 'Dar sokakları ve fado müziğiyle Lizbon''un en eski mahallesi.'),
  (138, '620', 'Algarve', 'Algarve', 'Benagil Cave', 'Benagil Mağarası', 'A sea cave with a sunlit skylight and golden beach.', 'Tavanındaki açıklıktan güneş ışığı giren, altın kumlu deniz mağarası.'),
  (139, '620', 'Madeira', 'Madeira', 'Madeira Levada Walks', 'Madeira Levada Yürüyüşleri', 'Trails along old irrigation channels through laurel forests.', 'Defne ormanlarının içinden eski sulama kanalları boyunca yürüyüş.'),
  (140, '300', 'Santorini', 'Santorini', 'Fira', 'Fira', 'The clifftop capital of Santorini with caldera views.', 'Kaldera manzaralı, uçurum üstündeki Santorini''nin başkenti.'),
  (141, '300', 'Mykonos', 'Mikonos', 'Mykonos Windmills', 'Mikonos Yel Değirmenleri', 'Whitewashed windmills overlooking the Aegean.', 'Ege''ye bakan bembeyaz yel değirmenleri.'),
  (142, '300', 'Meteora', 'Meteora', 'Meteora Monasteries', 'Meteora Manastırları', 'Monasteries perched on top of towering sandstone pillars.', 'Dev kumtaşı sütunların tepesindeki manastırlar.'),
  (143, '300', 'Crete', 'Girit', 'Knossos Palace', 'Knossos Sarayı', 'The ruins of the Minoan palace of the legendary Minotaur.', 'Efsanevi Minotor''un Minos Uygarlığı sarayının kalıntıları.'),
  (144, '300', 'Delphi', 'Delfi', 'Delphi Archaeological Site', 'Delfi Antik Kenti', 'The sanctuary of the ancient Greek oracle of Apollo.', 'Antik Yunan''ın Apollon kehanet tapınağı.'),
  (145, '826', 'London', 'Londra', 'London Eye', 'London Eye', 'A giant observation wheel on the Thames.', 'Thames kıyısında dev bir dönme dolap.'),
  (146, '826', 'London', 'Londra', 'Buckingham Palace', 'Buckingham Sarayı', 'The royal residence famous for its Changing of the Guard.', 'Nöbet değişimiyle ünlü kraliyet konutu.'),
  (147, '826', 'London', 'Londra', 'Tower of London', 'Londra Kulesi', 'A medieval fortress that houses the Crown Jewels.', 'Kraliyet mücevherlerini barındıran ortaçağ kalesi.'),
  (148, '826', 'Wiltshire', 'Wiltshire', 'Stonehenge', 'Stonehenge', 'The prehistoric ring of standing stones.', 'Tarih öncesi dikili taşlar halkası.'),
  (149, '826', 'Highlands', 'İskoç Highlands', 'Isle of Skye', 'Skye Adası', 'Fairy pools, jagged peaks and misty Scottish scenery.', 'Peri havuzları, sivri tepeler ve sisli İskoçya manzaraları.'),
  (150, '826', 'Giant''s Causeway', 'Giant''s Causeway', 'Giant''s Causeway', 'Devler Geçidi', 'Thousands of interlocking basalt columns on the Irish coast.', 'İrlanda kıyısında binlerce birbirine kenetlenen bazalt sütun.'),
  (151, '276', 'Cologne', 'Köln', 'Cologne Cathedral', 'Köln Katedrali', 'A Gothic giant that dominates the Rhine skyline.', 'Ren kıyısının siluetine hâkim Gotik dev.'),
  (152, '276', 'Munich', 'Münih', 'Marienplatz', 'Marienplatz', 'Munich''s central square with its famous glockenspiel.', 'Ünlü çan saatiyle Münih''in merkez meydanı.'),
  (153, '276', 'Berlin', 'Berlin', 'Berlin Wall Memorial', 'Berlin Duvarı Anıtı', 'Remnants of the wall that once divided the city.', 'Şehri bir zamanlar ikiye bölen duvarın kalıntıları.'),
  (154, '276', 'Rothenburg', 'Rothenburg', 'Rothenburg ob der Tauber', 'Rothenburg ob der Tauber', 'A perfectly preserved medieval walled town.', 'Mükemmel korunmuş ortaçağ surlu kasabası.'),
  (155, '276', 'Black Forest', 'Kara Orman', 'Black Forest', 'Kara Orman', 'Dense fir forests, cuckoo clocks and fairytale villages.', 'Yoğun çam ormanları, guguklu saatler ve masal köyleri.'),
  (156, '528', 'Amsterdam', 'Amsterdam', 'Anne Frank House', 'Anne Frank Evi', 'The hiding place where Anne Frank wrote her diary.', 'Anne Frank''in günlüğünü yazdığı saklanma evi.'),
  (157, '528', 'Amsterdam', 'Amsterdam', 'Rijksmuseum', 'Rijksmuseum', 'Dutch masterpieces including Rembrandt''s Night Watch.', 'Rembrandt''ın Gece Devriyesi dahil Hollanda başyapıtları.'),
  (158, '528', 'Keukenhof', 'Keukenhof', 'Keukenhof Gardens', 'Keukenhof Bahçeleri', 'Millions of tulips blooming in spring.', 'Baharda açan milyonlarca lale.'),
  (159, '528', 'Kinderdijk', 'Kinderdijk', 'Kinderdijk Windmills', 'Kinderdijk Yel Değirmenleri', 'Nineteen historic windmills in a polder landscape.', 'Polder manzarasında on dokuz tarihi yel değirmeni.'),
  (160, '056', 'Bruges', 'Brugge', 'Bruges Old Town', 'Brugge Eski Şehir', 'Canals, cobblestones and medieval gabled houses.', 'Kanallar, arnavut kaldırımları ve ortaçağ evleri.'),
  (161, '056', 'Brussels', 'Brüksel', 'Atomium', 'Atomium', 'A giant iron-crystal-shaped monument from the 1958 World''s Fair.', '1958 Dünya Fuarı''ndan kalma, dev demir kristali biçimli anıt.'),
  (162, '056', 'Ghent', 'Gent', 'Gravensteen Castle', 'Gravensteen Kalesi', 'A moated medieval castle in the heart of Ghent.', 'Gent''in merkezinde hendekli ortaçağ kalesi.'),
  (163, '756', 'Lucerne', 'Luzern', 'Chapel Bridge', 'Kapellbrücke', 'A medieval wooden covered bridge over the Reuss River.', 'Reuss Nehri üzerinde ortaçağdan kalma ahşap kapalı köprü.'),
  (164, '756', 'Interlaken', 'Interlaken', 'Jungfraujoch', 'Jungfraujoch', 'The ''Top of Europe'' reached by Europe''s highest railway.', 'Avrupa''nın en yüksek tren hattıyla çıkılan ''Avrupa''nın Zirvesi''.'),
  (165, '756', 'Geneva', 'Cenevre', 'Jet d''Eau', 'Jet d''Eau', 'A 140-metre fountain rising from Lake Geneva.', 'Cenevre Gölü''nden fışkıran 140 metrelik çeşme.'),
  (166, '756', 'Lauterbrunnen', 'Lauterbrunnen', 'Lauterbrunnen Valley', 'Lauterbrunnen Vadisi', 'A valley of 72 waterfalls beneath towering cliffs.', 'Yüksek kayalıklar altında 72 şelaleli vadi.'),
  (167, '040', 'Salzburg', 'Salzburg', 'Hohensalzburg Fortress', 'Hohensalzburg Kalesi', 'A huge hilltop fortress above Mozart''s hometown.', 'Mozart''ın memleketine bakan dev tepe kalesi.'),
  (168, '040', 'Hallstatt', 'Hallstatt', 'Hallstatt', 'Hallstatt', 'A lakeside village at the foot of the Alps, straight from a postcard.', 'Alplerin eteğinde, kartpostal gibi göl kıyısı köyü.'),
  (169, '040', 'Vienna', 'Viyana', 'St. Stephen''s Cathedral', 'Aziz Stephan Katedrali', 'Vienna''s Gothic cathedral with a patterned tiled roof.', 'Desenli çatısıyla Viyana''nın Gotik katedrali.'),
  (170, '040', 'Innsbruck', 'Innsbruck', 'Golden Roof', 'Altın Çatı', 'A 15th-century balcony topped with golden tiles in Innsbruck''s old town.', 'Innsbruck eski şehrinde 15. yüzyıldan kalma altın kiremitli balkon.'),
  (171, '203', 'Prague', 'Prag', 'Prague Castle', 'Prag Kalesi', 'The largest ancient castle complex in the world.', 'Dünyanın en büyük antik kale kompleksi.'),
  (172, '203', 'Prague', 'Prag', 'Old Town Square', 'Eski Şehir Meydanı', 'A medieval square with the famous Astronomical Clock.', 'Ünlü Astronomik Saat''in bulunduğu ortaçağ meydanı.'),
  (173, '203', 'Cesky Krumlov', 'Cesky Krumlov', 'Český Krumlov', 'Český Krumlov', 'A storybook town wrapped around a river bend.', 'Nehrin kıvrımına sarılmış masal gibi kasaba.'),
  (174, '348', 'Budapest', 'Budapeşte', 'Fisherman''s Bastion', 'Balıkçı Tabyası', 'A fairytale terrace with sweeping Danube views.', 'Tuna manzaralı masalsı bir teras.'),
  (175, '348', 'Budapest', 'Budapeşte', 'Széchenyi Thermal Bath', 'Széchenyi Kaplıcası', 'A grand neo-baroque thermal bath complex.', 'Görkemli neo-barok kaplıca kompleksi.'),
  (176, '348', 'Budapest', 'Budapeşte', 'Chain Bridge', 'Zincirli Köprü', 'The first permanent bridge linking Buda and Pest.', 'Buda ile Peşte''yi birleştiren ilk kalıcı köprü.'),
  (177, '191', 'Plitvice', 'Plitvice', 'Plitvice Lakes National Park', 'Plitvice Gölleri Milli Parkı', 'Sixteen turquoise lakes linked by waterfalls.', 'Şelalelerle birbirine bağlı on altı turkuaz göl.'),
  (178, '191', 'Split', 'Split', 'Diocletian''s Palace', 'Diocletian Sarayı', 'A Roman emperor''s palace that became a living old town.', 'Yaşayan eski şehre dönüşen Roma imparatorluk sarayı.'),
  (179, '191', 'Hvar', 'Hvar', 'Hvar Island', 'Hvar Adası', 'Lavender fields, sunshine and a lively Adriatic harbour.', 'Lavanta tarlaları, güneş ve hareketli bir Adriyatik limanı.'),
  (180, '191', 'Rovinj', 'Rovinj', 'Rovinj Old Town', 'Rovinj Eski Şehir', 'A colorful Venetian-style fishing town on a peninsula.', 'Yarımada üzerinde Venedik tarzı renkli balıkçı kasabası.'),
  (181, '578', 'Tromso', 'Tromsø', 'Tromsø', 'Tromsø', 'The Arctic gateway for Northern Lights and midnight sun.', 'Kuzey Işıkları ve gece yarısı güneşi için Arktik kapısı.'),
  (182, '578', 'Stavanger', 'Stavanger', 'Preikestolen (Pulpit Rock)', 'Preikestolen (Vaaz Kayası)', 'A flat cliff plateau rising 600 m above Lysefjord.', 'Lysefjord''un 600 metre üzerinde yükselen düz kayalık platform.'),
  (183, '578', 'Bergen', 'Bergen', 'Bryggen Wharf', 'Bryggen Rıhtımı', 'Colorful Hanseatic wooden warehouses on Bergen''s harbour.', 'Bergen limanında renkli Hansa ahşap depoları.'),
  (184, '578', 'Flam', 'Flåm', 'Flåm Railway', 'Flåm Demiryolu', 'One of the steepest and most scenic railway lines in the world.', 'Dünyanın en dik ve manzaralı demiryollarından biri.'),
  (185, '352', 'Reykjavik', 'Reykjavik', 'Blue Lagoon', 'Mavi Lagün', 'A milky-blue geothermal spa in a lava field.', 'Lav alanında sütlü mavi jeotermal kaplıca.'),
  (186, '352', 'Golden Circle', 'Altın Daire', 'Gullfoss Waterfall', 'Gullfoss Şelalesi', 'A thundering two-tier waterfall on the Golden Circle.', 'Altın Daire rotasında gürleyen iki kademeli şelale.'),
  (187, '352', 'Vik', 'Vik', 'Reynisfjara Black Sand Beach', 'Reynisfjara Kara Kum Plajı', 'Black basalt columns and sea stacks on a volcanic beach.', 'Volkanik plajda siyah bazalt sütunlar ve deniz kayalıkları.'),
  (188, '352', 'Jokulsarlon', 'Jökulsárlón', 'Jökulsárlón Glacier Lagoon', 'Jökulsárlón Buzul Lagünü', 'Icebergs drifting across a glacial lagoon.', 'Buzul lagününde sürüklenen buz dağları.'),
  (189, '643', 'Moscow', 'Moskova', 'Saint Basil''s Cathedral', 'Aziz Basil Katedrali', 'A cathedral with colorful onion domes on Red Square.', 'Kızıl Meydan''da renkli soğan kubbeli katedral.'),
  (190, '643', 'Saint Petersburg', 'Saint Petersburg', 'Hermitage Museum', 'Hermitage Müzesi', 'One of the largest art museums in the world, in the Winter Palace.', 'Kış Sarayı''nda yer alan dünyanın en büyük sanat müzelerinden biri.'),
  (191, '643', 'Saint Petersburg', 'Saint Petersburg', 'Church of the Savior on Spilled Blood', 'Dökülen Kan Üzerindeki Kurtarıcı Kilisesi', 'A mosaic-covered church built where Alexander II was assassinated.', 'II. Aleksandr''ın suikasta uğradığı yerde yapılan mozaik kaplı kilise.'),
  (192, '643', 'Lake Baikal', 'Baykal Gölü', 'Lake Baikal', 'Baykal Gölü', 'The deepest and oldest freshwater lake on Earth.', 'Dünyanın en derin ve en eski tatlı su gölü.'),
  (193, '616', 'Krakow', 'Krakow', 'Auschwitz-Birkenau Memorial', 'Auschwitz-Birkenau Anıtı', 'A somber memorial and museum of the Holocaust.', 'Soykırımı anan hüzünlü anıt ve müze.'),
  (194, '616', 'Krakow', 'Krakow', 'Wieliczka Salt Mine', 'Wieliczka Tuz Madeni', 'An underground world of salt chapels and sculptures.', 'Tuzdan şapeller ve heykellerle dolu yeraltı dünyası.'),
  (195, '616', 'Warsaw', 'Varşova', 'Warsaw Old Town', 'Varşova Eski Şehir', 'A meticulously rebuilt old town after World War II.', 'İkinci Dünya Savaşı sonrası titizlikle yeniden inşa edilen eski şehir.'),
  (196, '616', 'Zakopane', 'Zakopane', 'Morskie Oko', 'Morskie Oko', 'A glacial lake in the Tatra Mountains.', 'Tatra Dağları''nda bir buzul gölü.'),
  (197, '752', 'Stockholm', 'Stockholm', 'Vasa Museum', 'Vasa Müzesi', 'A remarkably preserved 17th-century warship.', 'Olağanüstü korunmuş 17. yüzyıl savaş gemisi.'),
  (198, '752', 'Kiruna', 'Kiruna', 'Icehotel', 'Icehotel', 'A hotel rebuilt from ice every winter in Swedish Lapland.', 'İsveç Laponya''sında her kış yeniden buzdan inşa edilen otel.'),
  (199, '752', 'Visby', 'Visby', 'Visby Medieval Town', 'Visby Ortaçağ Şehri', 'A walled Hanseatic town on the island of Gotland.', 'Gotland adasında Hansa dönemi surlu şehir.'),
  (200, '208', 'Copenhagen', 'Kopenhag', 'Nyhavn', 'Nyhavn', 'A colorful 17th-century waterfront with canals and cafes.', 'Kanallar ve kafelerle 17. yüzyıldan kalma renkli rıhtım.'),
  (201, '208', 'Copenhagen', 'Kopenhag', 'Tivoli Gardens', 'Tivoli Bahçeleri', 'One of the world''s oldest amusement parks.', 'Dünyanın en eski eğlence parklarından biri.'),
  (202, '208', 'Helsingor', 'Helsingør', 'Kronborg Castle', 'Kronborg Kalesi', 'The Renaissance castle known as Elsinore in Hamlet.', 'Hamlet''te Elsinore olarak bilinen Rönesans kalesi.'),
  (203, '246', 'Helsinki', 'Helsinki', 'Suomenlinna Sea Fortress', 'Suomenlinna Deniz Kalesi', 'An island fortress a short ferry ride from Helsinki.', 'Helsinki''den kısa bir vapur yolculuğu mesafesinde ada kalesi.'),
  (204, '246', 'Rovaniemi', 'Rovaniemi', 'Santa Claus Village', 'Noel Baba Köyü', 'Meet Santa on the Arctic Circle.', 'Kuzey Kutup Dairesi''nde Noel Baba ile tanış.'),
  (205, '246', 'Helsinki', 'Helsinki', 'Temppeliaukio Church', 'Temppeliaukio Kilisesi', 'A church carved directly into solid rock.', 'Doğrudan kayaya oyulmuş kilise.'),
  (206, '470', 'Valletta', 'Valletta', 'St. John''s Co-Cathedral', 'Aziz Yuhanna Katedrali', 'A baroque interior with a Caravaggio masterpiece.', 'Caravaggio''nun başyapıtını barındıran barok iç mekân.'),
  (207, '470', 'Mdina', 'Mdina', 'Mdina', 'Mdina', 'The silent walled city of Malta''s former capital.', 'Malta''nın eski başkenti olan sessiz surlu şehir.'),
  (208, '470', 'Gozo', 'Gozo', 'Azure Window Coast (Dwejra)', 'Dwejra Kıyısı', 'Dramatic cliffs and the Inland Sea on Gozo.', 'Gozo''da dramatik kayalıklar ve İç Deniz.'),
  (209, 'zz-n-cyprus', 'Famagusta', 'Gazimağusa', 'Salamis Ruins', 'Salamis Antik Kenti', 'Ancient Greek and Roman ruins on the Mediterranean coast.', 'Akdeniz kıyısında antik Yunan ve Roma kalıntıları.'),
  (210, 'zz-n-cyprus', 'Nicosia', 'Lefkoşa', 'Selimiye Mosque (Nicosia)', 'Selimiye Camii (Lefkoşa)', 'A Gothic cathedral turned mosque in the heart of Nicosia.', 'Lefkoşa''nın kalbinde camiye dönüştürülmüş Gotik katedral.'),
  (211, 'zz-n-cyprus', 'Karpas', 'Karpaz', 'Karpaz Peninsula Golden Beach', 'Karpaz Altın Kum Plajı', 'An untouched sandy beach where wild donkeys roam.', 'Yabani eşeklerin dolaştığı el değmemiş kumsal.'),
  (212, '268', 'Kazbegi', 'Kazbegi', 'Gergeti Trinity Church', 'Gergeti Teslis Kilisesi', 'A lonely church beneath snow-capped Mount Kazbek.', 'Karlı Kazbek Dağı''nın altında yalnız bir kilise.'),
  (213, '268', 'Mtskheta', 'Mtskheta', 'Jvari Monastery', 'Cvari Manastırı', 'A 6th-century monastery above the meeting of two rivers.', 'İki nehrin birleştiği yerin üzerinde 6. yüzyıldan kalma manastır.'),
  (214, '268', 'Svaneti', 'Svaneti', 'Ushguli Village', 'Uşguli Köyü', 'Medieval stone towers in one of Europe''s highest villages.', 'Avrupa''nın en yüksek köylerinden birinde ortaçağ taş kuleleri.'),
  (215, '031', 'Baku', 'Bakü', 'Old City (Icherisheher)', 'İçeri Şehir', 'A walled medieval core with the Maiden Tower.', 'Kız Kulesi''ni barındıran surlu ortaçağ merkezi.'),
  (216, '031', 'Baku', 'Bakü', 'Heydar Aliyev Center', 'Haydar Aliyev Merkezi', 'A flowing white building designed by Zaha Hadid.', 'Zaha Hadid''in tasarladığı akıcı hatlı beyaz yapı.'),
  (217, '031', 'Gobustan', 'Gobustan', 'Gobustan Mud Volcanoes', 'Gobustan Çamur Volkanları', 'Bubbling mud volcanoes and ancient rock carvings.', 'Kabaran çamur volkanları ve antik kaya kabartmaları.'),
  (218, '400', 'Wadi Rum', 'Wadi Rum', 'Wadi Rum', 'Wadi Rum', 'A red desert valley known as the Valley of the Moon.', 'Ay Vadisi olarak bilinen kızıl çöl vadisi.'),
  (219, '400', 'Dead Sea', 'Lut Gölü', 'Dead Sea', 'Lut Gölü', 'Float effortlessly on the lowest point on Earth.', 'Yeryüzünün en alçak noktasında kolayca suda süzül.'),
  (220, '400', 'Jerash', 'Cereş', 'Jerash Roman Ruins', 'Cereş Roma Kalıntıları', 'One of the best-preserved Roman provincial cities.', 'En iyi korunmuş Roma eyalet şehirlerinden biri.'),
  (221, '400', 'Amman', 'Amman', 'Amman Citadel', 'Amman Kalesi', 'Hilltop ruins of Roman, Byzantine and Umayyad eras.', 'Roma, Bizans ve Emevi dönemlerinden tepe kalıntıları.'),
  (222, '818', 'Luxor', 'Luksor', 'Karnak Temple', 'Karnak Tapınağı', 'A vast complex of temples and colossal columns.', 'Devasa sütunlarıyla tapınaklar kompleksi.'),
  (223, '818', 'Luxor', 'Luksor', 'Valley of the Kings', 'Krallar Vadisi', 'The royal burial ground of the pharaohs, including Tutankhamun.', 'Tutankhamon dahil firavunların kraliyet mezarlığı.'),
  (224, '818', 'Abu Simbel', 'Ebu Simbel', 'Abu Simbel Temples', 'Ebu Simbel Tapınakları', 'Rock temples guarded by four colossal statues of Ramses II.', 'II. Ramses''in dört devasa heykeliyle korunan kaya tapınakları.'),
  (225, '818', 'Cairo', 'Kahire', 'Egyptian Museum', 'Mısır Müzesi', 'A treasure house of ancient Egyptian artifacts.', 'Antik Mısır eserleriyle dolu bir hazine.'),
  (226, '818', 'Aswan', 'Asvan', 'Philae Temple', 'Philae Tapınağı', 'An island temple dedicated to the goddess Isis.', 'İsis''e adanmış ada tapınağı.'),
  (227, '504', 'Chefchaouen', 'Şefşavan', 'Chefchaouen Blue City', 'Şefşavan Mavi Şehir', 'A mountain town where every wall is painted blue.', 'Her duvarın maviye boyandığı dağ kasabası.'),
  (228, '504', 'Fes', 'Fes', 'Fes el-Bali Medina', 'Fes Medinası', 'The world''s largest car-free urban zone and a medieval maze.', 'Dünyanın araçsız en büyük kent alanı ve ortaçağ labirenti.'),
  (229, '504', 'Casablanca', 'Kazablanka', 'Hassan II Mosque', 'II. Hassan Camii', 'A massive mosque built on the Atlantic shoreline.', 'Atlas Okyanusu kıyısına inşa edilmiş dev cami.'),
  (230, '504', 'Merzouga', 'Merzouga', 'Erg Chebbi Dunes', 'Erg Chebbi Kum Tepeleri', 'Camel treks over towering Sahara dunes.', 'Sahra''nın yüksek kum tepelerinde deve gezisi.'),
  (231, '504', 'Ait Benhaddou', 'Ait Benhaddou', 'Aït Benhaddou', 'Aït Benhaddou', 'A fortified mud-brick village featured in many films.', 'Pek çok filmde görülen kerpiç surlu köy.'),
  (232, '784', 'Abu Dhabi', 'Abu Dabi', 'Sheikh Zayed Grand Mosque', 'Şeyh Zayid Camii', 'A white marble mosque with 82 domes.', '82 kubbeli beyaz mermer cami.'),
  (233, '784', 'Dubai', 'Dubai', 'Palm Jumeirah', 'Palm Jumeirah', 'A palm-shaped artificial island.', 'Palmiye şeklinde yapay ada.'),
  (234, '784', 'Dubai', 'Dubai', 'Dubai Frame', 'Dubai Çerçevesi', 'A giant picture frame with views of old and new Dubai.', 'Eski ve yeni Dubai''yi gösteren dev bir tablo çerçevesi.'),
  (235, '784', 'Dubai', 'Dubai', 'Dubai Mall Fountain', 'Dubai Mall Çeşmesi', 'A choreographed fountain show beneath the Burj Khalifa.', 'Burj Khalifa''nın dibinde koreografili çeşme gösterisi.'),
  (236, '512', 'Nizwa', 'Nizwa', 'Nizwa Fort', 'Nizwa Kalesi', 'A 17th-century fort with a round defensive tower.', 'Yuvarlak savunma kulesine sahip 17. yüzyıl kalesi.'),
  (237, '512', 'Wahiba Sands', 'Wahiba Kumulları', 'Wahiba Sands', 'Wahiba Kumulları', 'Golden dunes and Bedouin desert camps.', 'Altın kum tepeleri ve Bedevi çöl kampları.'),
  (238, '512', 'Muscat', 'Maskat', 'Mutrah Souq', 'Mutrah Çarşısı', 'A traditional market of frankincense and silver.', 'Tütsü ve gümüşle dolu geleneksel çarşı.'),
  (239, '634', 'Doha', 'Doha', 'Museum of Islamic Art', 'İslam Sanatı Müzesi', 'I. M. Pei''s geometric museum on the Doha waterfront.', 'I. M. Pei''nin Doha sahilindeki geometrik müzesi.'),
  (240, '634', 'Doha', 'Doha', 'The Pearl-Qatar', 'The Pearl-Qatar', 'A luxurious artificial island with Italian-style marinas.', 'İtalyan tarzı marinalarla lüks yapay ada.'),
  (241, '634', 'Doha', 'Doha', 'Katara Cultural Village', 'Katara Kültür Köyü', 'An amphitheatre, galleries and beach in a cultural district.', 'Amfi tiyatro, galeriler ve plajıyla kültür bölgesi.'),
  (242, '376', 'Jerusalem', 'Kudüs', 'Dome of the Rock', 'Kubbetüs-Sahre', 'A golden-domed shrine on the Temple Mount.', 'Mescid-i Aksa Haremi''nde altın kubbeli mabet.'),
  (243, '376', 'Jerusalem', 'Kudüs', 'Church of the Holy Sepulchre', 'Kutsal Kabir Kilisesi', 'A holy site for Christians, built over Jesus''s tomb.', 'İsa''nın kabri üzerine inşa edilmiş Hristiyanların kutsal mekânı.'),
  (244, '376', 'Masada', 'Masada', 'Masada Fortress', 'Masada Kalesi', 'A mountaintop fortress above the Dead Sea.', 'Lut Gölü''ne bakan dağ başı kalesi.'),
  (245, '376', 'Tel Aviv', 'Tel Aviv', 'Old Jaffa', 'Eski Yafa', 'An ancient port town with art galleries and sea views.', 'Sanat galerileri ve deniz manzaralı antik liman kenti.'),
  (246, '404', 'Nairobi', 'Nairobi', 'Nairobi National Park', 'Nairobi Milli Parkı', 'Lions and giraffes with a city skyline behind them.', 'Şehir silüetinin önünde aslanlar ve zürafalar.'),
  (247, '404', 'Amboseli', 'Amboseli', 'Amboseli National Park', 'Amboseli Milli Parkı', 'Elephants roaming beneath Mount Kilimanjaro.', 'Kilimanjaro Dağı''nın altında dolaşan filler.'),
  (248, '404', 'Lamu', 'Lamu', 'Lamu Old Town', 'Lamu Eski Şehir', 'A Swahili trading town of carved doors and narrow lanes.', 'Oyma kapıları ve dar sokaklarıyla Swahili ticaret kasabası.'),
  (249, '834', 'Arusha', 'Arusha', 'Mount Kilimanjaro', 'Kilimanjaro Dağı', 'Africa''s highest peak and the world''s tallest freestanding mountain.', 'Afrika''nın en yüksek zirvesi, dünyanın en yüksek bağımsız dağı.'),
  (250, '834', 'Ngorongoro', 'Ngorongoro', 'Ngorongoro Crater', 'Ngorongoro Krateri', 'A volcanic caldera teeming with wildlife.', 'Vahşi yaşamla dolu volkanik kaldera.'),
  (251, '834', 'Zanzibar', 'Zanzibar', 'Stone Town, Zanzibar', 'Stone Town (Zanzibar)', 'A historic Swahili port with spice markets and carved doors.', 'Baharat pazarları ve oyma kapılarıyla tarihi Swahili limanı.'),
  (252, '834', 'Zanzibar', 'Zanzibar', 'Nungwi Beach', 'Nungwi Plajı', 'White-sand beaches and calm turquoise water.', 'Beyaz kumsal ve sakin turkuaz deniz.'),
  (253, '710', 'Cape Town', 'Cape Town', 'Cape of Good Hope', 'Ümit Burnu', 'Rugged cliffs where two oceans seem to meet.', 'İki okyanusun buluştuğu görünen sarp kayalıklar.'),
  (254, '710', 'Cape Town', 'Cape Town', 'Boulders Beach Penguins', 'Boulders Plajı Penguenleri', 'African penguins on a granite-boulder beach.', 'Granit kayalı plajda Afrika penguenleri.'),
  (255, '710', 'Mpumalanga', 'Mpumalanga', 'Blyde River Canyon', 'Blyde River Kanyonu', 'One of the largest green canyons in the world.', 'Dünyanın en büyük yeşil kanyonlarından biri.'),
  (256, '710', 'Kruger', 'Kruger', 'Kruger National Park', 'Kruger Milli Parkı', 'Home to the Big Five on a classic safari.', 'Klasik safaride Büyük Beşli''ye ev sahipliği yapar.'),
  (257, '710', 'Johannesburg', 'Johannesburg', 'Apartheid Museum', 'Apartheid Müzesi', 'A powerful museum of South Africa''s history.', 'Güney Afrika tarihini anlatan güçlü bir müze.'),
  (258, '894', 'Lusaka', 'Lusaka', 'South Luangwa National Park', 'Güney Luangwa Milli Parkı', 'A birthplace of the walking safari with dense wildlife.', 'Yürüyüş safarisinin doğduğu, yoğun hayvan nüfuslu park.'),
  (259, '894', 'Livingstone', 'Livingstone', 'Devil''s Pool', 'Şeytan Havuzu', 'A natural rock pool on the very edge of Victoria Falls.', 'Victoria Şelalesi''nin tam kenarında doğal kaya havuzu.'),
  (260, '072', 'Chobe', 'Chobe', 'Chobe National Park', 'Chobe Milli Parkı', 'The largest elephant population in Africa.', 'Afrika''nın en büyük fil nüfusu.'),
  (261, '072', 'Makgadikgadi', 'Makgadikgadi', 'Makgadikgadi Salt Pans', 'Makgadikgadi Tuz Gölleri', 'A vast white salt flat under a wide sky.', 'Geniş bir gökyüzü altında uçsuz bucaksız beyaz tuz düzlüğü.'),
  (262, '516', 'Etosha', 'Etosha', 'Etosha National Park', 'Etosha Milli Parkı', 'Waterhole safaris around a giant salt pan.', 'Dev bir tuz gölü çevresinde su birikintisi safarisi.'),
  (263, '516', 'Sossusvlei', 'Sossusvlei', 'Deadvlei', 'Deadvlei', 'Dead trees against orange dunes and a white clay pan.', 'Turuncu kum tepeleri ve beyaz kil zemin üzerinde ölü ağaçlar.'),
  (264, '516', 'Swakopmund', 'Swakopmund', 'Skeleton Coast', 'İskelet Kıyısı', 'Shipwrecks and seal colonies along a foggy desert coast.', 'Sisli çöl kıyısında gemi enkazları ve fok kolonileri.'),
  (265, '392', 'Tokyo', 'Tokyo', 'Senso-ji Temple', 'Sensō-ji Tapınağı', 'Tokyo''s oldest temple, reached through a lantern-lit gate.', 'Fener ışıklı kapıdan girilen Tokyo''nun en eski tapınağı.'),
  (266, '392', 'Tokyo', 'Tokyo', 'Tokyo Skytree', 'Tokyo Skytree', 'A 634-metre broadcasting tower with panoramic views.', 'Panoramik manzaralı 634 metrelik yayın kulesi.'),
  (267, '392', 'Kyoto', 'Kyoto', 'Kinkaku-ji (Golden Pavilion)', 'Kinkaku-ji (Altın Köşk)', 'A gold-leaf covered temple reflected in a pond.', 'Göletin sularına yansıyan altın kaplama tapınak.'),
  (268, '392', 'Kyoto', 'Kyoto', 'Arashiyama Bamboo Grove', 'Arashiyama Bambu Ormanı', 'A towering path through swaying bamboo.', 'Sallanan bambuların arasında yükselen patika.'),
  (269, '392', 'Osaka', 'Osaka', 'Osaka Castle', 'Osaka Kalesi', 'A grand castle surrounded by moats and cherry trees.', 'Hendekler ve kiraz ağaçlarıyla çevrili görkemli kale.'),
  (270, '392', 'Nara', 'Nara', 'Nara Deer Park', 'Nara Geyik Parkı', 'Friendly wild deer roaming among ancient temples.', 'Antik tapınaklar arasında dolaşan sevimli yabani geyikler.'),
  (271, '392', 'Hiroshima', 'Hiroşima', 'Itsukushima Shrine', 'Itsukushima Tapınağı', 'A torii gate that appears to float on the sea.', 'Denizde yüzüyormuş gibi duran torii kapısı.'),
  (272, '156', 'Beijing', 'Pekin', 'Forbidden City', 'Yasak Şehir', 'The vast imperial palace of China''s emperors.', 'Çin imparatorlarının geniş saray kompleksi.'),
  (273, '156', 'Beijing', 'Pekin', 'Temple of Heaven', 'Cennet Tapınağı', 'A circular temple complex for imperial ceremonies.', 'İmparatorluk törenleri için dairesel tapınak kompleksi.'),
  (274, '156', 'Xi''an', 'Xi''an', 'Terracotta Army', 'Terakota Ordusu', 'Thousands of life-size clay soldiers guarding an emperor''s tomb.', 'Bir imparatorun mezarını koruyan binlerce gerçek boyutlu kil asker.'),
  (275, '156', 'Zhangjiajie', 'Zhangjiajie', 'Zhangjiajie Avatar Mountains', 'Zhangjiajie Avatar Dağları', 'Towering sandstone pillars shrouded in mist.', 'Sisle sarılı yüksek kumtaşı sütunlar.'),
  (276, '156', 'Guilin', 'Guilin', 'Li River Karst Landscape', 'Li Nehri Karst Manzarası', 'Limestone peaks rising from a tranquil river.', 'Sakin bir nehirden yükselen kireçtaşı tepeleri.'),
  (277, '156', 'Chengdu', 'Chengdu', 'Giant Panda Base', 'Dev Panda Üssü', 'See giant pandas in a protected bamboo habitat.', 'Korunan bambu ortamında dev pandaları görün.'),
  (278, '356', 'Delhi', 'Delhi', 'Red Fort', 'Kızıl Kale', 'A Mughal fortress of red sandstone.', 'Kırmızı kumtaşından Babür kalesi.'),
  (279, '356', 'Delhi', 'Delhi', 'India Gate', 'Hindistan Kapısı', 'A war memorial arch at the heart of New Delhi.', 'Yeni Delhi''nin kalbinde bir savaş anıtı kemeri.'),
  (280, '356', 'Varanasi', 'Varanasi', 'Varanasi Ghats', 'Varanasi Ghatları', 'Dawn rituals along the sacred Ganges.', 'Kutsal Ganj Nehri kıyısında şafak ritüelleri.'),
  (281, '356', 'Udaipur', 'Udaipur', 'City Palace, Udaipur', 'Udaipur Şehir Sarayı', 'A palace complex overlooking Lake Pichola.', 'Pichola Gölü''ne bakan saray kompleksi.'),
  (282, '356', 'Kerala', 'Kerala', 'Kerala Backwaters', 'Kerala Backwaters', 'Houseboat cruises through palm-fringed lagoons.', 'Palmiyelerle çevrili lagünlerde tekne turu.'),
  (283, '356', 'Amritsar', 'Amritsar', 'Golden Temple', 'Altın Tapınak', 'The holiest Sikh shrine, gleaming above a sacred pool.', 'Kutsal havuzun üzerinde parlayan Sih''lerin en kutsal tapınağı.'),
  (284, '524', 'Pokhara', 'Pokhara', 'Phewa Lake', 'Phewa Gölü', 'A lake mirroring the Annapurna range.', 'Annapurna sıradağlarını yansıtan göl.'),
  (285, '524', 'Kathmandu', 'Kathmandu', 'Boudhanath Stupa', 'Boudhanath Stupası', 'One of the largest spherical stupas in the world.', 'Dünyanın en büyük küresel stupalarından biri.'),
  (286, '524', 'Kathmandu', 'Kathmandu', 'Swayambhunath (Monkey Temple)', 'Swayambhunath (Maymun Tapınağı)', 'A hilltop stupa with prayer flags and playful monkeys.', 'Dua bayrakları ve oyuncu maymunlarla tepe stupası.'),
  (287, '144', 'Kandy', 'Kandy', 'Temple of the Tooth', 'Diş Tapınağı', 'A sacred temple housing a relic of the Buddha.', 'Buda''nın kutsal bir kalıntısını barındıran tapınak.'),
  (288, '144', 'Ella', 'Ella', 'Nine Arch Bridge', 'Dokuz Kemerli Köprü', 'A colonial-era railway bridge surrounded by jungle.', 'Ormanlarla çevrili sömürge dönemi demiryolu köprüsü.'),
  (289, '144', 'Galle', 'Galle', 'Galle Fort', 'Galle Kalesi', 'A Dutch colonial fort on the southern coast.', 'Güney kıyısında Hollanda sömürge kalesi.'),
  (290, '360', 'Yogyakarta', 'Yogyakarta', 'Borobudur Temple', 'Borobudur Tapınağı', 'The world''s largest Buddhist temple.', 'Dünyanın en büyük Budist tapınağı.'),
  (291, '360', 'Yogyakarta', 'Yogyakarta', 'Prambanan Temple', 'Prambanan Tapınağı', 'A soaring 9th-century Hindu temple complex.', '9. yüzyıldan kalma yükselen Hindu tapınak kompleksi.'),
  (292, '360', 'Bali', 'Bali', 'Uluwatu Temple', 'Uluwatu Tapınağı', 'A sea temple perched on a cliff high above the Indian Ocean.', 'Hint Okyanusu''nun üzerinde uçurum başında deniz tapınağı.'),
  (293, '360', 'Komodo', 'Komodo', 'Komodo National Park', 'Komodo Milli Parkı', 'The only home of the Komodo dragon.', 'Komodo ejderinin tek yaşam alanı.'),
  (294, '360', 'East Java', 'Doğu Java', 'Mount Bromo', 'Bromo Yanardağı', 'A smoking volcano seen over a sea of clouds at dawn.', 'Şafakta bulut denizi üzerinde tüten yanardağ.'),
  (295, '764', 'Bangkok', 'Bangkok', 'Grand Palace', 'Büyük Saray', 'The dazzling former royal residence in Bangkok.', 'Bangkok''taki göz alıcı eski kraliyet sarayı.'),
  (296, '764', 'Chiang Mai', 'Chiang Mai', 'Doi Suthep', 'Doi Suthep', 'A golden temple on a mountain above Chiang Mai.', 'Chiang Mai''nin üzerindeki dağda altın tapınak.'),
  (297, '764', 'Krabi', 'Krabi', 'Railay Beach', 'Railay Plajı', 'A beach with towering limestone cliffs, reachable only by boat.', 'Sadece tekneyle ulaşılan, yüksek kireçtaşı kayalıkları olan plaj.'),
  (298, '764', 'Phuket', 'Phuket', 'Phi Phi Islands', 'Phi Phi Adaları', 'Clear lagoons and cliffs from ''The Beach''.', '''The Beach'' filminden bilinen berrak lagünler ve kayalıklar.'),
  (299, '764', 'Ayutthaya', 'Ayutthaya', 'Ayutthaya Historical Park', 'Ayutthaya Tarihi Parkı', 'Ruined temples of Siam''s former capital.', 'Siyam''ın eski başkentinin yıkık tapınakları.'),
  (300, '704', 'Hoi An', 'Hoi An', 'Hoi An Ancient Town', 'Hoi An Antik Kenti', 'A lantern-lit trading port with yellow shophouses.', 'Fener ışıklı, sarı dükkân evleriyle ticaret limanı.'),
  (301, '704', 'Hanoi', 'Hanoi', 'Hoan Kiem Lake', 'Hoan Kiem Gölü', 'A tranquil lake in the middle of Hanoi''s Old Quarter.', 'Hanoi Eski Mahalle''nin ortasında sakin bir göl.'),
  (302, '704', 'Da Nang', 'Da Nang', 'Golden Bridge (Ba Na Hills)', 'Altın Köprü (Ba Na Tepeleri)', 'A footbridge held aloft by giant stone hands.', 'Dev taş ellerin tuttuğu yaya köprüsü.'),
  (303, '704', 'Sapa', 'Sapa', 'Sapa Rice Terraces', 'Sapa Pirinç Terasları', 'Layered terraces carved into misty mountains.', 'Sisli dağlara oyulmuş katmanlı teraslar.'),
  (304, '704', 'Ninh Binh', 'Ninh Binh', 'Trang An Landscape', 'Trang An Manzarası', 'Boat rides through caves beneath limestone karsts.', 'Kireçtaşı tepeleri altında mağaralardan tekne gezisi.'),
  (305, '116', 'Siem Reap', 'Siem Reap', 'Bayon Temple', 'Bayon Tapınağı', 'A temple of smiling stone faces in Angkor Thom.', 'Angkor Thom''da gülümseyen taş yüzlerden oluşan tapınak.'),
  (306, '116', 'Siem Reap', 'Siem Reap', 'Ta Prohm', 'Ta Prohm', 'A temple embraced by giant tree roots.', 'Dev ağaç köklerinin sardığı tapınak.'),
  (307, '116', 'Phnom Penh', 'Phnom Penh', 'Royal Palace, Phnom Penh', 'Phnom Penh Kraliyet Sarayı', 'A golden-spired palace on the Mekong riverfront.', 'Mekong kıyısında altın külahlı saray.'),
  (308, '410', 'Seoul', 'Seul', 'N Seoul Tower', 'N Seul Kulesi', 'A hilltop tower with sweeping city views.', 'Şehre hâkim tepe kulesi.'),
  (309, '410', 'Seoul', 'Seul', 'Bukchon Hanok Village', 'Bukchon Hanok Köyü', 'Traditional Korean houses among modern Seoul.', 'Modern Seul''ün ortasında geleneksel Kore evleri.'),
  (310, '410', 'Busan', 'Busan', 'Gamcheon Culture Village', 'Gamcheon Kültür Köyü', 'A hillside of pastel houses and street art.', 'Pastel evler ve sokak sanatıyla dolu yamaç.'),
  (311, '410', 'Jeju', 'Jeju', 'Seongsan Ilchulbong', 'Seongsan Ilchulbong', 'A volcanic crater on Jeju Island best seen at sunrise.', 'Jeju Adası''nda gün doğumunda izlenen volkanik krater.'),
  (312, '462', 'Male', 'Malé', 'Hulhumalé Beach', 'Hulhumalé Plajı', 'A calm beach close to the capital and the airport.', 'Başkent ve havalimanına yakın sakin plaj.'),
  (313, '462', 'Baa Atoll', 'Baa Atolü', 'Baa Atoll (Hanifaru Bay)', 'Baa Atolü (Hanifaru Koyu)', 'A UNESCO biosphere reserve known for manta ray swarms.', 'Manta vatozu sürüleriyle ünlü UNESCO biyosfer rezervi.'),
  (314, '462', 'Ari Atoll', 'Ari Atolü', 'Ari Atoll Whale Sharks', 'Ari Atolü Balina Köpekbalıkları', 'Snorkel alongside gentle whale sharks.', 'Sakin balina köpekbalıklarıyla birlikte şnorkelle yüzün.'),
  (315, '702', 'Singapore', 'Singapur', 'Gardens by the Bay', 'Gardens by the Bay', 'Giant Supertrees and glass conservatories.', 'Dev Süperağaçlar ve cam seralar.'),
  (316, '702', 'Singapore', 'Singapur', 'Merlion Park', 'Merlion Parkı', 'The half-lion, half-fish symbol of Singapore.', 'Singapur''un yarı aslan yarı balık sembolü.'),
  (317, '702', 'Singapore', 'Singapur', 'Sentosa Island', 'Sentosa Adası', 'A resort island of beaches and attractions.', 'Plajlar ve eğlence alanlarıyla tatil adası.'),
  (318, '458', 'Kuala Lumpur', 'Kuala Lumpur', 'Batu Caves', 'Batu Mağaraları', 'A limestone hill with a giant golden statue and rainbow stairs.', 'Dev altın heykel ve gökkuşağı merdivenleriyle kireçtaşı tepesi.'),
  (319, '458', 'Penang', 'Penang', 'George Town Street Art', 'George Town Sokak Sanatı', 'Murals and heritage shophouses in a UNESCO city.', 'UNESCO kentinde duvar resimleri ve tarihi dükkân evleri.'),
  (320, '458', 'Langkawi', 'Langkawi', 'Langkawi Sky Bridge', 'Langkawi Gökyüzü Köprüsü', 'A curved bridge hanging high above the rainforest.', 'Yağmur ormanının üzerinde asılı kavisli köprü.'),
  (321, '608', 'Cebu', 'Cebu', 'Kawasan Falls', 'Kawasan Şelaleleri', 'Turquoise cascades for canyoneering and swimming.', 'Kanyoning ve yüzme için turkuaz şelaleler.'),
  (322, '608', 'Bohol', 'Bohol', 'Chocolate Hills', 'Çikolata Tepeleri', 'Over a thousand grass-covered hills that turn brown in dry season.', 'Kurak mevsimde kahverengiye dönen bin kadar çimenli tepe.'),
  (323, '608', 'Boracay', 'Boracay', 'White Beach, Boracay', 'Boracay Beyaz Plaj', 'A powdery white sand beach famed for its sunsets.', 'Gün batımıyla ünlü pudra gibi beyaz kumsal.'),
  (324, '036', 'Uluru', 'Uluru', 'Uluru (Ayers Rock)', 'Uluru (Ayers Kayası)', 'A sacred sandstone monolith that glows red at sunset.', 'Gün batımında kızaran kutsal kumtaşı monolit.'),
  (325, '036', 'Melbourne', 'Melbourne', 'Great Ocean Road', 'Great Ocean Road', 'A coastal drive past the Twelve Apostles.', 'On İki Havari kayalıklarının yanından kıyı yolu.'),
  (326, '036', 'Sydney', 'Sidney', 'Bondi Beach', 'Bondi Plajı', 'Australia''s most famous surf beach.', 'Avustralya''nın en ünlü sörf plajı.'),
  (327, '036', 'Tasmania', 'Tazmanya', 'Cradle Mountain', 'Cradle Dağı', 'A rugged alpine park with wombats and glacial lakes.', 'Vombatlar ve buzul gölleriyle sarp dağ parkı.'),
  (328, '554', 'Queenstown', 'Queenstown', 'Queenstown Skyline', 'Queenstown Skyline', 'Adventure capital with views over Lake Wakatipu.', 'Wakatipu Gölü manzaralı macera başkenti.'),
  (329, '554', 'Rotorua', 'Rotorua', 'Hobbiton Movie Set', 'Hobbiton Film Seti', 'The Shire from The Lord of the Rings.', 'Yüzüklerin Efendisi''nin Shire''ı.'),
  (330, '554', 'Fiordland', 'Fiordland', 'Tongariro Alpine Crossing', 'Tongariro Alpine Geçidi', 'A volcanic day-hike past emerald lakes.', 'Zümrüt göllerin yanından volkanik bir günübirlik yürüyüş.'),
  (331, '554', 'Wanaka', 'Wanaka', 'Wanaka Tree', 'Wanaka Ağacı', 'A lone willow standing in the lake at sunrise.', 'Gün doğumunda gölün içinde duran yalnız bir söğüt.'),
  (332, '242', 'Nadi', 'Nadi', 'Sri Siva Subramaniya Temple', 'Sri Siva Subramaniya Tapınağı', 'A colorful Hindu temple, the largest in the Southern Hemisphere.', 'Güney Yarımküre''nin en büyük, renkli Hindu tapınağı.'),
  (333, '242', 'Mamanuca', 'Mamanuca', 'Mamanuca Islands', 'Mamanuca Adaları', 'Sandbanks and snorkeling in calm lagoons.', 'Sakin lagünlerde kumsallar ve şnorkel.'),
  (334, '840', 'New York', 'New York', 'Times Square', 'Times Square', 'The neon crossroads of the world.', 'Dünyanın neon yol ayrımı.'),
  (335, '840', 'New York', 'New York', 'Central Park', 'Central Park', 'An 843-acre green oasis in Manhattan.', 'Manhattan''da 843 dönümlük yeşil vaha.'),
  (336, '840', 'New York', 'New York', 'Empire State Building', 'Empire State Binası', 'An Art Deco skyscraper with skyline views.', 'Şehir manzaralı Art Deco gökdelen.'),
  (337, '840', 'Washington, D.C.', 'Washington, D.C.', 'Lincoln Memorial', 'Lincoln Anıtı', 'A marble memorial at the end of the National Mall.', 'National Mall''in sonunda mermer anıt.'),
  (338, '840', 'Wyoming', 'Wyoming', 'Yellowstone National Park', 'Yellowstone Milli Parkı', 'Geysers, hot springs and bison herds.', 'Gayzerler, kaplıcalar ve bizon sürüleri.'),
  (339, '840', 'California', 'Kaliforniya', 'Yosemite National Park', 'Yosemite Milli Parkı', 'Granite cliffs and giant sequoias.', 'Granit kayalıklar ve dev sekoyalar.'),
  (340, '840', 'Nevada', 'Nevada', 'Las Vegas Strip', 'Las Vegas Strip', 'A dazzling avenue of casinos and shows.', 'Kumarhaneler ve gösterilerle dolu göz alıcı bulvar.'),
  (341, '840', 'Utah', 'Utah', 'Antelope Canyon', 'Antelope Kanyonu', 'A slot canyon with glowing sandstone waves.', 'Parlayan kumtaşı dalgalarıyla dar bir kanyon.'),
  (342, '124', 'Alberta', 'Alberta', 'Banff National Park', 'Banff Milli Parkı', 'Turquoise lakes under the Canadian Rockies.', 'Kanada Kayalık Dağları altında turkuaz göller.'),
  (343, '124', 'Alberta', 'Alberta', 'Lake Louise', 'Lake Louise', 'A glacial lake with a mountain amphitheatre.', 'Dağ amfisiyle çevrili buzul gölü.'),
  (344, '124', 'Toronto', 'Toronto', 'CN Tower', 'CN Kulesi', 'A 553-metre tower with a glass floor.', 'Cam zeminli 553 metrelik kule.'),
  (345, '124', 'Quebec City', 'Quebec', 'Old Quebec', 'Eski Quebec', 'A walled French-colonial city with a castle hotel.', 'Şato otelli surlu Fransız sömürge şehri.'),
  (346, '124', 'Churchill', 'Churchill', 'Churchill Polar Bears', 'Churchill Kutup Ayıları', 'Polar bear watching on Hudson Bay.', 'Hudson Körfezi''nde kutup ayısı gözlemi.'),
  (347, '484', 'Mexico City', 'Meksiko', 'Teotihuacan', 'Teotihuacan', 'The Pyramids of the Sun and the Moon.', 'Güneş ve Ay Piramitleri.'),
  (348, '484', 'Tulum', 'Tulum', 'Tulum Ruins', 'Tulum Kalıntıları', 'A Maya port city above Caribbean cliffs.', 'Karayip uçurumları üzerinde Maya liman kenti.'),
  (349, '484', 'Cancun', 'Cancun', 'Isla Mujeres', 'Isla Mujeres', 'A relaxed Caribbean island close to Cancun.', 'Cancun''a yakın sakin bir Karayip adası.'),
  (350, '484', 'Guanajuato', 'Guanajuato', 'Guanajuato Colorful Streets', 'Guanajuato Renkli Sokaklar', 'Pastel colonial houses on hillside alleys.', 'Yamaç sokaklarında pastel sömürge evleri.'),
  (351, '604', 'Cusco', 'Cusco', 'Rainbow Mountain', 'Gökkuşağı Dağı', 'A striped mountain at 5,000 metres.', '5000 metrede çizgili bir dağ.'),
  (352, '604', 'Cusco', 'Cusco', 'Sacred Valley', 'Kutsal Vadi', 'Inca ruins and terraces in the Andes.', 'And Dağları''nda İnka kalıntıları ve terasları.'),
  (353, '604', 'Lake Titicaca', 'Titicaca Gölü', 'Uros Floating Islands', 'Uros Yüzen Adaları', 'Reed islands on Lake Titicaca.', 'Titicaca Gölü''nde kamıştan adalar.'),
  (354, '604', 'Nazca', 'Nazca', 'Nazca Lines', 'Nazca Çizgileri', 'Giant desert geoglyphs best seen from the air.', 'Havadan en iyi görülen dev çöl geoglifleri.'),
  (355, '076', 'Foz do Iguacu', 'Foz do Iguaçu', 'Iguazu Falls', 'Iguazu Şelaleleri', 'Hundreds of waterfalls in the rainforest.', 'Yağmur ormanında yüzlerce şelale.'),
  (356, '076', 'Rio de Janeiro', 'Rio de Janeiro', 'Copacabana Beach', 'Copacabana Plajı', 'A famous curved beach of Rio.', 'Rio''nun ünlü kavisli plajı.'),
  (357, '076', 'Rio de Janeiro', 'Rio de Janeiro', 'Sugarloaf Mountain', 'Şeker Somunu Dağı', 'A cable car ride to sweeping views of Rio.', 'Rio manzarası için teleferik yolculuğu.'),
  (358, '076', 'Lencois Maranhenses', 'Lençóis Maranhenses', 'Lençóis Maranhenses', 'Lençóis Maranhenses', 'White dunes filled with turquoise rain lagoons.', 'Turkuaz yağmur lagünleriyle dolu beyaz kum tepeleri.'),
  (359, '032', 'El Calafate', 'El Calafate', 'Perito Moreno Glacier', 'Perito Moreno Buzulu', 'An advancing glacier that calves into a lake.', 'Göle buz bırakan ilerleyen buzul.'),
  (360, '032', 'Ushuaia', 'Ushuaia', 'Ushuaia End of the World', 'Ushuaia Dünyanın Sonu', 'The southernmost city on Earth.', 'Dünyanın en güneydeki şehri.'),
  (361, '032', 'Mendoza', 'Mendoza', 'Mendoza Vineyards', 'Mendoza Bağları', 'Wine tasting beneath the Andes.', 'And Dağları altında şarap tadımı.'),
  (362, '032', 'Buenos Aires', 'Buenos Aires', 'Recoleta Cemetery', 'Recoleta Mezarlığı', 'An ornate city of marble mausoleums.', 'Süslü mermer mozolelerden oluşan şehir.'),
  (363, '152', 'Torres del Paine', 'Torres del Paine', 'Torres del Paine', 'Torres del Paine', 'Granite spires and glaciers in Patagonia.', 'Patagonya''da granit kuleler ve buzullar.'),
  (364, '152', 'Easter Island', 'Paskalya Adası', 'Moai Statues, Easter Island', 'Moai Heykelleri, Paskalya Adası', 'Monumental stone heads on a remote island.', 'Uzak bir adada anıtsal taş başlar.'),
  (365, '152', 'Valparaiso', 'Valparaíso', 'Valparaíso Hills', 'Valparaíso Tepeleri', 'A port city of murals and funiculars.', 'Duvar resimleri ve fünikülerlerle liman kenti.'),
  (366, '192', 'Havana', 'Havana', 'El Capitolio', 'El Capitolio', 'Havana''s grand domed capitol building.', 'Havana''nın görkemli kubbeli kapitol binası.'),
  (367, '192', 'Havana', 'Havana', 'Malecón', 'Malecón', 'A seaside promenade, the heart of Havana''s social life.', 'Havana''nın sosyal yaşamının kalbi olan sahil yürüyüş yolu.'),
  (368, '192', 'Vinales', 'Viñales', 'Viñales Valley', 'Viñales Vadisi', 'Limestone mogotes and tobacco farms.', 'Kireçtaşı mogotelar ve tütün çiftlikleri.'),
  (369, '192', 'Trinidad', 'Trinidad', 'Trinidad Old Town', 'Trinidad Eski Şehir', 'A cobblestone colonial town frozen in time.', 'Zamanda donmuş arnavut kaldırımlı sömürge kasabası.'),
  (370, '010', 'Antarctic Peninsula', 'Antarktika Yarımadası', 'Lemaire Channel', 'Lemaire Kanalı', 'A narrow channel nicknamed ''Kodak Gap''.', '''Kodak Gap'' lakaplı dar bir kanal.'),
  (371, '010', 'Antarctic Peninsula', 'Antarktika Yarımadası', 'Deception Island', 'Deception Adası', 'A flooded volcanic caldera you can sail into.', 'İçine girilebilen sular altındaki volkanik kaldera.'),
  (372, '170', 'Cartagena', 'Cartagena', 'Cartagena Walled City', 'Cartagena Surlu Şehir', 'A colorful colonial walled port on the Caribbean.', 'Karayipler''de renkli sömürge surlu liman şehri.'),
  (373, '170', 'Guatape', 'Guatapé', 'Piedra del Peñol', 'Piedra del Peñol', 'A giant rock with a 740-step staircase.', '740 basamaklı merdiveniyle dev kaya.'),
  (374, '170', 'Salento', 'Salento', 'Cocora Valley', 'Cocora Vadisi', 'The world''s tallest palm trees in misty hills.', 'Sisli tepelerde dünyanın en uzun palmiye ağaçları.'),
  (375, '218', 'Galapagos', 'Galapagos', 'Galápagos Islands', 'Galápagos Adaları', 'Darwin''s wildlife laboratory of unique species.', 'Darwin''in eşsiz türlerin yaşadığı doğa laboratuvarı.'),
  (376, '218', 'Quito', 'Quito', 'Quito Old Town', 'Quito Eski Şehir', 'A UNESCO historic center in the Andes.', 'And Dağları''nda UNESCO tarihi merkez.'),
  (377, '068', 'Uyuni', 'Uyuni', 'Salar de Uyuni', 'Uyuni Tuz Gölü', 'The world''s largest salt flat, a giant mirror after rain.', 'Yağmurdan sonra dev aynaya dönen dünyanın en büyük tuz düzlüğü.'),
  (378, '068', 'La Paz', 'La Paz', 'Valle de la Luna (La Paz)', 'Ay Vadisi (La Paz)', 'Eroded clay spires near the highest capital.', 'En yüksek başkentin yakınında aşınmış kil kuleler.'),
  (379, '858', 'Colonia del Sacramento', 'Colonia del Sacramento', 'Colonia del Sacramento', 'Colonia del Sacramento', 'A quiet colonial town with a lighthouse and cobblestones.', 'Fener ve arnavut kaldırımlarıyla sakin bir sömürge kasabası.'),
  (380, '858', 'Punta del Este', 'Punta del Este', 'La Mano de Punta del Este', 'Punta del Este Eli', 'A giant sculpture of a hand rising from the sand.', 'Kumdan yükselen dev el heykeli.'),
  (381, '188', 'La Fortuna', 'La Fortuna', 'Arenal Volcano', 'Arenal Yanardağı', 'A perfectly cone-shaped volcano with hot springs.', 'Kaplıcalarıyla birlikte mükemmel konik yanardağ.'),
  (382, '188', 'Monteverde', 'Monteverde', 'Monteverde Cloud Forest', 'Monteverde Bulut Ormanı', 'Hanging bridges through misty cloud forest.', 'Sisli bulut ormanında asma köprüler.'),
  (383, '388', 'Ocho Rios', 'Ocho Rios', 'Dunn''s River Falls', 'Dunn''s River Şelaleri', 'A terraced waterfall you can climb.', 'Tırmanılabilen basamaklı şelale.'),
  (384, '388', 'Negril', 'Negril', 'Seven Mile Beach, Negril', 'Negril Yedi Mil Plajı', 'A long beach known for cliff sunsets.', 'Uçurum gün batımlarıyla ünlü uzun plaj.'),
  (385, '044', 'Exuma', 'Exuma', 'Swimming Pigs, Exuma', 'Yüzen Domuzlar, Exuma', 'Pigs paddling in clear Bahamian water.', 'Berrak Bahama sularında yüzen domuzlar.'),
  (386, '044', 'Nassau', 'Nassau', 'Paradise Island', 'Paradise Island', 'A resort island with white sand and aqua water.', 'Beyaz kum ve turkuaz suyla tatil adası.'),
  (387, '214', 'Punta Cana', 'Punta Cana', 'Punta Cana Beaches', 'Punta Cana Plajları', 'Palm-lined white sand beaches on the Caribbean.', 'Karayipler''de palmiye kenarlı beyaz kumsallar.'),
  (388, '214', 'Samana', 'Samaná', 'Salto El Limón', 'Salto El Limón', 'A jungle waterfall reached on horseback.', 'At sırtıyla ulaşılan orman şelalesi.'),
  (389, '591', 'Panama City', 'Panama Şehri', 'Panama Canal', 'Panama Kanalı', 'Watch ships pass through the Miraflores Locks.', 'Miraflores Kilitlerinden geçen gemileri izleyin.'),
  (390, '591', 'Bocas del Toro', 'Bocas del Toro', 'San Blas Islands', 'San Blas Adaları', 'Palm-topped sandbars in the Caribbean.', 'Karayipler''de palmiyeli kum adacıkları.'),
  (391, '320', 'Tikal', 'Tikal', 'Tikal', 'Tikal', 'Maya temples rising above the jungle canopy.', 'Orman çatısının üzerinde yükselen Maya tapınakları.'),
  (392, '320', 'Antigua Guatemala', 'Antigua Guatemala', 'Antigua Guatemala', 'Antigua Guatemala', 'A colonial city beneath three volcanoes.', 'Üç yanardağın altında sömürge şehri.'),
  (393, '084', 'San Pedro', 'San Pedro', 'Great Blue Hole', 'Büyük Mavi Delik', 'A giant marine sinkhole popular with divers.', 'Dalgıçların gözdesi dev deniz çukuru.'),
  (394, '788', 'Tunis', 'Tunus', 'Carthage Ruins', 'Kartaca Kalıntıları', 'The ruins of the ancient Phoenician-Roman city.', 'Antik Fenike-Roma şehrinin kalıntıları.'),
  (395, '788', 'Sidi Bou Said', 'Sidi Bou Said', 'Sidi Bou Said', 'Sidi Bou Said', 'A blue-and-white clifftop village over the Mediterranean.', 'Akdeniz''e bakan mavi-beyaz uçurum köyü.'),
  (396, '788', 'El Jem', 'El Cem', 'El Jem Amphitheatre', 'El Cem Amfitiyatrosu', 'One of the best-preserved Roman amphitheatres.', 'En iyi korunmuş Roma amfitiyatrolarından biri.'),
  (397, '231', 'Lalibela', 'Lalibela', 'Rock-Hewn Churches of Lalibela', 'Lalibela Kaya Kiliseleri', 'Eleven medieval churches carved out of solid rock.', 'Tek parça kayadan oyulmuş on bir ortaçağ kilisesi.'),
  (398, '231', 'Danakil', 'Danakil', 'Danakil Depression', 'Danakil Çukurluğu', 'A surreal, colorful volcanic desert.', 'Gerçeküstü, renkli volkanik çöl.'),
  (399, '450', 'Morondava', 'Morondava', 'Avenue of the Baobabs', 'Baobablar Yolu', 'Giant baobabs lining a dirt road at sunset.', 'Gün batımında toprak yol boyunca uzanan dev baobablar.'),
  (400, '450', 'Tsingy', 'Tsingy', 'Tsingy de Bemaraha', 'Bemaraha Tsingy', 'A forest of razor-sharp limestone pinnacles.', 'Jilet gibi keskin kireçtaşı sivrilerden oluşan orman.'),
  (401, '480', 'Chamarel', 'Chamarel', 'Seven Colored Earths', 'Yedi Renkli Toprak', 'Dunes in seven natural shades.', 'Doğal yedi tonda kum tepeleri.'),
  (402, '480', 'Le Morne', 'Le Morne', 'Le Morne Brabant', 'Le Morne Brabant', 'A dramatic mountain and lagoon on the southwest tip.', 'Güneybatı ucunda dramatik dağ ve lagün.'),
  (403, '690', 'Praslin', 'Praslin', 'Anse Lazio', 'Anse Lazio', 'A granite-framed beach often ranked among the world''s best.', 'Dünyanın en iyileri arasında gösterilen granit çerçeveli plaj.'),
  (404, '690', 'La Digue', 'La Digue', 'Anse Source d''Argent', 'Anse Source d''Argent', 'Pink-tinged sand between giant granite boulders.', 'Dev granit kayalar arasında pembemsi kum.'),
  (405, '646', 'Volcanoes', 'Volkanlar', 'Volcanoes National Park (Gorillas)', 'Volkanlar Milli Parkı (Goriller)', 'Trek to meet endangered mountain gorillas.', 'Nesli tükenmekte olan dağ gorilleriyle tanışmak için trekking.'),
  (406, '800', 'Bwindi', 'Bwindi', 'Bwindi Impenetrable Forest', 'Bwindi Geçilmez Ormanı', 'Home to about half of the world''s mountain gorillas.', 'Dünyadaki dağ gorillerinin yaklaşık yarısına ev sahipliği yapar.'),
  (407, '800', 'Jinja', 'Jinja', 'Source of the Nile', 'Nil''in Kaynağı', 'Where the White Nile begins its journey to the sea.', 'Beyaz Nil''in denize yolculuğuna başladığı yer.'),
  (408, '288', 'Cape Coast', 'Cape Coast', 'Cape Coast Castle', 'Cape Coast Kalesi', 'A fortress and memorial of the transatlantic slave trade.', 'Atlantik köle ticaretinin kalesi ve anıtı.'),
  (409, '686', 'Dakar', 'Dakar', 'Lake Retba (Pink Lake)', 'Retba Gölü (Pembe Göl)', 'A rose-colored lake rich in salt.', 'Tuz oranı yüksek, gül rengi göl.'),
  (410, '686', 'Dakar', 'Dakar', 'Goree Island', 'Gorée Adası', 'A small island memorializing the slave trade.', 'Köle ticaretini anan küçük bir ada.'),
  (411, '012', 'Algiers', 'Cezayir', 'Casbah of Algiers', 'Cezayir Kasbahı', 'A hillside medina overlooking the Mediterranean.', 'Akdeniz''e bakan yamaç medinası.'),
  (412, '012', 'Djanet', 'Djanet', 'Tassili n''Ajjer', 'Tassili n''Ajjer', 'A Saharan plateau of ancient rock art and rock forests.', 'Antik kaya sanatı ve kaya ormanlarıyla Sahra platosu.'),
  (413, '422', 'Baalbek', 'Baalbek', 'Baalbek Roman Temples', 'Baalbek Roma Tapınakları', 'Monumental temples to Jupiter and Bacchus.', 'Jüpiter ve Bacchus''a adanmış anıtsal tapınaklar.'),
  (414, '422', 'Beirut', 'Beyrut', 'Raouche Rocks (Pigeon Rocks)', 'Ravşe Kayalıkları (Güvercin Kayalığı)', 'Sea stacks standing off Beirut''s coast.', 'Beyrut kıyısında deniz kayalıkları.'),
  (415, '422', 'Jeita', 'Ceyta', 'Jeita Grotto', 'Ceyta Mağarası', 'A spectacular limestone cave system with a river.', 'Nehirli, muhteşem kireçtaşı mağara sistemi.'),
  (416, '682', 'Al Ula', 'Al Ula', 'Hegra (Mada''in Salih)', 'Hegra (Medain Salih)', 'Nabataean tombs carved into desert sandstone.', 'Çöl kumtaşına oyulmuş Nabatî mezarları.'),
  (417, '682', 'Jeddah', 'Cidde', 'Al-Balad Old Town', 'Al-Balad Eski Şehir', 'A coral-stone old town on the Red Sea coast.', 'Kızıldeniz kıyısında mercan taşından eski şehir.'),
  (418, '364', 'Isfahan', 'İsfahan', 'Naqsh-e Jahan Square', 'Nakş-ı Cihan Meydanı', 'One of the world''s largest and most beautiful squares.', 'Dünyanın en büyük ve en güzel meydanlarından biri.'),
  (419, '364', 'Shiraz', 'Şiraz', 'Nasir al-Mulk Mosque', 'Nasir el-Mülk Camii', 'The Pink Mosque with kaleidoscopic stained glass.', 'Kaleydoskop gibi vitraylarıyla Pembe Cami.'),
  (420, '364', 'Persepolis', 'Persepolis', 'Persepolis', 'Persepolis', 'The ceremonial capital of the Persian Empire.', 'Pers İmparatorluğu''nun tören başkenti.'),
  (421, '860', 'Samarkand', 'Semerkant', 'Registan Square', 'Registan Meydanı', 'Three madrasas decorated with dazzling blue tilework.', 'Göz alıcı mavi çinilerle süslü üç medrese.'),
  (422, '860', 'Bukhara', 'Buhara', 'Bukhara Old Town', 'Buhara Eski Şehir', 'A Silk Road city of domes, minarets and bazaars.', 'Kubbeler, minareler ve çarşılarla İpek Yolu şehri.'),
  (423, '860', 'Khiva', 'Hive', 'Itchan Kala (Khiva)', 'İçan Kale (Hive)', 'A fully walled desert city of turquoise minarets.', 'Turkuaz minareli, tamamen surlu çöl şehri.'),
  (424, '398', 'Almaty', 'Almatı', 'Charyn Canyon', 'Çarın Kanyonu', 'A red-rock canyon called the little Grand Canyon.', 'Küçük Grand Canyon olarak bilinen kızıl kayalı kanyon.'),
  (425, '398', 'Almaty', 'Almatı', 'Big Almaty Lake', 'Büyük Almatı Gölü', 'An alpine turquoise lake in the mountains.', 'Dağlarda turkuaz alpin göl.'),
  (426, '417', 'Issyk-Kul', 'Issık Göl', 'Issyk-Kul Lake', 'Issık Göl', 'A vast, warm alpine lake that never freezes.', 'Hiç donmayan geniş ve ılık dağ gölü.'),
  (427, '417', 'Karakol', 'Karakol', 'Jeti-Oguz', 'Cety-Öğüz', 'Red cliffs known as the Seven Bulls.', 'Yedi Boğa olarak bilinen kızıl kayalıklar.'),
  (428, '051', 'Garni', 'Garni', 'Garni Temple', 'Garni Tapınağı', 'A Greco-Roman temple in the Armenian mountains.', 'Ermeni dağlarında bir Greko-Romen tapınağı.'),
  (429, '051', 'Khor Virap', 'Khor Virap', 'Khor Virap Monastery', 'Khor Virap Manastırı', 'A monastery with a famous view of Mount Ararat.', 'Ağrı Dağı manzarasıyla ünlü manastır.'),
  (430, '051', 'Yerevan', 'Erivan', 'Cascade Complex', 'Cascade Kompleksi', 'A giant stairway with art and city views.', 'Sanat eserleri ve şehir manzaralı dev merdiven.'),
  (431, '496', 'Ulaanbaatar', 'Ulan Batur', 'Genghis Khan Statue', 'Cengiz Han Heykeli', 'A giant equestrian statue on the steppe.', 'Bozkırda dev at sırtında heykel.'),
  (432, '496', 'Gobi', 'Gobi', 'Gobi Desert (Flaming Cliffs)', 'Gobi Çölü (Alev Kayalıkları)', 'Red sandstone cliffs famed for dinosaur fossils.', 'Dinozor fosilleriyle ünlü kırmızı kumtaşı kayalıklar.'),
  (433, '064', 'Paro', 'Paro', 'Tiger''s Nest Monastery', 'Kaplan Yuvası Manastırı', 'A cliffside monastery high above Paro Valley.', 'Paro Vadisi''nin çok üzerinde uçurum kenarında manastır.'),
  (434, '064', 'Thimphu', 'Thimphu', 'Buddha Dordenma', 'Buda Dordenma', 'A giant golden Buddha overlooking the capital.', 'Başkente bakan dev altın Buda.'),
  (435, '586', 'Lahore', 'Lahor', 'Badshahi Mosque', 'Badşahi Camii', 'A vast Mughal mosque of red sandstone.', 'Kırmızı kumtaşından geniş Babür camii.'),
  (436, '586', 'Hunza', 'Hunza', 'Hunza Valley', 'Hunza Vadisi', 'A mountain valley beneath snowy peaks and orchards.', 'Karlı zirveler ve meyve bahçeleri altında dağ vadisi.'),
  (437, '050', 'Dhaka', 'Dakka', 'Lalbagh Fort', 'Lalbağ Kalesi', 'An unfinished 17th-century Mughal fort.', 'Tamamlanmamış 17. yüzyıl Babür kalesi.'),
  (438, '050', 'Sundarbans', 'Sundarbans', 'Sundarbans Mangrove Forest', 'Sundarbans Mangrov Ormanı', 'The largest mangrove forest and home of the Bengal tiger.', 'En büyük mangrov ormanı ve Bengal kaplanının yurdu.'),
  (439, '104', 'Bagan', 'Bagan', 'Bagan Temples', 'Bagan Tapınakları', 'Thousands of pagodas across a misty plain.', 'Sisli ovada binlerce pagoda.'),
  (440, '104', 'Yangon', 'Yangon', 'Shwedagon Pagoda', 'Shwedagon Pagodası', 'A gilded stupa glowing over Yangon.', 'Yangon''un üzerinde parlayan yaldızlı stupa.'),
  (441, '104', 'Inle', 'Inle', 'Inle Lake', 'Inle Gölü', 'Leg-rowing fishermen and floating gardens.', 'Ayakla kürek çeken balıkçılar ve yüzen bahçeler.'),
  (442, '418', 'Luang Prabang', 'Luang Prabang', 'Kuang Si Falls', 'Kuang Si Şelaleleri', 'Turquoise pools beneath a tiered waterfall.', 'Basamaklı şelalenin altında turkuaz havuzlar.'),
  (443, '418', 'Luang Prabang', 'Luang Prabang', 'Alms Giving Ceremony', 'Sadaka Töreni', 'Saffron-robed monks collecting alms at dawn.', 'Şafakta sadaka toplayan safran cübbeli keşişler.'),
  (444, '158', 'Taipei', 'Taipei', 'Taipei 101', 'Taipei 101', 'A bamboo-inspired skyscraper with a fast elevator.', 'Bambudan ilham alan, hızlı asansörlü gökdelen.'),
  (445, '158', 'Jiufen', 'Jiufen', 'Jiufen Old Street', 'Jiufen Eski Sokağı', 'Lantern-lit lanes on a hillside above the sea.', 'Denize bakan yamaçta fener ışıklı sokaklar.'),
  (446, '158', 'Taroko', 'Taroko', 'Taroko Gorge', 'Taroko Vadisi', 'Marble canyon walls and winding trails.', 'Mermer kanyon duvarları ve kıvrımlı patikalar.'),
  (447, '233', 'Tallinn', 'Tallinn', 'Tallinn Old Town', 'Tallinn Eski Şehir', 'A medieval walled town with cobbled streets.', 'Arnavut kaldırımlı sokaklarıyla ortaçağ surlu şehri.'),
  (448, '233', 'Lahemaa', 'Lahemaa', 'Lahemaa National Park', 'Lahemaa Milli Parkı', 'Forests, bogs and manor houses on the coast.', 'Kıyıda ormanlar, bataklıklar ve malikâneler.'),
  (449, '428', 'Riga', 'Riga', 'Riga Old Town', 'Riga Eski Şehir', 'Art Nouveau facades and Gothic spires.', 'Art Nouveau cepheler ve Gotik kuleler.'),
  (450, '428', 'Sigulda', 'Sigulda', 'Turaida Castle', 'Turaida Kalesi', 'A red-brick medieval castle in a forest valley.', 'Orman vadisinde kırmızı tuğlalı ortaçağ kalesi.'),
  (451, '440', 'Vilnius', 'Vilnius', 'Vilnius Old Town', 'Vilnius Eski Şehir', 'One of Europe''s largest baroque old towns.', 'Avrupa''nın en büyük barok eski şehirlerinden biri.'),
  (452, '440', 'Trakai', 'Trakai', 'Trakai Island Castle', 'Trakai Ada Kalesi', 'A brick castle on an island in a lake.', 'Göl ortasındaki adada tuğla kale.'),
  (453, '440', 'Klaipeda', 'Klaipėda', 'Hill of Crosses', 'Haçlar Tepesi', 'A hill covered with hundreds of thousands of crosses.', 'Yüz binlerce haçla kaplı tepe.'),
  (454, '705', 'Bled', 'Bled', 'Lake Bled', 'Bled Gölü', 'A church island in a glacial lake beneath a castle.', 'Kalenin altındaki buzul gölünde kilise adası.'),
  (455, '705', 'Postojna', 'Postojna', 'Postojna Cave', 'Postojna Mağarası', 'A huge karst cave system explored by train.', 'Trenle gezilen geniş karst mağara sistemi.'),
  (456, '705', 'Ljubljana', 'Ljubljana', 'Ljubljana Old Town', 'Ljubljana Eski Şehir', 'A car-free riverside center with Triple Bridge.', 'Üçlü Köprü''lü araçsız nehir kıyısı merkezi.'),
  (457, '703', 'Bratislava', 'Bratislava', 'Bratislava Castle', 'Bratislava Kalesi', 'A white hilltop castle above the Danube.', 'Tuna''ya bakan beyaz tepe kalesi.'),
  (458, '703', 'High Tatras', 'Yüksek Tatralar', 'High Tatras', 'Yüksek Tatralar', 'Jagged peaks, lakes and hiking trails.', 'Sivri tepeler, göller ve yürüyüş parkurları.'),
  (459, '642', 'Brasov', 'Braşov', 'Bran Castle', 'Bran Şatosu', 'The castle linked to the Dracula legend.', 'Drakula efsanesiyle anılan şato.'),
  (460, '642', 'Transylvania', 'Transilvanya', 'Transfagarasan Highway', 'Transfagarasan Yolu', 'A spectacular mountain road of hairpin bends.', 'Saç tokası virajlarla muhteşem dağ yolu.'),
  (461, '642', 'Bucharest', 'Bükreş', 'Palace of the Parliament', 'Parlamento Sarayı', 'The heaviest building in the world.', 'Dünyanın en ağır binası.'),
  (462, '100', 'Sofia', 'Sofya', 'Alexander Nevsky Cathedral', 'Aleksandr Nevski Katedrali', 'A golden-domed Orthodox cathedral.', 'Altın kubbeli Ortodoks katedrali.'),
  (463, '100', 'Rila', 'Rila', 'Rila Monastery', 'Rila Manastırı', 'A striped, frescoed monastery in the mountains.', 'Dağlarda çizgili, fresklerle süslü manastır.'),
  (464, '100', 'Plovdiv', 'Filibe', 'Plovdiv Roman Theatre', 'Filibe Roma Tiyatrosu', 'A well-preserved Roman theatre in the old town.', 'Eski şehirde iyi korunmuş Roma tiyatrosu.'),
  (465, '688', 'Belgrade', 'Belgrad', 'Belgrade Fortress', 'Belgrad Kalesi', 'A fortress at the meeting of the Sava and Danube.', 'Sava ve Tuna''nın birleştiği yerde kale.'),
  (466, '688', 'Novi Sad', 'Novi Sad', 'Petrovaradin Fortress', 'Petrovaradin Kalesi', 'The Gibraltar of the Danube.', 'Tuna''nın Cebelitarık''ı.'),
  (467, '070', 'Mostar', 'Mostar', 'Stari Most', 'Mostar Köprüsü', 'The reconstructed Ottoman bridge arching over the Neretva.', 'Neretva üzerinde kavis yapan yeniden inşa edilmiş Osmanlı köprüsü.'),
  (468, '070', 'Sarajevo', 'Saraybosna', 'Bascarsija', 'Başçarşı', 'The Ottoman bazaar heart of Sarajevo.', 'Saraybosna''nın Osmanlı çarşı merkezi.'),
  (469, '070', 'Kravice', 'Kravice', 'Kravice Waterfalls', 'Kravice Şelaleleri', 'A wide cascade you can swim beneath.', 'Altında yüzülebilen geniş şelale.'),
  (470, '499', 'Kotor', 'Kotor', 'Bay of Kotor', 'Kotor Körfezi', 'A fjord-like bay and a walled medieval town.', 'Fiyort benzeri körfez ve surlu ortaçağ kasabası.'),
  (471, '499', 'Budva', 'Budva', 'Sveti Stefan', 'Sveti Stefan', 'A fortified island village joined by a causeway.', 'Kara yoluyla bağlanan surlu ada köyü.'),
  (472, '008', 'Berat', 'Berat', 'Berat Old Town', 'Berat Eski Şehir', 'The ''town of a thousand windows''.', '''Bin pencereli şehir''.'),
  (473, '008', 'Saranda', 'Sarandë', 'Ksamil Islands', 'Ksamil Adaları', 'Crystal-clear Ionian water around small islets.', 'Küçük adacıklar çevresinde berrak İyon denizi.'),
  (474, '807', 'Ohrid', 'Ohrid', 'Lake Ohrid', 'Ohrid Gölü', 'One of Europe''s oldest and deepest lakes.', 'Avrupa''nın en eski ve en derin göllerinden biri.'),
  (475, '807', 'Skopje', 'Üsküp', 'Stone Bridge, Skopje', 'Taş Köprü, Üsküp', 'A 15th-century Ottoman bridge over the Vardar.', 'Vardar üzerinde 15. yüzyıldan kalma Osmanlı köprüsü.'),
  (476, '372', 'County Clare', 'County Clare', 'Cliffs of Moher', 'Moher Kayalıkları', 'Sheer sea cliffs rising 214 metres above the Atlantic.', 'Atlantik''in 214 metre üzerinde yükselen sarp deniz kayalıkları.'),
  (477, '372', 'Dublin', 'Dublin', 'Trinity College Library', 'Trinity College Kütüphanesi', 'The Long Room and the Book of Kells.', 'Long Room ve Kells Kitabı.'),
  (478, '372', 'Kerry', 'Kerry', 'Ring of Kerry', 'Ring of Kerry', 'A scenic coastal drive around the Iveragh Peninsula.', 'Iveragh Yarımadası çevresinde manzaralı sahil yolu.'),
  (479, '442', 'Luxembourg City', 'Lüksemburg', 'Bock Casemates', 'Bock Kazamatları', 'Underground tunnels in the old fortress rock.', 'Eski kale kayasında yeraltı tünelleri.'),
  (480, '804', 'Kyiv', 'Kiev', 'Saint Sophia Cathedral', 'Aziz Sofya Katedrali', 'An 11th-century cathedral with golden domes.', 'Altın kubbeli 11. yüzyıl katedrali.'),
  (481, '804', 'Lviv', 'Lviv', 'Lviv Old Town', 'Lviv Eski Şehir', 'A Habsburg-era center with cobbled squares.', 'Arnavut kaldırımlı meydanlarıyla Habsburg dönemi merkezi.'),
  (482, '304', 'Ilulissat', 'Ilulissat', 'Ilulissat Icefjord', 'Ilulissat Buz Fiyordu', 'Giant icebergs calved from a glacier.', 'Bir buzuldan kopan dev buz dağları.'),
  (483, '132', 'Santo Antao', 'Santo Antão', 'Santo Antão Hiking Trails', 'Santo Antão Yürüyüş Parkurları', 'Volcanic ridges and green valleys.', 'Volkanik sırtlar ve yeşil vadiler.'),
  (484, '132', 'Sal', 'Sal', 'Sal Island Beaches', 'Sal Adası Plajları', 'Windsurfing and white-sand coasts.', 'Rüzgâr sörfü ve beyaz kumlu kıyılar.'),
  (485, '258', 'Bora Bora', 'Bora Bora', 'Bora Bora Lagoon', 'Bora Bora Lagünü', 'Overwater bungalows beneath Mount Otemanu.', 'Otemanu Dağı''nın altında su üstü bungalovlar.'),
  (486, '258', 'Moorea', 'Moorea', 'Moorea', 'Moorea', 'Jagged volcanic peaks around a blue lagoon.', 'Mavi lagünü çevreleyen sivri volkanik tepeler.'),
  (487, '598', 'Kokoda', 'Kokoda', 'Kokoda Track', 'Kokoda Patikası', 'A rugged jungle trek over WWII battlefields.', 'İkinci Dünya Savaşı cephelerinden geçen zorlu orman yürüyüşü.'),
  (488, '630', 'San Juan', 'San Juan', 'Old San Juan', 'Eski San Juan', 'Blue cobblestones and Spanish forts.', 'Mavi arnavut kaldırımları ve İspanyol kaleleri.'),
  (489, '052', 'Bridgetown', 'Bridgetown', 'Crane Beach', 'Crane Plajı', 'Pink sand and rolling surf in Barbados.', 'Barbados''ta pembe kum ve dalgalı deniz.'),
  (490, '332', 'Cap-Haitien', 'Cap-Haïtien', 'Citadelle Laferrière', 'Laferrière Kalesi', 'A mountaintop fortress built after independence.', 'Bağımsızlıktan sonra inşa edilmiş dağ başı kalesi.'),
  (491, '740', 'Paramaribo', 'Paramaribo', 'Paramaribo Historic Center', 'Paramaribo Tarihi Merkezi', 'Wooden colonial buildings beside a mosque and synagogue.', 'Cami ve sinagogun yanında ahşap sömürge binaları.'),
  (492, '862', 'Canaima', 'Canaima', 'Angel Falls', 'Angel Şelalesi', 'The world''s tallest uninterrupted waterfall.', 'Dünyanın kesintisiz en yüksek şelalesi.'),
  (493, '862', 'Los Roques', 'Los Roques', 'Los Roques Archipelago', 'Los Roques Takımadaları', 'A protected Caribbean archipelago of coral reefs.', 'Mercan resifli korunan Karayip takımadası.'),
  (494, '600', 'Asuncion', 'Asunción', 'Jesuit Missions of La Santisima Trinidad', 'La Santísima Trinidad Cizvit Misyonları', 'Ruins of an 18th-century Jesuit reduction.', '18. yüzyıl Cizvit yerleşkesinin kalıntıları.'),
  (495, '760', 'Palmyra', 'Palmira', 'Palmyra', 'Palmira', 'The ancient desert oasis city of columns.', 'Sütunlarıyla antik çöl vahası şehri.'),
  (496, '760', 'Damascus', 'Şam', 'Umayyad Mosque', 'Emevi Camii', 'One of the oldest and largest mosques in the world.', 'Dünyanın en eski ve en büyük camilerinden biri.'),
  (497, '368', 'Babylon', 'Babil', 'Babylon Ruins', 'Babil Kalıntıları', 'The ruins of the ancient Mesopotamian capital.', 'Antik Mezopotamya başkentinin kalıntıları.'),
  (498, '368', 'Erbil', 'Erbil', 'Erbil Citadel', 'Erbil Kalesi', 'A continuously inhabited hilltop citadel.', 'Kesintisiz yaşanan tepe kalesi.'),
  (499, '048', 'Manama', 'Manama', 'Bahrain Fort', 'Bahreyn Kalesi', 'An archaeological site layered over 4,000 years.', '4000 yıllık katmanlara sahip arkeolojik alan.'),
  (500, '414', 'Kuwait City', 'Kuveyt', 'Kuwait Towers', 'Kuveyt Kuleleri', 'Slender towers that symbolize Kuwait.', 'Kuveyt''in sembolü ince kuleler.'),
  (501, '887', 'Sanaa', 'Sana', 'Old City of Sanaa', 'Sana Eski Şehir', 'Tower houses with white gypsum decoration.', 'Beyaz alçı süslemeli kule evler.'),
  (502, '887', 'Socotra', 'Sokotra', 'Socotra Dragon Blood Trees', 'Sokotra Ejder Kanı Ağaçları', 'Umbrella-shaped trees found nowhere else.', 'Başka yerde olmayan şemsiye biçimli ağaçlar.'),
  (503, '004', 'Bamyan', 'Bamiyan', 'Band-e Amir Lakes', 'Bend-i Emir Gölleri', 'Deep blue lakes separated by natural travertine dams.', 'Doğal traverten barajlarla ayrılmış koyu mavi göller.'),
  (504, '762', 'Pamir', 'Pamir', 'Pamir Highway', 'Pamir Karayolu', 'One of the world''s highest and most dramatic road trips.', 'Dünyanın en yüksek ve en çarpıcı yol gezilerinden biri.'),
  (505, '795', 'Darvaza', 'Derweze', 'Darvaza Gas Crater', 'Derweze Gaz Krateri', 'The ''Door to Hell'', a burning crater in the desert.', 'Çölde yanan krater: ''Cehennemin Kapısı''.'),
  (506, '112', 'Mir', 'Mir', 'Mir Castle', 'Mir Kalesi', 'A fairytale castle complex in Belarus.', 'Belarus''ta masalsı bir kale kompleksi.'),
  (507, '498', 'Chisinau', 'Kişinev', 'Cricova Wine Cellars', 'Cricova Şarap Mahzenleri', 'An underground wine city with kilometres of tunnels.', 'Kilometrelerce tünelli yeraltı şarap şehri.'),
  (508, '196', 'Paphos', 'Baf', 'Tombs of the Kings', 'Krallar Mezarları', 'Underground rock-cut tombs near the coast.', 'Kıyıya yakın yeraltı kaya mezarları.'),
  (509, '196', 'Paphos', 'Baf', 'Aphrodite''s Rock', 'Afrodit Kayası', 'The legendary birthplace of Aphrodite.', 'Afrodit''in efsanevi doğum yeri.'),
  (510, '020', 'Andorra la Vella', 'Andorra la Vella', 'Caldea Spa', 'Caldea Spa', 'A large thermal spa in the Pyrenees.', 'Pireneler''de büyük termal spa.'),
  (511, '492', 'Monaco', 'Monako', 'Monte Carlo Casino', 'Monte Carlo Kumarhanesi', 'A Belle Époque casino with an opulent atrium.', 'Gösterişli atriumlu Belle Époque kumarhane.'),
  (512, '674', 'San Marino', 'San Marino', 'Guaita Tower', 'Guaita Kulesi', 'A medieval tower on Mount Titano.', 'Titano Dağı''nda ortaçağ kulesi.'),
  (513, '438', 'Vaduz', 'Vaduz', 'Vaduz Castle', 'Vaduz Şatosu', 'The prince''s hilltop castle above the capital.', 'Başkentin üzerinde prensin tepe şatosu.'),
  (514, '336', 'Vatican City', 'Vatikan', 'St. Peter''s Basilica', 'Aziz Petrus Bazilikası', 'The heart of the Catholic world and Michelangelo''s dome.', 'Katolik dünyasının kalbi ve Michelangelo''nun kubbesi.'),
  (515, '336', 'Vatican City', 'Vatikan', 'Sistine Chapel', 'Sistina Şapeli', 'Michelangelo''s ceiling frescoes.', 'Michelangelo''nun tavan freskleri.');

-- Cities (reuses an existing city with the same English name per country).
insert into public.cities (country_id, name, name_tr)
select distinct on (country_id, city) country_id, city, city_tr
from _new_landmarks
order by country_id, city, ord
on conflict (country_id, name) do nothing;

-- Landmarks. sort_order follows list order (all above add_landmarks.sql's
-- 1-98), so a city's older landmarks keep showing first.
insert into public.landmarks
  (country_id, city_id, name, name_tr, description, description_tr, sort_order)
select n.country_id, c.id, n.name, n.name_tr, n.description, n.description_tr, n.ord
from _new_landmarks n
join public.cities c on c.country_id = n.country_id and c.name = n.city
order by n.ord
on conflict (city_id, name) do nothing;

commit;

-- Optional, on its own: make specific landmarks show in "Yeni eklenenler".
-- Replace the names in the list, then run.
--
-- insert into public.catalog_highlights
--   (type, item_id, title, title_tr, subtitle, subtitle_tr, image_url)
-- select 'landmarks', l.id::text, l.name, l.name_tr, null, null, l.image_url
-- from public.landmarks l
-- where l.name in ('Blue Mosque', 'Troy')
-- on conflict (type, item_id) do nothing;
