-- Run this once in the Supabase SQL editor (Database > SQL Editor).
-- Safe to re-run: every statement is idempotent.
--
-- Read-only reference table mirroring data/worldCountries.json (id, name,
-- Turkish name, ISO2) so you can write cuisine_meals/catalog_highlights
-- inserts by country NAME instead of memorizing/copying numeric ids —
-- Postgres resolves the id for you, so a typo just matches zero rows
-- (loud/obvious) instead of silently pointing at a nonexistent country.
--
-- The app itself never reads this table — it's purely a founder-workflow
-- convenience for writing SQL in the dashboard. If worldCountries.json ever
-- changes, regenerate this file's INSERT block from it rather than hand-
-- editing rows.

create table if not exists public.countries (
  id text primary key,
  name text not null,
  name_tr text not null,
  iso2 text
);

alter table public.countries enable row level security;

drop policy if exists "Anyone can read countries" on public.countries;
create policy "Anyone can read countries"
  on public.countries
  for select
  using (true);

insert into public.countries (id, name, name_tr, iso2)
values
  ('716', 'Zimbabwe', 'Zimbabve', 'ZW'),
  ('894', 'Zambia', 'Zambiya', 'ZM'),
  ('887', 'Yemen', 'Yemen', 'YE'),
  ('704', 'Vietnam', 'Vietnam', 'VN'),
  ('862', 'Venezuela', 'Venezuela', 'VE'),
  ('336', 'Vatican', 'Vatikan', 'VA'),
  ('548', 'Vanuatu', 'Vanuatu', 'VU'),
  ('860', 'Uzbekistan', 'Özbekistan', 'UZ'),
  ('858', 'Uruguay', 'Uruguay', 'UY'),
  ('583', 'Micronesia', 'Mikronezya', 'FM'),
  ('584', 'Marshall Is.', 'Marshall Adaları', 'MH'),
  ('580', 'N. Mariana Is.', 'Kuzey Mariana Adaları', 'MP'),
  ('850', 'U.S. Virgin Is.', 'ABD Virjin Adaları', 'VI'),
  ('316', 'Guam', 'Guam', 'GU'),
  ('016', 'American Samoa', 'Amerikan Samoası', 'AS'),
  ('630', 'Puerto Rico', 'Porto Riko', 'PR'),
  ('840', 'United States of America', 'Amerika Birleşik Devletleri', 'US'),
  ('239', 'S. Geo. and the Is.', 'Güney Georgia ve Güney Sandwich Adaları', 'GS'),
  ('086', 'Br. Indian Ocean Ter.', 'Britanya Hint Okyanusu Toprakları', 'IO'),
  ('654', 'Saint Helena', 'Saint Helena', 'SH'),
  ('612', 'Pitcairn Is.', 'Pitcairn Adaları', 'PN'),
  ('660', 'Anguilla', 'Anguilla', 'AI'),
  ('238', 'Falkland Is.', 'Falkland Adaları', 'FK'),
  ('136', 'Cayman Is.', 'Cayman Adaları', 'KY'),
  ('060', 'Bermuda', 'Bermuda', 'BM'),
  ('092', 'British Virgin Is.', 'Britanya Virjin Adaları', 'VG'),
  ('796', 'Turks and Caicos Is.', 'Turks ve Caicos Adaları', 'TC'),
  ('500', 'Montserrat', 'Montserrat', 'MS'),
  ('832', 'Jersey', 'Jersey', 'JE'),
  ('831', 'Guernsey', 'Guernsey', 'GG'),
  ('833', 'Isle of Man', 'Man Adası', 'IM'),
  ('826', 'United Kingdom', 'Birleşik Krallık', 'GB'),
  ('784', 'United Arab Emirates', 'Birleşik Arap Emirlikleri', 'AE'),
  ('804', 'Ukraine', 'Ukrayna', 'UA'),
  ('800', 'Uganda', 'Uganda', 'UG'),
  ('795', 'Turkmenistan', 'Türkmenistan', 'TM'),
  ('792', 'Turkey', 'Türkiye', 'TR'),
  ('788', 'Tunisia', 'Tunus', 'TN'),
  ('780', 'Trinidad and Tobago', 'Trinidad ve Tobago', 'TT'),
  ('776', 'Tonga', 'Tonga', 'TO'),
  ('768', 'Togo', 'Togo', 'TG'),
  ('626', 'Timor-Leste', 'Doğu Timor', 'TL'),
  ('764', 'Thailand', 'Tayland', 'TH'),
  ('834', 'Tanzania', 'Tanzanya', 'TZ'),
  ('762', 'Tajikistan', 'Tacikistan', 'TJ'),
  ('158', 'Taiwan', 'Tayvan', 'TW'),
  ('760', 'Syria', 'Suriye', 'SY'),
  ('756', 'Switzerland', 'İsviçre', 'CH'),
  ('752', 'Sweden', 'İsveç', 'SE'),
  ('748', 'eSwatini', 'Esvatini', 'SZ'),
  ('740', 'Suriname', 'Surinam', 'SR'),
  ('728', 'S. Sudan', 'Güney Sudan', 'SS'),
  ('729', 'Sudan', 'Sudan', 'SD'),
  ('144', 'Sri Lanka', 'Sri Lanka', 'LK'),
  ('724', 'Spain', 'İspanya', 'ES'),
  ('410', 'South Korea', 'Güney Kore', 'KR'),
  ('710', 'South Africa', 'Güney Afrika', 'ZA'),
  ('706', 'Somalia', 'Somali', 'SO'),
  ('zz-somaliland', 'Somaliland', 'Somaliland', null),
  ('090', 'Solomon Is.', 'Solomon Adaları', 'SB'),
  ('703', 'Slovakia', 'Slovakya', 'SK'),
  ('705', 'Slovenia', 'Slovenya', 'SI'),
  ('702', 'Singapore', 'Singapur', 'SG'),
  ('694', 'Sierra Leone', 'Sierra Leone', 'SL'),
  ('690', 'Seychelles', 'Seyşeller', 'SC'),
  ('688', 'Serbia', 'Sırbistan', 'RS'),
  ('686', 'Senegal', 'Senegal', 'SN'),
  ('682', 'Saudi Arabia', 'Suudi Arabistan', 'SA'),
  ('678', 'São Tomé and Principe', 'São Tomé ve Príncipe', 'ST'),
  ('674', 'San Marino', 'San Marino', 'SM'),
  ('882', 'Samoa', 'Samoa', 'WS'),
  ('670', 'St. Vin. and Gren.', 'Saint Vincent ve Grenadinler', 'VC'),
  ('662', 'Saint Lucia', 'Saint Lucia', 'LC'),
  ('659', 'St. Kitts and Nevis', 'Saint Kitts ve Nevis', 'KN'),
  ('646', 'Rwanda', 'Ruanda', 'RW'),
  ('643', 'Russia', 'Rusya', 'RU'),
  ('642', 'Romania', 'Romanya', 'RO'),
  ('634', 'Qatar', 'Katar', 'QA'),
  ('620', 'Portugal', 'Portekiz', 'PT'),
  ('616', 'Poland', 'Polonya', 'PL'),
  ('608', 'Philippines', 'Filipinler', 'PH'),
  ('604', 'Peru', 'Peru', 'PE'),
  ('600', 'Paraguay', 'Paraguay', 'PY'),
  ('598', 'Papua New Guinea', 'Papua Yeni Gine', 'PG'),
  ('591', 'Panama', 'Panama', 'PA'),
  ('585', 'Palau', 'Palau', 'PW'),
  ('586', 'Pakistan', 'Pakistan', 'PK'),
  ('512', 'Oman', 'Umman', 'OM'),
  ('578', 'Norway', 'Norveç', 'NO'),
  ('408', 'North Korea', 'Kuzey Kore', 'KP'),
  ('566', 'Nigeria', 'Nijerya', 'NG'),
  ('562', 'Niger', 'Nijer', 'NE'),
  ('558', 'Nicaragua', 'Nikaragua', 'NI'),
  ('554', 'New Zealand', 'Yeni Zelanda', 'NZ'),
  ('570', 'Niue', 'Niue', 'NU'),
  ('184', 'Cook Is.', 'Cook Adaları', 'CK'),
  ('528', 'Netherlands', 'Hollanda', 'NL'),
  ('533', 'Aruba', 'Aruba', 'AW'),
  ('531', 'Curaçao', 'Curaçao', 'CW'),
  ('524', 'Nepal', 'Nepal', 'NP'),
  ('520', 'Nauru', 'Nauru', 'NR'),
  ('516', 'Namibia', 'Namibya', 'NA'),
  ('508', 'Mozambique', 'Mozambik', 'MZ'),
  ('504', 'Morocco', 'Fas', 'MA'),
  ('732', 'W. Sahara', 'Batı Sahra', 'EH'),
  ('499', 'Montenegro', 'Karadağ', 'ME'),
  ('496', 'Mongolia', 'Moğolistan', 'MN'),
  ('498', 'Moldova', 'Moldova', 'MD'),
  ('492', 'Monaco', 'Monako', 'MC'),
  ('484', 'Mexico', 'Meksika', 'MX'),
  ('480', 'Mauritius', 'Mauritius', 'MU'),
  ('478', 'Mauritania', 'Moritanya', 'MR'),
  ('470', 'Malta', 'Malta', 'MT'),
  ('466', 'Mali', 'Mali', 'ML'),
  ('462', 'Maldives', 'Maldivler', 'MV'),
  ('458', 'Malaysia', 'Malezya', 'MY'),
  ('454', 'Malawi', 'Malavi', 'MW'),
  ('450', 'Madagascar', 'Madagaskar', 'MG'),
  ('807', 'Macedonia', 'Kuzey Makedonya', 'MK'),
  ('442', 'Luxembourg', 'Lüksemburg', 'LU'),
  ('440', 'Lithuania', 'Litvanya', 'LT'),
  ('438', 'Liechtenstein', 'Lihtenştayn', 'LI'),
  ('434', 'Libya', 'Libya', 'LY'),
  ('430', 'Liberia', 'Liberya', 'LR'),
  ('426', 'Lesotho', 'Lesotho', 'LS'),
  ('422', 'Lebanon', 'Lübnan', 'LB'),
  ('428', 'Latvia', 'Letonya', 'LV'),
  ('418', 'Laos', 'Laos', 'LA'),
  ('417', 'Kyrgyzstan', 'Kırgızistan', 'KG'),
  ('414', 'Kuwait', 'Kuveyt', 'KW'),
  ('zz-kosovo', 'Kosovo', 'Kosova', null),
  ('296', 'Kiribati', 'Kiribati', 'KI'),
  ('404', 'Kenya', 'Kenya', 'KE'),
  ('398', 'Kazakhstan', 'Kazakistan', 'KZ'),
  ('400', 'Jordan', 'Ürdün', 'JO'),
  ('392', 'Japan', 'Japonya', 'JP'),
  ('388', 'Jamaica', 'Jamaika', 'JM'),
  ('380', 'Italy', 'İtalya', 'IT'),
  ('376', 'Israel', 'İsrail', 'IL'),
  ('275', 'Palestine', 'Filistin', 'PS'),
  ('372', 'Ireland', 'İrlanda', 'IE'),
  ('368', 'Iraq', 'Irak', 'IQ'),
  ('364', 'Iran', 'İran', 'IR'),
  ('360', 'Indonesia', 'Endonezya', 'ID'),
  ('356', 'India', 'Hindistan', 'IN'),
  ('352', 'Iceland', 'İzlanda', 'IS'),
  ('348', 'Hungary', 'Macaristan', 'HU'),
  ('340', 'Honduras', 'Honduras', 'HN'),
  ('332', 'Haiti', 'Haiti', 'HT'),
  ('328', 'Guyana', 'Guyana', 'GY'),
  ('624', 'Guinea-Bissau', 'Gine-Bissau', 'GW'),
  ('324', 'Guinea', 'Gine', 'GN'),
  ('320', 'Guatemala', 'Guatemala', 'GT'),
  ('308', 'Grenada', 'Grenada', 'GD'),
  ('300', 'Greece', 'Yunanistan', 'GR'),
  ('288', 'Ghana', 'Gana', 'GH'),
  ('276', 'Germany', 'Almanya', 'DE'),
  ('268', 'Georgia', 'Gürcistan', 'GE'),
  ('270', 'Gambia', 'Gambiya', 'GM'),
  ('266', 'Gabon', 'Gabon', 'GA'),
  ('250', 'France', 'Fransa', 'FR'),
  ('666', 'St. Pierre and Miquelon', 'Saint-Pierre ve Miquelon', 'PM'),
  ('876', 'Wallis and Futuna Is.', 'Wallis ve Futuna Adaları', 'WF'),
  ('663', 'St-Martin', 'Saint-Martin', 'MF'),
  ('652', 'St-Barthélemy', 'Saint-Barthélemy', 'BL'),
  ('258', 'Fr. Polynesia', 'Fransız Polinezyası', 'PF'),
  ('540', 'New Caledonia', 'Yeni Kaledonya', 'NC'),
  ('260', 'Fr. S. Antarctic Lands', 'Fransız Güney ve Antarktika Toprakları', 'TF'),
  ('248', 'Åland', 'Åland Adaları', 'AX'),
  ('246', 'Finland', 'Finlandiya', 'FI'),
  ('242', 'Fiji', 'Fiji', 'FJ'),
  ('231', 'Ethiopia', 'Etiyopya', 'ET'),
  ('233', 'Estonia', 'Estonya', 'EE'),
  ('232', 'Eritrea', 'Eritre', 'ER'),
  ('226', 'Eq. Guinea', 'Ekvator Ginesi', 'GQ'),
  ('222', 'El Salvador', 'El Salvador', 'SV'),
  ('818', 'Egypt', 'Mısır', 'EG'),
  ('218', 'Ecuador', 'Ekvador', 'EC'),
  ('214', 'Dominican Rep.', 'Dominik Cumhuriyeti', 'DO'),
  ('212', 'Dominica', 'Dominika', 'DM'),
  ('262', 'Djibouti', 'Cibuti', 'DJ'),
  ('304', 'Greenland', 'Grönland', 'GL'),
  ('234', 'Faeroe Is.', 'Faroe Adaları', 'FO'),
  ('208', 'Denmark', 'Danimarka', 'DK'),
  ('203', 'Czechia', 'Çekya', 'CZ'),
  ('zz-n-cyprus', 'N. Cyprus', 'Kuzey Kıbrıs', 'CY'),
  ('196', 'Cyprus', 'Kıbrıs', 'CY'),
  ('192', 'Cuba', 'Küba', 'CU'),
  ('191', 'Croatia', 'Hırvatistan', 'HR'),
  ('384', 'Côte d''Ivoire', 'Fildişi Sahili', 'CI'),
  ('188', 'Costa Rica', 'Kosta Rika', 'CR'),
  ('180', 'Dem. Rep. Congo', 'Kongo Demokratik Cumhuriyeti', 'CD'),
  ('178', 'Congo', 'Kongo', 'CG'),
  ('174', 'Comoros', 'Komorlar', 'KM'),
  ('170', 'Colombia', 'Kolombiya', 'CO'),
  ('156', 'China', 'Çin', 'CN'),
  ('446', 'Macao', 'Makao', 'MO'),
  ('344', 'Hong Kong', 'Hong Kong', 'HK'),
  ('152', 'Chile', 'Şili', 'CL'),
  ('148', 'Chad', 'Çad', 'TD'),
  ('140', 'Central African Rep.', 'Orta Afrika Cumhuriyeti', 'CF'),
  ('132', 'Cabo Verde', 'Cape Verde', 'CV'),
  ('124', 'Canada', 'Kanada', 'CA'),
  ('120', 'Cameroon', 'Kamerun', 'CM'),
  ('116', 'Cambodia', 'Kamboçya', 'KH'),
  ('104', 'Myanmar', 'Myanmar', 'MM'),
  ('108', 'Burundi', 'Burundi', 'BI'),
  ('854', 'Burkina Faso', 'Burkina Faso', 'BF'),
  ('100', 'Bulgaria', 'Bulgaristan', 'BG'),
  ('096', 'Brunei', 'Brunei', 'BN'),
  ('076', 'Brazil', 'Brezilya', 'BR'),
  ('072', 'Botswana', 'Botsvana', 'BW'),
  ('070', 'Bosnia and Herz.', 'Bosna Hersek', 'BA'),
  ('068', 'Bolivia', 'Bolivya', 'BO'),
  ('064', 'Bhutan', 'Butan', 'BT'),
  ('204', 'Benin', 'Benin', 'BJ'),
  ('084', 'Belize', 'Belize', 'BZ'),
  ('056', 'Belgium', 'Belçika', 'BE'),
  ('112', 'Belarus', 'Belarus', 'BY'),
  ('052', 'Barbados', 'Barbados', 'BB'),
  ('050', 'Bangladesh', 'Bangladeş', 'BD'),
  ('048', 'Bahrain', 'Bahreyn', 'BH'),
  ('044', 'Bahamas', 'Bahamalar', 'BS'),
  ('031', 'Azerbaijan', 'Azerbaycan', 'AZ'),
  ('040', 'Austria', 'Avusturya', 'AT'),
  ('036', 'Australia', 'Avustralya', 'AU'),
  ('zz-indian-ocean-ter', 'Indian Ocean Ter.', 'Hint Okyanusu Toprakları', null),
  ('334', 'Heard I. and McDonald Is.', 'Heard Adası ve McDonald Adaları', 'HM'),
  ('574', 'Norfolk Island', 'Norfolk Adası', 'NF'),
  ('051', 'Armenia', 'Ermenistan', 'AM'),
  ('032', 'Argentina', 'Arjantin', 'AR'),
  ('028', 'Antigua and Barb.', 'Antigua ve Barbuda', 'AG'),
  ('024', 'Angola', 'Angola', 'AO'),
  ('020', 'Andorra', 'Andorra', 'AD'),
  ('012', 'Algeria', 'Cezayir', 'DZ'),
  ('008', 'Albania', 'Arnavutluk', 'AL'),
  ('004', 'Afghanistan', 'Afganistan', 'AF'),
  ('zz-siachen-glacier', 'Siachen Glacier', 'Siachen Buzulu', null),
  ('534', 'Sint Maarten', 'Sint Maarten', 'SX')
on conflict (id) do update set
  name = excluded.name,
  name_tr = excluded.name_tr,
  iso2 = excluded.iso2;
